### ISSUE TITLE
Keep current line highlighted when geany loses focus?

### ISSUE THREAD

**Issue by paul1149** [geany/geany#3743] opened 2024-01-14 04:27 UTC
I'm using an adaption of a theme file, and this is the pertinent line:

`current_line=#000;#4d5a68;true`

This gives me a slightly softer background and sets the line apart. I searched around, but didn't find what the `True` and `False` parameters do in these line specs.

My problem is I'm constantly going back and forth between geany and another program, and each time I lose the line's highlighting, so I have to visually search for it.

What I would like is if the line would stay highlighted even when I'm focused on another program. This is the way Kate and Kwrite work.

Thanks much!

**Comment by paul1149** [comment] 2024-01-14 15:23
Amazing that there is a setting for this. So it has been well thought out. It makes sense to me that always visible is the default, as I see no advantage to hiding the highlighting when focus is lost, and in my case there would be a lot of advantage to maintaining it.

Thanks for the detective work!

**Comment by elextr** [comment] 2024-01-14 23:17
This is a duplicate of #1528 from 2017 by ... why its you!  The answer was the same then, but as nobody has made the PR (that I can find).  That indicates that it is likely that some users prefer the current behaviour, so although its likely most don't care it needs to be a preference, not simply switch the hard wired option, not that any PR has been forthcoming even for that.

Closing as duplicate

**Closed by elextr** 2024-01-14 23:17 UTC
Labels: enhancement

**Comment by paul1149** [comment] 2024-01-14 23:24
Okay sorry about that. It had been so long that I completely forgot that I had brought this issue up once earlier. I don't know the details of the mechanics, but I hope someone will consider making the necessary change. Be well.
