### ISSUE TITLE
Var keyword not highlighted in valid java

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#4001] opened 2024-10-16 19:34 UTC
Please could you highlight the the **var** keyword on line **3** in the following valid Java?

![image](https://github.com/user-attachments/assets/0f0df315-79f1-4bb5-9b13-98021c1ab901)

**Comment by techee** [comment] 2024-10-16 20:51
Closing as a duplicate of #3854.

I've assigned myself to #3854 and similar trivial problem reports and I'll try to make corresponding pull requests soon.

In the meantime you can just go to Tools->Configuration files->Filetype configuration->Programming languages->filetype.java, comment-out e.g. the `secondary=...` line and add `var` by yourself.

**Closed by techee** 2024-10-16 20:51 UTC

**Comment by elextr** [comment] 2024-10-16 21:37
s/comment-out/uncomment/ ???
