### ISSUE TITLE
ctrl+shift+v crashes geany!

### ISSUE THREAD

**Issue by lukensmall** [geany/geany#3190] opened 2022-05-02 18:48 UTC
I accidentally hit ctrl+shift+v (because it is paste in my terminal emulator of choice) and it often if not always crashes geany leaving a geany.core!

I suspect it may happen for other key combinations without keybindings.
I set it to a custom command to make it do nothing for now.

I'm using geany 1.36 on OpenBSD 7.1 on an x86_64 intel (amd64 platform) based system.

_Originally posted by @lukensmall in https://github.com/geany/geany/issues/2807#issuecomment-1115236932_

**Comment by elextr** [comment] 2022-05-02 23:06
To be fixed by #3153

**Comment by eht16** [comment] 2022-05-15 16:02
@elextr isn't this report rather a duplicate of https://github.com/geany/geany/issues/2813 or am I just confused?

**Comment by elextr** [comment] 2022-05-15 23:50
@eht16 you are right, I just just got confused between the VTE issues :-)

So duplicate of #2183 and S/B fixed by #3091, right?

**Closed by elextr** 2022-05-15 23:50 UTC

**Comment by eht16** [comment] 2022-05-16 21:43
> So duplicate of #2183 and S/B fixed by #3091, right?

Yes!
