### ISSUE TITLE
Geany doesn't respond to dot (.) 

### ISSUE THREAD

**Issue by dibyendu1** [geany/geany#2472] opened 2020-04-10 07:16 UTC
Hello.... 

I am new to this forum.. and I am using Windows 10.

I have started coding on Geany for learning python. I saved a file as "Something.py" then I start to code.

Well... I have an issue when I type dot (.) . It doesn't respond to a single tap. I have to type it twice, then two dots appear on the screen, then I have to delete one and then continue the coding. 

When i press dot and then type and character other than "r" , the dot and the character shows up at the same time. But when i press dot and a "r" , nothing shows up! (Tried several times!!)

How to solve it? My keyboard is working fine (checked on other text editors).

Thank you.

EDIT : Realized the same happens with the comma (,)

**Comment by codebrainz** [comment] 2020-04-10 17:36
Duplicate of #1902 and likely others related to keyboard layouts on Windows.

**Closed by codebrainz** 2020-04-10 17:36 UTC
Labels: windows
