### ISSUE TITLE
Weird vertical line always shows in the centre.

### ISSUE THREAD

**Issue by apoorv569** [geany/geany#2565] opened 2020-08-03 06:36 UTC
In Geany I have this weird vertical line always showing in the center, Its annoying to me, is there a way to hide it? I am on Arch Linux, and have `geany` and `geany-plugins` installed, and I have downloaded most of the themes from geany's website.
![2020-08-03_12-06](https://user-images.githubusercontent.com/53279454/89153063-ccb2f880-d581-11ea-810a-28a644b04445.png)

**Comment by codebrainz** [comment] 2020-08-03 06:39
Duplicate of #1779, #2396

**Closed by codebrainz** 2020-08-03 06:39 UTC

**Comment by apoorv569** [comment] 2020-08-03 06:55
Thanks!
