### ISSUE TITLE
Language Server Protocol support

### ISSUE THREAD

**Issue by iahung** [geany/geany#3342] opened 2022-11-20 20:57 UTC
I know there are opening tickets for it, but there is no new information.

https://github.com/geany/geany/issues/2184 https://github.com/geany/geany-plugins/issues/1012

Geany is a good text editor but it's lagging behind others. As conservative as Emacs, now they have acknowledged the important of LSP support and supported LSP: https://emacs-lsp.github.io/lsp-mode/

LSP is not simply as ctags. People refer to ctags when discussing LSP support make me afraid. There are many language servers out there for various programming languages:

https://langserver.org/

https://microsoft.github.io/language-server-protocol/implementors/servers/

ctags is pretty primitive compared to real language servers like clangd. And please don't confused Jedi python code completion with a language server, Jedi is a library. A language server is much more powerful.

**Comment by iahung** [comment] 2022-11-20 21:04
Geany is a truly portable text editor. I used it own Windows, Linux, BSD and even Open Indiana. It could be compiled everywhere and run everywhere. This is what truly awesome about it. A comparison: TextAdept required Linux to compile and only cross compile to other platforms like these platforms are second class citizens, and now they are about to drop BSD support too.

https://github.com/orbitalquark/textadept/issues/295

https://github.com/orbitalquark/textadept/releases/tag/textadept_11.5_alpha_2

As bad as they are, they still have LSP support: https://github.com/orbitalquark/textadept-lsp

**Comment by elextr** [comment] 2022-11-20 23:07
Duplicate of #2184 

There is no point of opening new issues for the same thing.  We know what LSPs are, and what they do.  As the discussions on #3049 (off topic for the PR, but thats where they happened) indicate, there needs to be significant effort to transform Geany to use LSPs, even if only for symbols and autocomplete.  So much so that the expert on those commented that they would be unable to take the project on.

Geany is a completely volunteer project, there are no corporates sponsoring it, and nobody works on it full time, so if you want something ... do it!!  Don't just try to guilt trip others into it by comparing to other more active projects.

Make your own github clone, announce on a Geany discussion where the clone is and what you are gonna experiment with, so others can watch, and advise, or even help, and go for it (well, maybe do some planning first given the possible scope of changes ;-).

As far as plugins go, there are various ones mentioned in https://github.com/geany/geany-plugins/issues/1012 but AFAICT they havn't been touched for 6-7 years and are GTK2 only, so they may not work with GTK3 Geany.  Maybe "somebody" could update them.

**Closed by elextr** 2022-11-20 23:07 UTC
