### ISSUE TITLE
Have a new programming language specific capability/feature very similar to another

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany#3117] opened 2022-01-30 01:50 UTC
Please be patient guide me to have a new programming language (PL) specific capability/feature very similar to another previous existing one
The need arose for such in a PL has upgraded pretty drastic and needs to work as well as the orginal one, for the real case is:
 **Raku out of Perl 5**

Even if the `filetype_extensions.conf` was edited to be kind of
`Perl=*.pl;*.raku;*.rakumod;*.pm;` .....

its brace matching capability/feature would fail in e.g. a regex sub part variable
$foo = `qr{ .... }`
to be
$foo = `rx{ .... }`

which implies the merely edition is not the correct way to do setup
Please guide how to set up correctly in clear, complete, brief step-by-step instruction

**Comment by elextr** [comment] 2022-01-30 02:19
Duplicate of #3054

**Closed by elextr** 2022-01-30 02:19 UTC
