### ISSUE TITLE
Geany sometimes crashes when editing a Pascal source file

### ISSUE THREAD

**Issue by rchastain** [geany/geany#3127] opened 2022-02-15 10:14 UTC
Hello! I use Geany daily. It sometimes crashes when I edit a Pascal source file. I have just found a modification that makes Geany crash. I attach the file. Geany crashed when I added the comment (`{ ... }`).

I opened the document with another editor and added the comment. Then, if I try to open the document with Geany, it crashes.

I am on Linux. It's Geany 1.37.1.

[makegeanycrash.zip](https://github.com/geany/geany/files/8068076/makegeanycrash.zip)

Thanks for your attention.

**Comment by elextr** [comment] 2022-02-15 10:23
Duplicate of #2358 #2428 #2982 #2987 and fixed by #3043

**Closed by elextr** 2022-02-15 10:23 UTC

**Comment by rchastain** [comment] 2022-02-15 10:32
> Duplicate of #2358 #2428 #2982 #2987 and fixed by #3043

Oops! Sorry. Thank you for your answer.
