### ISSUE TITLE
underscores do not show in the editor

### ISSUE THREAD

**Issue by tux2bsd** [geany/geany#3383] opened 2023-02-02 23:19 UTC
underscores do not show in the editor, you can find them with ctrl+f (if you know they are there) but you can't see them

ii  geany          1.36-1build1 amd64        fast and lightweight IDE
PRETTY_NAME="Ubuntu 20.04.5 LTS"
(xfce xubuntu)

I use a relatively stock OS install, no custom fonts in the DE etc

**Comment by elextr** [comment] 2023-02-03 00:00
Duplicate of #2466 and half a billion others

**Closed by elextr** 2023-02-03 00:00 UTC
