### ISSUE TITLE
Window doesn't open maximized 

### ISSUE THREAD

**Issue by djuric** [geany/geany#671] opened 2015-09-27 17:00 UTC
When new file is opened (previous file which hasn't been opened before), it doesn't open maximized, window is not fully across the screen. This is clean installation of 2.24 version on Windows 7. You should also have previous files already opened in geany showing in tabs to replicate this problem
![geany](https://cloud.githubusercontent.com/assets/1643081/10124022/0eb000d2-654a-11e5-9ede-2cfbc83ed3ee.png)

**Comment by elextr** [comment] 2015-10-05 00:47
Can any Win 7 users reproduce?

**Comment by eht16** [comment] 2015-10-10 14:06
I cannot reproduce this with Windows 7 and the classic theme. There the Geany window is properly maximised. So I assume this is related to these modern Aero themes. But since I connect via RDP to the only Windows 7 system I have access to, I cannot verify my assumption because I'm unable to use Aero themes via RDP.

**Comment by eht16** [comment] 2015-10-10 14:39
@djuric when you say you are using 2.24 I guess you mean 1.24 as 2.24 doesn't exist. Could you try 1.25 which is the current release. In this release, the included GTK runtime environment was updated, maybe this solves the issue already.

**Comment by djuric** [comment] 2015-10-10 16:06
@eht16 yes sorry, version which I use is 1.25. I meant to type that instead of 2.24. And yes I just downloaded now again last version 1.25, same problem happens. I tried switching to classic theme but it makes no difference 

On first file opening eg. file.txt, it works fine (while Geany hasn't been started yet). However next file which you try to open while Geany is running and file which you haven't opened before (it's the best to create new something.txt file to test) than it opens non-maximized 

If this is what you tried and couldn't replicate the problem than I guess it's something on my end, I will try something else. Thank you very much

**Comment by eht16** [comment] 2015-10-11 11:28
Thanks for the extra info. I'm still unable to reproduce this.

Could you share your geany.conf? Maybe this will help.

Also, what exactly do you do when you say "next file which you try to open"? Do you open the next file within Geany using the File Open dialog, or from the command line via geany.exe or via the Explorer context menu item "Open with Geany" or something else?

**Comment by djuric** [comment] 2015-10-12 02:28
Thanks for your reply, here is my geany.conf http://pastebin.com/9izfd0hS 

I mean next file which I open using right click on file and than "Open with Geany". This seems to be the only way when issue above happens. I tried Geany's File Open dialog as you said and this works fine, windows is immediately maximized regardless if file was opened before or not

**Comment by eht16** [comment] 2015-10-13 20:21
Ok, I think we are getting closer. Though I still cannot reproduce the issue even with your config :(.

Since you said with Geany 1.24 it doesn't happen, I assume it might be related to the embedded GTK runtime which was updated from 2.16 to 2.24 with Geany 1.25 while in Geany no changes were made to the relevant code.
A quick search in the GTK bug tracker revealed two maybe related reports:

https://bugzilla.gnome.org/show_bug.cgi?id=620267

https://bugzilla.gnome.org/show_bug.cgi?id=675846

620267 sounds very related. Is there any change you maximized the Geany window using the "snap" feature? If so, according to the information provided in the bug report, can you also reproduce the behaviour if you maximize the window using the normal method?

**Comment by djuric** [comment] 2015-10-18 15:26
I tried snap feature but it doesn't make much difference. But yes i think it's GTK related, I will try to reinstall version of GTK if that's possible. I understand that it's not problem on your end, I really appreciate your assistance :)

**Comment by eht16** [comment] 2016-11-13 13:11
You could maybe try a newer version of Geany which includes a more recent GTK version.
Until then, I'll close this issue.
Just re-open if there are any news.

**Closed by eht16** 2016-11-13 13:11 UTC
Labels: waiting for information, windows
