### ISSUE TITLE
Add "Lint" and custom second "Execute" to shortcut list

### ISSUE THREAD

**Issue by sven-frotscher** [geany/geany#2832] opened 2021-06-22 22:44 UTC
I would like to trigger the "Lint" command or the custom second "Execute" command with a keyboard shortcut.
If you want to introduce this with minimal disruption, just create the option to configure shortcuts for these in the preferences, but leave them unset by default.

To be fair, an Alt combination, together with careful placement of underscores in the "Set Build Commands" window, allows one to trigger them with just 3 keystrokes each (see also #1520). Still, needing only one would be nicer :)

**Comment by elextr** [comment] 2021-06-22 23:09
The limitation on build menu keyboard shortcuts is a known and documented limitation [see](https://www.geany.org/manual/current/index.html#build-menu-keyboard-shortcuts).  

The keybinding preferences dialog does not know how to handle variable numbers of menu items, because nobody has taught it.  So it only knows the old fixed menu items that are always present.  Contributions to its training are welcome.

Closed as duplicate of #705 #1614 and probably others.

**Closed by elextr** 2021-06-22 23:09 UTC
