### ISSUE TITLE
Find dialog goes crazy after changing Mac Dock System Preferences Setting

### ISSUE THREAD

**Issue by sstiefel19** [geany/geany#2410] opened 2019-12-13 10:11 UTC
Hi,
I have the problem that if I change a Mac System Preference setting I cant use the Geany find dialog anymore. Steps to reproduce:
0. Open Geany and edit a .cpp file
1. Open Mac System Preferences
2. Click 'Dock'
3. Change 'Prefer tabs when opening documents' to 'Always'
4. go back to geany. Invoke the Find dialog by Search->Find or CMD F 

The search dialog will go full screen and look weird. (See screenshot)
best,
Stephan

I have
Mac Mojave 10.14.6
Geany 1.36 (downloaded binaries for mac)
(built on or after 2019-09-29)
Using GTK+ v2.24.32 and GLib v2.60.6 runtime libraries

<img width="1920" alt="Screenshot 2019-12-13 at 11 06 59" src="https://user-images.githubusercontent.com/55794986/70792091-c70d6600-1d98-11ea-9248-a2cd7473c275.png">

**Comment by techee** [comment] 2020-03-22 13:14
There is a new release for macOS which is based on GTK 3 and which should fix this problem - at least I can't reproduce it now. I'm closing this issue but feel free to re-open it if you think it's not fixed completely.

**Closed by techee** 2020-03-22 13:14 UTC
Labels: macos
