### ISSUE TITLE
When opening Plugin Manager, GTK warning and critical messages appear in console

### ISSUE THREAD

**Issue by andy5995** [geany/geany#2065] opened 2019-01-25 00:43 UTC
When I select "tools -> plugin Manager", this appears in the terminal where I opened geany from

```
(geany:3375): Gtk-WARNING **: 15:38:55.556: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(geany:3375): Gtk-WARNING **: 15:38:55.556: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node entry, owner GtkEntry)

(geany:3375): Gtk-WARNING **: 15:38:55.556: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(geany:3375): Gtk-WARNING **: 15:38:55.556: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(geany:3375): Gtk-CRITICAL **: 15:38:55.556: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(geany:3375): Gtk-CRITICAL **: 15:38:55.556: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(geany:3375): Gtk-WARNING **: 15:38:55.556: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(geany:3375): Gtk-CRITICAL **: 15:38:55.556: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```

Here's my debug info:

```
15:41:01: Geany INFO : Using alternate configuration directory
15:41:01: Geany INFO : Geany 1.35 (git >= bf5c9edd), en_US.utf8
15:41:01: Geany INFO : GTK 3.24.3, GLib 2.58.2
15:41:01: Geany INFO : System data dir: /home/andy/test-geany/share/geany
15:41:01: Geany INFO : User config dir: /home/andy/test-geany/config
15:41:02: Geany INFO : Loaded GTK+ CSS theme '/home/andy/test-geany/share/geany/geany.css'
15:41:02: Geany INFO : Loaded GTK+ CSS theme '/home/andy/test-geany/share/geany/geany-3.20.css'
15:41:02: Geany INFO : System plugin path: /home/andy/test-geany/lib/geany
15:41:02: Geany INFO : Added filetype Clojure (61).
15:41:02: Geany INFO : Added filetype Graphviz (62).
15:41:02: Geany INFO : Added filetype CUDA (63).
15:41:02: Geany INFO : Added filetype JSON (64).
15:41:02: Geany INFO : Added filetype Arduino (65).
15:41:02: Geany INFO : Added filetype Scala (66).
15:41:02: Geany INFO : Added filetype Genie (67).
15:41:02: Geany INFO : Added filetype Cython (68).
15:41:02: Geany INFO : Loaded libvte from libvte-2.91.so
15:41:02: Geany INFO : unknown : None (UTF-8)
15:42:20: Geany INFO : Added 7 plugin(s) in '/home/andy/test-geany/lib/geany'.
15:42:20: Gtk CRITICAL : gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed
```

**Comment by codebrainz** [comment] 2019-01-25 01:32
Try with a different theme/theme-engine.

**Comment by elextr** [comment] 2019-01-25 01:46
Yeah, try dead tortoise, its the reference theme

(Adwaita, see [here](https://en.wikipedia.org/wiki/Adwaita))

**Comment by elextr** [comment] 2019-04-01 01:09
Same messages occur with:

10:05:30: Geany INFO		: Geany 1.35 (git >= c4f5878d), en_AU.UTF-8
10:05:30: Geany INFO		: GTK 3.22.30, GLib 2.56.3

on Mint 19 with Cinnamon @andy5995 what desktop were you using?

**Comment by andy5995** [comment] 2019-04-01 03:49
@elextr XFCE on Debian buster

**Comment by elextr** [comment] 2019-04-01 04:10
Ok, so not dependent on theme/engine then.

**Comment by codebrainz** [comment] 2019-04-01 14:11
Did you both try with Adwaita and various other themes?

**Comment by elextr** [comment] 2019-04-01 23:06
Tortoise still fails.  And since Mint themes are their own and @andy5995 is using XFCE themes then we have tried a selection.  Anyway its unlikely that themes will make those type of sizing errors, its probable that Geany is doing something not compatible new sizing code in GTK 3.22+.  @b4n or other GTK expert should have a look.

**Comment by codebrainz** [comment] 2019-04-01 23:57
> Mint themes are their own

The default Mint theme looks like a fork of Greybird a popular theme designed by some Xfce designers (default Xubuntu theme), which is why I asked again. GTK+ themes are cross-desktop, and since there are so few good ones out there after the giant GTK+3 breakages, it's not uncommon for two different DE users to have the same theme.

> its unlikely that themes will make those type of sizing errors

I've gotten all kinds of similar weird errors when using a GTK+ theme which hadn't been updated after GTK+ theme breaks in recent years.

----

I think the VTE has been known to cause such errors before, you could try disabling it. You could also try running Geany with `--g-fatal-warnings` in GDB to maybe see where the warning is coming from.

**Comment by elextr** [comment] 2019-04-02 00:00
Its not VTE, its the plugin manager dialog, and to be clear Mint specifically upgrades its themes to work, unlike other distros.  And I'm not using the default Mint theme anyway.

**Comment by andy5995** [comment] 2019-04-06 05:44
I couldn't find the dead tortoise theme. Provide a link for that?

> Did you both try with Adwaita and various other themes?

Yeah, but it's a little hard for me to make sure I did things right. I've never developed with GTK before, and never tried using a theme switcher or installed a new theme before you guys mentioned it above (Jan 24).

I  tried two different programs for switching themes: gtk-theme-switch2 and gnome-tweak-tool.

gnome-tweak-tool shows I'm currently using the Adwaita theme, but gtk-theme-switch2 tells me I'm using Lightning bug, and that's the correct one.

I installed lightning bug manually after downloading it from some theme site (don't remember where).

But now looking at the Geany debug info, it looks like it may be using a separate theme, not the system themes I mentioned? Should I be copying the theme files into those directories shown in the Debug info?

**Comment by elextr** [comment] 2019-04-06 05:53
@andy5995 [Adwaita](https://en.wikipedia.org/wiki/Adwaita) is a dead tortoise.  For the life of me I don't know why GTK chose that name, except to allow me to confuse people with bad jokes, sorry. :grin:

The problem seems to happen on a number of different themes, so I don't see that its likely to be theme related, but what it is I don't know, calling GTK experts.

**Comment by elextr** [comment] 2021-06-03 00:42
Ping, now Geany is GTK3 only:

```
09:27:44: Geany INFO		: Geany 1.38 (git >= b524a58e), en_AU.UTF-8
09:27:44: Geany INFO		: GTK 3.24.20, GLib 2.64.6
09:27:44: Geany INFO		: OS: Linux Mint 20 (ulyana)
```

 this should be fixed, somebody who understands GTK should take a look.

**Comment by andy5995** [comment] 2021-06-03 02:34
I think it's the same

```
$ geany

(geany:11284): Gtk-WARNING **: 21:29:32.584: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(geany:11284): Gtk-WARNING **: 21:29:32.584: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node entry, owner GtkEntry)

(geany:11284): Gtk-WARNING **: 21:29:32.584: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(geany:11284): Gtk-WARNING **: 21:29:32.584: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(geany:11284): Gtk-CRITICAL **: 21:29:32.584: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(geany:11284): Gtk-CRITICAL **: 21:29:32.584: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(geany:11284): Gtk-WARNING **: 21:29:32.584: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(geany:11284): Gtk-CRITICAL **: 21:29:32.584: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```

```
21:30:02: Geany INFO		: Geany 1.38 (git >= b524a58e), en_US.UTF-8
21:30:02: Geany INFO		: GTK 3.24.5, GLib 2.58.3
21:30:02: Geany INFO		: OS: Linux
21:30:02: Geany INFO		: System data dir: /home/andy/.local/share/geany
21:30:02: Geany INFO		: User config dir: /home/andy/.config/geany
21:30:02: Geany INFO		: Loaded GTK+ CSS theme '/home/andy/.local/share/geany/geany.css'
21:30:02: Geany INFO		: Loaded GTK+ CSS theme '/home/andy/.local/share/geany/geany-3.20.css'
21:30:02: Geany INFO		: System plugin path: /home/andy/.local/lib/geany
21:30:02: Geany INFO		: Added filetype Clojure (63).
21:30:02: Geany INFO		: Added filetype Nim (64).
21:30:02: Geany INFO		: Added filetype Graphviz (65).
21:30:02: Geany INFO		: Added filetype Groovy (66).
21:30:02: Geany INFO		: Added filetype CUDA (67).
21:30:02: Geany INFO		: Added filetype JSON (68).
21:30:02: Geany INFO		: Added filetype Arduino (69).
21:30:02: Geany INFO		: Added filetype Kotlin (70).
21:30:02: Geany INFO		: Added filetype Scala (71).
21:30:02: Geany INFO		: Added filetype Genie (72).
21:30:02: Geany INFO		: Added filetype Swift (73).
21:30:02: Geany INFO		: Added filetype Cython (74).
21:30:02: Geany INFO		: Added filetype TypeScript (75).
21:30:02: Geany INFO		: Loaded libvte from libvte-2.91.so
21:30:02: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/codenav.so (Code navigation)
21:30:02: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/debugger.so (Debugger)
21:30:02: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/filebrowser.so (File Browser)
21:30:02: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/geanyvc.so (GeanyVC)
21:30:02: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/projectorganizer.so (Project Organizer)
21:30:02: SpellCheck DEBUG	: Initializing Enchant library version 1.6 or older
21:30:02: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/spellcheck.so (Spell Check)
21:30:02: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/splitwindow.so (Split Window)
21:30:02: Geany INFO		: unknown : None (UTF-8)
21:30:04: Geany INFO		: Plugin "/home/andy/.local/lib/geany/codenav.so" already loaded.
21:30:04: Geany INFO		: Plugin "/home/andy/.local/lib/geany/debugger.so" already loaded.
21:30:04: Geany INFO		: Plugin "/home/andy/.local/lib/geany/filebrowser.so" already loaded.
21:30:04: Geany INFO		: Plugin "/home/andy/.local/lib/geany/geanyvc.so" already loaded.
21:30:04: Geany INFO		: Plugin "/home/andy/.local/lib/geany/projectorganizer.so" already loaded.
21:30:04: Geany INFO		: Plugin "/home/andy/.local/lib/geany/spellcheck.so" already loaded.
21:30:04: Geany INFO		: Plugin "/home/andy/.local/lib/geany/splitwindow.so" already loaded.
21:30:04: Geany INFO		: Added 40 plugin(s) in '/home/andy/.local/lib/geany'.
21:30:04: Gtk CRITICAL	: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed
21:30:04: GdkPixbuf DEBUG	: gdk_pixbuf_from_pixdata() called on:
21:30:04: GdkPixbuf DEBUG	: 	Encoding raw
21:30:04: GdkPixbuf DEBUG	: 	Dimensions: 14 x 14
21:30:04: GdkPixbuf DEBUG	: 	Rowstride: 56, Length: 808
21:30:04: GdkPixbuf DEBUG	: 	Copy pixels == false
21:30:05: GdkPixbuf DEBUG	: gdk_pixbuf_from_pixdata() called on:
21:30:05: GdkPixbuf DEBUG	: 	Encoding raw
21:30:05: GdkPixbuf DEBUG	: 	Dimensions: 14 x 14
21:30:05: GdkPixbuf DEBUG	: 	Rowstride: 56, Length: 808
21:30:05: GdkPixbuf DEBUG	: 	Copy pixels == false
21:30:05: GdkPixbuf DEBUG	: gdk_pixbuf_from_pixdata() called on:
21:30:05: GdkPixbuf DEBUG	: 	Encoding raw
21:30:05: GdkPixbuf DEBUG	: 	Dimensions: 14 x 14
21:30:05: GdkPixbuf DEBUG	: 	Rowstride: 56, Length: 808
21:30:05: GdkPixbuf DEBUG	: 	Copy pixels == false
```

**Comment by elextr** [comment] 2021-06-03 03:13
@andy5995 yep, get the same messages on terminal as you, but I don't get all the debug messages, just one
```
10:40:13: Gtk CRITICAL	: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed
```

**Comment by AntumDeluge** [comment] 2023-02-08 02:15
This is likely an internal Gtk issue, not Geany. I believe it is often the fault of the window manager as many different Gtk applications cause the same output.

**Comment by andy5995** [comment] 2023-02-08 09:20
Sounds about right, thanks @AntumDeluge . Probably different themes are also a factor?

**Comment by elextr** [comment] 2023-02-08 11:26
> This is likely an internal Gtk issue, not Geany. I believe it is often the fault of the window manager as many different Gtk applications cause the same output.

Agree its a GTK issue, but probably not the window manager, thats not part of GTK.  Its more likely its to do with changes in the way GTK calculates its initial sizes getting silly numbers before the whole dialog is constructed and initialised.  I know it changed late in the GTK3 cycle, but I'm not expert enough to know what changed.

It does no harm except being ugly, so perhaps the pragmatic approach is to leave it alone and if Geany ever goes to GTK4 it can be addressed along with lots of other stuff.

**Comment by AntumDeluge** [comment] 2023-02-16 19:44
> Probably different themes are also a factor?

Maybe, I don't know for sure. I never messed around with themes to see if it made any difference.

I'm using Lubuntu (LXQT) right now. The Gtk 2/3 theme is set to `Arc-Dark`. But I've gotten those Gtk error/warning messages on almost every system I've used for multiple different apps, including systems using window managers built with Gtk.

![image](https://user-images.githubusercontent.com/3631473/219470189-8c951931-9648-4cd0-a863-130b088920c1.png)

**Comment by techee** [comment] 2024-11-26 17:26
This is actually caused by `geany_wrap_label_new()` here:

https://github.com/geany/geany/blob/32ef42eb9e41029e89e52a9cee78afd06706aa7a/src/plugins.c#L1925

When replaced with `gtk_label_new()`, the error messages are gone. Not sure why this happens, it's possibly some interaction of the resizable label and resizable list below.

I'm not sure if the wrapping label is actually necessary here - the English text at least isn't too long. And it could be made shorter if needed for some translations:
```
Choose which plugins to load:
```
I think the "at startup" is kind of implicit (and possibly misleading) because the plugin is loaded immediately and the fact that it's loaded at startup is caused by the fact that the settings is saved here - no need to emphasize that IMO.

**Closed** 2024-12-09 11:29 UTC
Labels: gtk
