### ISSUE TITLE
Scroll wheel on tab bar to cycle through tabs (feature request)

### ISSUE THREAD

**Issue by mythril** [geany/geany#1848] opened 2018-04-30 17:21 UTC
Hi, in older versions of geany you used to be able to use the scroll wheel while hovering the tab bar to cycle through tabs, it seems the recent update to 1.33 vanished that feature into the void.

It was a nice feature, just making a note in case you guys want to implement/re-enable it.

**Comment by elextr** [comment] 2018-04-30 23:04
You are probably using a GTK3 version of Geany.  GTK removed that feature.

**Comment by codebrainz** [comment] 2018-05-01 00:49
Duplicate of #1778 and #1815.

**Closed by codebrainz** 2018-05-01 00:49 UTC
Labels: gtk, invalid

**Comment by War3Evo** [comment] 2022-01-02 00:02
Yeah.. when I went from Debian 8 to Debian 11.. that feature is missed... mouse wheel to scroll through tabs.

**Comment by elextr** [comment] 2022-01-02 00:04
@War3Evo Debian went to GTK3, so see [comment](https://github.com/geany/geany/issues/1848#issuecomment-385554385) above.
