### ISSUE TITLE
Issue with the terminal of the mac

### ISSUE THREAD

**Issue by Oscarsito49** [geany/geany#3369] opened 2023-01-16 14:23 UTC
Spanish: He intentado solucionar de mil maneras y no llego a ninguna solucion. La aplicacion funciona a la perfeccion pero cuando voy a ejecutar el programa me sale este error de permisos del terminal para ejecutar documentos. El termina y Geany tienen permiso a acceder al disco duro entero pero aun asi no funciona. He contactado con apple y ni ellos mismos saben solucionarme el problema.
Si alguien sabe como solucionarlo se lo agradezco eternamente, necesito una solucion rapida ya que lo necesito para clase y con este error no puedo avanzar.

English: I have tried to solve it in a thousand ways and I have not come to any solution. The application works perfectly but when I go to run the program I get this terminal permissions error to run documents. He terminates and Geany is allowed to access the entire hard drive but it still doesn't work. I have contacted apple and they themselves do not know how to solve the problem.
If someone knows how to solve it, I am eternally grateful, I need a quick solution since I need it for class and with this error I cannot move forward.
<img width="845" alt="Captura de pantalla 2023-01-16 a las 15 18 38" src="https://user-images.githubusercontent.com/122802900/212700300-3e1daecb-9da4-4588-9632-ddf31e099ef4.png">
<img width="316" alt="Captura de pantalla 2023-01-16 a las 15 18 14" src="https://user-images.githubusercontent.com/122802900/212700310-57188862-a3a4-4b39-9787-916e3119fd02.png">

**Comment by Marcos150** [comment] 2023-01-16 17:00
Spanish: A mi me ocurre el mismo error, pero he logrado encontrar una especie de solución. Si vas a la pestaña de "Editar -> Preferencias -> Terminal" y marcas la opción de "Ejecutar programas en la VTE" tu código se debería ejecutar en el terminal integrado de Geany sin ningún problema.

English: I have the same issue, but I was able to find a workaround. If you go to "Edit -> Preferences -> Terminal" and you check the box that says "Execute programs on the VTE" your code should execute on geany's integrated terminal without any problem.
<img width="805" alt="screenshot" src="https://user-images.githubusercontent.com/117666109/212730296-1aa4cd6f-6453-44e6-b33d-6e340a34e1d7.png">

**Comment by Marcos150** [comment] 2023-01-16 18:12
> Por cierto @Marcos150 te sabes el comando o la manera para borrar el contenido del terminal? En plan para que se quede en blanco

Puedes usar el comando "clear" para borrar el contenido del terminal o hacer click derecho y seleccionar la opción "Reiniciar terminal" para reiniciarlo completamente.

You can use the command "clear" to clear the terminal content or right click and select the option "Reset terminal" to reset it completely.

**Comment by techee** [comment] 2023-01-18 14:34
Interesting, I can't reproduce the issue here (when running a python script). I'm still on macOS 12.6.2 and haven't updated to 13 yet - what's your version? It's possible there's some new permission to allow/disallow applications to execute scripts in the terminal (for security reasons). Isn't there some option under "System Preferences"->"Security & Privacy" under the Privacy tab where you could allow Geany to execute scripts in terminal? (There's nothing like that on macOS 12.)

**Comment by techee** [comment] 2023-01-18 16:53
Would you try adding also
```
/usr/bin/open
```
and
```
/bin/zsh
```
to the list of applications having full disk access?

What happens is that Geany runs the command specified in Preferences->Tools->Terminal which by default is
```
open -a terminal %c
```
and where `%c` is substituted for the temporary shell script Geany creates called `geany _run_ script_ XXXXXX.sh`. The script is interpreted by the shell, i.e. `zsh` (unless you use `bash` or something else) inside the Terminal app. I suspect the error message might mean that either the `open` command or the `zsh` command don't have full disk access (and not Geany or Terminal).

> I went even to an apple store and they couldnt find the issue.

I'd be really surprised if those guys knew something ;-).

**Comment by techee** [comment] 2023-01-25 15:49
Alright, I upgraded to macOS 13 so I'm able to reproduce the issue. I've rebuilt Geany with the latest GTK version and Geany version from git master which can be downloaded here:

https://download.geany.org/snapshots/geany-1.38_osx_arm64.dmg

(The latest GTK seems to improve rendering performance so scrolling seems to be much faster plus there are some minor goodies in Geany so I recommend trying this version.)

First I thought this fixed the problem because when installed, launching the script worked. But once I uploaded the installer to the Geany site and then installed the downloaded version of the installer, it stopped working again. I think this is some sort of security protection to avoid executing some random scripts from the Internet using the built-in terminal.

Then I found this article

https://stackoverflow.com/questions/74187734/launchpackager-command-can-t-be-opened

with a workaround - one has to use a different terminal application for execution. When you use e.g. iTerm and in Geany under `Edit->Settings->Tools` set `open -a iTerm %c` as the terminal command, iTerm launches without any problems and performs the execute command.

**Comment by Oscarsito49** [comment] 2023-01-26 10:15
Thank you. <3

**Comment by techee** [comment] 2023-01-26 22:38
Just for completeness, I also created a `x86_64` binary with the latest Geany master and GTK here:

https://download.geany.org/snapshots/geany-1.38_osx.dmg

**Comment by techee** [comment] 2023-10-19 20:50
Seems to be fixed in macOS 14.

**Closed** 2024-06-18 17:53 UTC
Labels: macos
