### ISSUE TITLE
macOS: drag& drop of text always copies text

### ISSUE THREAD

**Issue by silberzwiebel** [geany/geany#1701] opened 2017-12-01 12:12 UTC
geany version 1.32, OS version macOS Sierra, 1.12.6.

Different from geany's behavior under Fedora, where selecting text and drag-&dropping it to another part in the document, moves the text (like Ctrl+X, Ctrl+V), under macOS, the text is always _copied_ (like Ctrl+C, Ctrl+V). Pressing any of the many modifier keys mac keyboards have to offer (Ctrl, Cmd, Alt) during the drag-&dropping doesn't change this behavior (despite [this entry in the manual](https://www.geany.org/manual/current/index.html#drag-and-drop-of-text)).

**Comment by techee** [comment] 2018-01-30 22:41
Yes, this seems to be a bug of the Mac version of GTK. This particular bug is also tracked here:

https://github.com/geany/geany-osx/issues/4

**Comment by techee** [comment] 2021-11-17 20:02
Closing as this is a duplicate of

geany/geany-osx#4

**Closed by techee** 2021-11-17 20:02 UTC
Labels: macos
