### ISSUE TITLE
Geany will crash when opening a PHP/HTML file this http-equiv meta tag

### ISSUE THREAD

**Issue by DGivney** [geany/geany#339] opened 2014-09-29 02:35 UTC
In Ubuntu 14.04 64bit Geany 1.25 (git >= f3cb246) will crash when opening a PHP/HTML file with the following http-equiv meta tag:

```
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
```

To replicate, save the above content in a file and open it in geany.

Error displayed after crash:
> 74
*** Error in `geany': malloc(): smallbin double linked list corrupted: 0x0000000002586d10 ***

**Comment by eht16** [comment] 2016-03-05 13:10
@DGivney does this still happen? I cannot reproduce with current GIT master.

**Comment by b4n** [comment] 2016-03-06 16:00
Me neither, let's close this at least for now.

**Closed by b4n** 2016-03-06 16:00 UTC
Labels: can't reproduce, waiting for information
