### ISSUE TITLE
Support VTE 2.91

### ISSUE THREAD

**Issue by kalikiana** [geany/geany#685] opened 2015-10-10 11:59 UTC
The new filename for VTE 2.91 on linux is libvte-2.91.so.0 and vte_terminal_fork_command needs to be replaced with vte_terminal_spawn_sync because the former was deprecated for some time and has been removed.

**Comment by b4n** [comment] 2015-10-10 12:01
Duplicate of #336

**Closed by b4n** 2015-10-10 12:01 UTC
