### ISSUE TITLE
Cursor does not work properly

### ISSUE THREAD

**Issue by zrdai** [geany/geany#1371] opened 2017-01-18 12:13 UTC
I am using Geany within Mac, OS Sierra, 10.12.2. The cursor cannot grap the buttons because it should always be higher than the position of the button. This is really annoying. Can I get help? I have already tried to reinstall Geany 1.29. It did not help. Could be an incompatability with Sierra. 
Thank you.

**Comment by phillc54** [comment] 2017-05-23 08:10
I have the same problem plus to select text the cursor needs to be two lines above the required text.
macOS Sierra 10.12.4
Geany 1.30.1
I have tried earlier Geany versions back to 1.25 but they all behave the same.

**Comment by lukaspirpamer** [comment] 2018-08-27 20:14
I have the same problem, I have just downloaded the newest version for mac (1.33)
I'm using macOS Sierra 10.12.6
Does anybody have a workaround?
Thanks!!

**Comment by elextr** [comment] 2018-08-27 20:45
@techee ping

**Comment by phillc54** [comment] 2018-08-27 22:57
I have Geany 1.33 on two iMacs,
It works fine on the iMac16,2 which reports as iMac (Retina 4K, 21.5-inch, Late 2015)
It shows the same faulty behaviour on the iMac14,1 which reports as iMac (21.5-inch, Late 2013)
Both iMacs have macOS High Sierra 10.13.6

**Comment by phillc54** [comment] 2018-08-28 00:16
I can confirm it behaves the same here on the iMac14,1.
Manually resizing the window while editing also fixes the cursor problem.

**Comment by phillc54** [comment] 2018-08-28 00:16
I can confirm it behaves the same here on the iMac14,1.
Manually resizing the window while editing also fixes the cursor problem.

**Comment by phillc54** [comment] 2018-08-28 00:17
I can confirm it behaves the same here on the iMac14,1.
Manually resizing the window while editing also fixes the cursor problem.

**Comment by elextr** [comment] 2018-08-28 00:29
@lukaspirpamer I presume you mean "is to LARGE for the display"?

With very little knowledge and less forethought, this looks like a bug in the GTK/OSX backend when windows don't fit the screen.

**Comment by phillc54** [comment] 2018-08-28 00:48
The window is not too big for the screen.
The cursor problem can be 'fixed' by resizing the window or moving the window.
This needs to be done for each popup window as well e.g. Open, Save etc.
Moving/Resizing by just one pixel is enough...
![screen shot 2018-08-28 at 10 42 48 am](https://user-images.githubusercontent.com/2746571/44694222-a50ea800-aaaf-11e8-83c1-9e362294145a.png)

**Comment by elextr** [comment] 2018-08-28 00:53
Ok, so GTK and OSX have differing ideas where the window is after popup so they disagree about if the cursor is over a button, but resync after a move/resize.

Somebody should report to the GTK/OSX backend.

**Comment by techee** [comment] 2018-08-29 13:30
To me this looks like a duplicate of #1729 - the problems are caused by the extra tab at the top which shouldn't be there. To summarise what you could try to fix the problem:

1. In macOS Settings set the value of "Dock->Prefer tabs when opening documents" to Manually.
2. In Geany menu bar try selecting "View->Hide tab bar"
3. As suggested in #1729 you might want to remove a GTK installation from homebrew or some other package manager which might conflict with Geany.

I'm closing this issue as I think it's a duplicate of #1729 and the discussion can continue there. Feel free to reopen this bug report if you think it's not the case.

**Closed by techee** 2018-08-29 13:30 UTC
Labels: macos
