### ISSUE TITLE
1.26 Mac bundle can not input chinese

### ISSUE THREAD

**Issue by yuhaixy** [geany/geany#920] opened 2016-02-28 02:39 UTC
On Mac OS X , i can't use input chinese with Squirrel. When i input chinese in the editor, the editor still display english chars.

**Comment by elextr** [comment] 2016-02-28 02:51
I think that the editor component we use (Scintilla, its a separate project at www.scintilla.org) only supports its own input methods, you should try Scite (which is a reference Scintilla using editor), and if that doesn't work raise it on the Scintilla project.

**Comment by techee** [comment] 2016-02-29 14:04
@yuhack Would you please try if the 1.25 release

http://download.geany.org/geany-1.25_osx.dmg

works for you? I had to remove some glib input method libraries in 1.26 because it somehow mysteriously started causing crashes in 1.26. It would be good to know if this is the reason or if there's some other issue (e.g. as what @elextr suggests).

**Comment by xhacker** [comment] 2016-03-06 20:35
I can also reproduce the issue with 1.26.

@techee: Just tried 1.25 and it works, with an issue where the candidates window is not under the cursor. Please see attached screenshot.

<img width="538" alt="screen shot 2016-03-06 at 12 33 31 pm" src="https://cloud.githubusercontent.com/assets/1051813/13556814/ce493096-e397-11e5-808e-093e60a43091.png">

**Comment by techee** [comment] 2016-03-13 17:07
@yuhack I added some more input method libraries into the just released 1.27 bundle - should work at least similarly to the 1.25 release. I'm afraid that's all I can do in Geany - the rest is Gtk which is in a slightly strange state on OS X. I might use Gtk 3 in the future once it gets more usable on osx which might fix some issues.

**Comment by techee** [comment] 2021-11-14 17:17
I believe input methods work correctly in the latest release, closing. Feel free to reopen if there are still some problems.

**Closed by techee** 2021-11-14 17:17 UTC
Labels: macos
