### ISSUE TITLE
GTK native printing produces empty pages

### ISSUE THREAD

**Issue by uffejakobsen** [geany/geany#2177] opened 2019-06-07 13:33 UTC
GTK native printing produces empty pages

When filetype is set to none printed pages are all blank - except for the linenumbers and header text.

When filetype (TCL) is set - code is printed using dimmed greyscale - totally unreadable.

Geany 1.35 on Archlinux - printing on black/white HP M3035 MFP LasterJet

**Comment by elextr** [comment] 2019-06-07 13:43
I don't suppose you are using a dark colour scheme, where lettering is white?  The printing uses the colour scheme colours for letters, but forces the background to white so it doesn't empty black ink/toner cartridges printing the background.  So its printed your text as white on a white background.

**Comment by uffejakobsen** [comment] 2019-06-07 13:57
Argh !!!! I was using the Dark color scheme - changing to Standard color scheme made printing possible - thanks.

Only problem that Stnadard color scheme is not that good for coding - is there a tweak that will enable printing from the Dark color scheme ?

**Comment by codebrainz** [comment] 2019-06-08 00:38
Related to and/or duplicate of at least: #2023, #1791, #1551, #894, #617, [308](https://sourceforge.net/p/geany/bugs/308/), [1019](https://sourceforge.net/p/geany/bugs/1019/).

IMO, this is definitely a silly and unexpected thing for Geany to do. By default it should print what is shown, and then offer a way to disable or invert syntax highlighting for printing.

Anyway, if anyone wants to work on this, feel free to pickup on #894 or create a newer better pull request.

**Closed by codebrainz** 2019-06-08 00:38 UTC
