### ISSUE TITLE
Japanese(and other) characters show up as boxes in Geany on Windows 10

### ISSUE THREAD

**Issue by Asmageddon** [geany/geany#1805] opened 2018-03-14 12:53 UTC
Example text copied from wikipedia:

![wikipedia for text editor](https://i.imgur.com/6xKwIWk.png)

How it shows up in Notepad++

![notepad plus plus screenshot](https://i.imgur.com/fEG9seF.png)

And lastly, how it looks in Geany:

![how it looks in Geany](https://i.imgur.com/LebCutn.png)

-----

Arabian, Korean, Chinese characters do not seem to work either, Russian do.

**Comment by codebrainz** [comment] 2018-03-14 14:09
What if you use the same font in Geany as you're using in Notepad++?

**Comment by Asmageddon** [comment] 2018-03-16 19:22
The problem persists regardless of the font.

**Comment by elextr** [comment] 2018-03-16 20:21
has it loaded as the correct encoding?

**Comment by Asmageddon** [comment] 2018-03-17 10:48
This happens regardless of which encoding I tell Geany to open/display a file as.

**Comment by elextr** [comment] 2018-03-17 11:02
Arabian, chinese, japanese, korean all display for me.  Please gist your original text instead of images.

**Comment by Asmageddon** [comment] 2018-03-20 23:15
It's the synopsis of [this](https://ja.wikipedia.org/wiki/%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF) wikipedia article,

> テキストエディタ（英語: text editor）とはコンピュータで文字情報（テキスト）のみのファイル、すなわちテキストファイルを作成、編集、保存するためのソフトウェア（プログラム）である。一般的に、文字情報の入力、削除、コピー、貼り付け、検索、置換、整形などの機能を備えている。Windowsのメモ帳や、macOSのテキストエディット、UNIXのvi、Emacsなど、多くのオペレーティングシステム (OS) やデスクトップ環境に最初から装備されている。

**Comment by elextr** [comment] 2018-03-20 23:49
Copied the wikipedia article and pasted it fine here on Linux but I can't test windows.  However as other people have used asian languages on Windows I suspect its something to do with your setup.

Lets see if any other contributors on Windows can reproduce.

**Comment by Asmageddon** [comment] 2018-03-21 12:47
Hmm :-/ It does indeed sound like it's on my end, but I've not (re)configured anything language/font related on Windows.

**Comment by idnsunset** [comment] 2019-11-04 15:51
Same issue on Windows 7, not only for Japanese but all the characters not included in the font you choose are displaying in boxes. There are some exceptions: any fonts that have been defined a key (key value can be even left blank) with in  `HKEY_LOCAL_MACHINE/Software/Microsoft/Windows NT/Current Version/FontLink/SystemLink`,  CJK characters could display although the fallback CJK fonts are not what I specified (the value I assigned to the key).  Maybe you could try to create a fontlink key in registry to at least let the characters show up first.

**Comment by AntumDeluge** [comment] 2022-08-19 21:32
This appears to be fixed. I am on Windows 10 using Geany 1.38 & the Japanese characters posted by @Asmageddon display correctly.

![Geany displaying Japanese characters](https://user-images.githubusercontent.com/3631473/185710057-9f1e21d7-21c6-49eb-bfd4-29e6870eb04c.png)

**Comment by elextr** [comment] 2022-08-19 22:13
@AntumDeluge thanks, it may depend on what language packs (ie fonts) are installed on your system, or a newer GTK version may find fonts better.

**Comment by mbabuskov** [comment] 2024-02-17 07:05
I have the same problem with that same Geany version (1.38) when trying to display the tricolon character ⁝

Also the same problem with some other General Punctuation characters like U+2025 TWO DOT LEADER (‥) etc.

The problem shows up only on Windows 10. It works fine on Linux and macOS.

I tried different fonts and it makes no difference.

**Comment by eht16** [comment] 2024-02-17 10:35
I have tested this on Windows 7 with Geany 2.0 and most fonts show the described problem.

By just trying to switch the font, I found a few which do work:
- Batang
- BatangChe
- DFKai-SB
- Dotum
There are probably more fonts which work, I gave up trying at that point.

This might be caused by a combination of Geany, GTK, Scintilla and Windows. I won't debug or fix this further due to my limited knowledge of all these components and in lack of the huge amount of time necessary.

**Closed by eht16** 2024-02-17 10:35 UTC
Labels: windows, can't reproduce

**Comment by Asmageddon** [comment] 2024-02-18 08:08
@eht16 Perhaps at least, you could switch the default font to one of those, and include Asian characters in the preview in order to notice and prevent the problem on user side?

**Comment by elextr** [comment] 2024-02-18 08:12
@Asmageddon fonts have to be installed on windows, they are not part of Geany.  If a user wants a font with CJK characters they need to install one.

**Comment by elextr** [comment] 2024-02-18 08:36
Also, these fonts are Windows fonts and it would be illegal to redistribute them.  As it says [here](https://learn.microsoft.com/en-us/typography/fonts/font-faq#redistribution-and-extended-rights) "you may not redistribute the Windows fonts".
