### ISSUE TITLE
Find

### ISSUE THREAD

**Issue by caltrop-3** [geany/geany#1634] opened 2017-10-09 20:50 UTC
Find -> In Session
says 2 matches but when Next clicked says NOT FOUND

**Comment by elextr** [comment] 2017-10-09 21:50
In session is in all files that are open, next is in the current file, so your two matches were in files other than the current one.

**Comment by LarsGit223** [comment] 2018-03-17 11:55
IMHO this should be closed as it is not a bug and the implemented behaviour has been explained.

**Closed** 2018-03-17 11:56 UTC
Labels: invalid
