### ISSUE TITLE
Multiline paste

### ISSUE THREAD

**Issue by misopeth** [geany/geany#1083] opened 2016-06-21 22:29 UTC
If I hold down Ctrl+Shift I am able to make a rectangular selection; then if I start typing the text is written in every selected line. However this is not the case if instead of typing I paste some copied text: the text gets pasted only in the first row. I understand that this is the correct behaviour if one is pasting some text copied from a rectangular selection, but what if I am pasting only one line of text? Shouldn't the text be pasted on every selected line?

**Comment by elextr** [comment] 2016-06-21 22:49
Duplicate of #625

**Closed by elextr** 2016-06-21 22:49 UTC
