### ISSUE TITLE
Windows: blurred display on HiDPI screens

### ISSUE THREAD

**Issue by tmssngr** [geany/geany#1951] opened 2018-09-12 10:57 UTC
I'm using Geany 1.33 on Windows 10 with a 4k-monitor set to 200% zoom level. Please see the attached screenshot of Geany and Notepad using Consolas 11 font.
![windows 10 with 4k screen](https://user-images.githubusercontent.com/6029561/45420807-72f26e00-b68b-11e8-9b33-5d95ee43b1b3.png)

**Comment by codebrainz** [comment] 2018-09-12 14:43
This sounds like a duplicate of #692 and #1655 which both have a workaround in the comments.

**Comment by tmssngr** [comment] 2018-09-12 15:13
I reckon the workaround only applies if Geany is launched by clicking a shortcut, but not if the `geany.exe` is launched directly, e.g. from command line, right?

**Comment by codebrainz** [comment] 2018-09-12 23:59
@tmssngr not sure, best to try and see. If I remember correctly Windows lets you set compatibility options for an .exe file the same way.

**Comment by codebrainz** [comment] 2018-09-13 14:54
Closing as duplicate of #692, etc.

**Closed by codebrainz** 2018-09-13 14:54 UTC
Labels: gtk, windows
