### ISSUE TITLE
not working Lint in Geany on Windows

### ISSUE THREAD

**Issue by NTMan** [geany/geany#1259] opened 2016-10-07 07:58 UTC
Demonstration: https://youtu.be/d14ehelN-Ik
Manually i can launch jshint.

OS: Windows 7 x64
Geany 1.28

**Comment by NTMan** [comment] 2016-10-07 13:20
Geany able launch eslint only when full path specified. This is uncorrect.

Second problem: Geany couldn't again launch eslint (even if full path specified for eslint) if checked file stored with long path name.
Demonstration: https://youtu.be/IO31rX8JfNs

**Comment by codebrainz** [comment] 2016-10-07 18:36
> Geany able launch eslint only when full path specified. This is incorrect.

The directory where eslint is found must be in the `%PATH%` environment variable. Geany will need to be restarted after changing the environment variables.

> if checked file stored with long path name.

Maybe it's the space in the filename rather than the length? What if you try `C:\11 1`, does it fail?

**Comment by b4n** [comment] 2016-10-07 19:36
What is the error displayed in the statusbar (between the parentheses)?  I unfortunately don't read Russian so I can't tell, but I guess it must be something like "no such file or directory", "failed to change directory" or something like that?

And as @codebrainz suggests, I'd guess it's related to either the space or the Russian characters in the filenames.  Both being kinda odd, because I thought we fixed all that, but well, maybe not.

**Comment by NTMan** [comment] 2016-10-07 21:22
> The directory where eslint is found must be in the %PATH% environment variable.

![08 10 2016 02-13](https://cloud.githubusercontent.com/assets/200750/19205653/36c26674-8cfd-11e6-9cd1-2485f3a7bc95.png)
Of course I know about it. This is Windows specific problem not reproduced on Linux. 

> Maybe it's the space in the filename rather than the length? What if you try C:\11 1, does it fail?

I try two another experiment 'C:\11 1' - works fine, but 'C:\Я' - have same error message.
So this problem related to Russian char in file path. And I see that it Windows specific problem too, because '~\я' on Linux worked fine.
![screenshot from 2016-10-08 02-19-42](https://cloud.githubusercontent.com/assets/200750/19205777/e54ad938-8cfd-11e6-875d-d52a168a014e.png)


> What is the error displayed in the statusbar (between the parentheses)? 

Translated from Russian as "incorrectly specified folder name"

**Comment by elextr** [comment] 2016-10-08 00:15
If it only fails with non-ASCII characters in the filename it looks like a disagreement about the locale.

**Comment by NTMan** [comment] 2016-10-13 13:14
And this is possible fix?

**Comment by elextr** [comment] 2016-10-13 14:04
@b4n [WTF](https://github.com/geany/geany/blob/master/src/utils.c#L1238) that doesn't look like it handles locale on windows, and [build](https://github.com/geany/geany/blob/master/src/build.c#L804) tests the result immediately after return, using the still UTF-8 directory name, so no wonder it can't find the directory.

**Comment by codebrainz** [comment] 2016-10-13 14:23
@elextr "filename encoding" on Windows is [always UTF-8 with GLib](https://developer.gnome.org/glib/stable/glib-Character-Set-Conversion.html#g-filename-from-utf8).

**Comment by elextr** [comment] 2016-10-13 14:36
Yes, forgot that, but now we don't use glib to spawn stuff on windows any more so we need the right encoding to pass to spawn unless it converts?

**Comment by elextr** [comment] 2016-10-14 01:18
@NTMan you are welcome to provide patches, but (AFAIK) we currently have no regular windows contributor, so it may be slow if you don't I'm afraid.

**Comment by eht16** [comment] 2016-10-24 22:17
@NTMan this might be related to #1076 and a possible fix (or a step to a fix) might be in #1095.

It'd be cool if you could try:
http://download.geany.org/snapshots/old/geany-1.28nightly20160703_pr1095_setup.exe
(and http://download.geany.org/snapshots/old/geany-plugins-1.28nightly20160703_setup.exe in case you also have plugins installed) and report if anything changes in this version.

**Comment by NTMan** [comment] 2016-10-25 04:13
Yes, with attached here version the bug is gone.

**Comment by NTMan** [comment] 2016-10-25 20:42
The only thing that still does not work search in files through grep.

Search settings:
![26 10 2016 01-31 1](https://cloud.githubusercontent.com/assets/200750/19703360/fbfa16bc-9b1c-11e6-825f-b6bc060bf81a.png)

Search results:
![26 10 2016 01-32](https://cloud.githubusercontent.com/assets/200750/19703371/0447d41c-9b1d-11e6-970a-1575b4e511e0.png)

I also demonstrated at same screen what grep working from command line with the same search setting.

**Comment by elextr** [comment] 2016-10-25 22:37
This is a duplicate of #1229, see also #1237.

**Comment by eht16** [comment] 2016-11-13 17:20
This should be fixed now in Geany 1.29 (released today).
We merged #1095 which fixes locale issues when spawning external commands.

**Closed by eht16** 2016-11-13 17:20 UTC
