### ISSUE TITLE
Need own keyboard shortcuts for commands for compiling and running projects

### ISSUE THREAD

**Issue by GizehFire** [geany/geany#3385] opened 2023-02-04 19:07 UTC
**[build-menu]** _(geany.conf)_
(..)
**NF_03_CM=**
(..)

How can I define my own shortcut key for NF_03_CM?

**Comment by elextr** [comment] 2023-02-04 23:41
Keybindings are only available for the basic commands.  

IIRC the problem is the keybindings code cannot handle dynamic changes to the number of entries for a section.

**Comment by ntrel** [comment] 2023-02-08 17:53
As a workaround you can set an underlined character for the command label e.g. _d and then use Alt-B then D to run the command - assuming your build parent menu item is called Build and not translated.

**Comment by ntrel** [comment] 2023-02-10 18:10
Duplicate of #705.

**Closed** 2023-02-10 18:11 UTC
Labels: enhancement
