### ISSUE TITLE
Long file names should not be cut in window titles when possible

### ISSUE THREAD

**Issue by mikhailnov** [geany/geany#2473] opened 2020-04-11 10:46 UTC
See this screenshot:
![image](https://user-images.githubusercontent.com/15802528/79041746-c4ae0200-7bfa-11ea-8320-82d29eed3208.png)
There is enough place to print the whole filename in the window title, but it is reduced

**Comment by codebrainz** [comment] 2020-04-11 10:55
Duplicate of #2334 and discussed in #2335.

**Closed by codebrainz** 2020-04-11 10:55 UTC
