### ISSUE TITLE
pressing F11 four or five times cause system freez, hanging

### ISSUE THREAD

**Issue by esmaeelE** [geany/geany#1460] opened 2017-04-07 16:51 UTC
in Geany 1.27 running on  UBUNTU 16.04 lts, when on press four or five times F11, Full screen key
OS crash.

**Comment by codebrainz** [comment] 2017-04-07 21:59
Can't reproduce on Ubuntu 16.04 with Geany 1.30 using XFWM window manager.

**Comment by LarsGit223** [comment] 2018-03-17 15:28
I also cannot re-produce this with Geany (master, 1.34) on Ubuntu 16.04, Gnome desktop and GTK 2.24.30, GLib 2.48.2.

@esmaeelE: did you try Geany 1.33?

**Comment by b4n** [comment] 2018-09-19 20:50
Closing as we need more information and cannot reproduce.  Feel free to reopen if it still happens.

**Closed by b4n** 2018-09-19 20:50 UTC
Labels: can't reproduce
