### ISSUE TITLE
Home/End/Ctrl-C/Ctrl-V fail to work in Split View

### ISSUE THREAD

**Issue by vvedula22** [geany/geany#1107] opened 2016-07-02 00:19 UTC
Hello,

None of the usual controls (including home/end keyboard switches, copy/paste, etc.) function in split view. Please update if there is any fix for this.

Thanks

**Comment by elextr** [comment] 2016-07-02 00:24
Duplicate of #604 #988 and others

**Closed by elextr** 2016-07-02 00:24 UTC
