### ISSUE TITLE
Lose the last opened files

### ISSUE THREAD

**Issue by ghost** [geany/geany#1826] opened 2018-04-16 11:54 UTC
When I reboot the system - geany loses the list of open files, how to fix it?
System Kubuntu 12, and 14, and 16 - The same behavior.

**Comment by shiftee** [comment] 2018-04-16 12:28
Loses the list or doesn't save the latest version?

In my experience Geany closes without saving the list when it receives SIGINT.

To keep the list you need to use **File->Quit** after opening a new file or close and re-open the project.

Ideally this would be fixed

**Comment by RostislavVel** [comment] 2018-04-16 13:17
If you close geany in the manual - it retains. It is not very convenient! Other editors such oddities are not. Is it possible to do save project every time you open a new file?

**Comment by elextr** [comment] 2018-04-16 22:10
Crashing Geany is not the correct way to close it.  (Crashing it is what your system is doing to Geany if you logout or shutdown with Geany still running).

Even if the session was saved each time it was saved, its only one of the things that can be saved at shutdown, many plugins (which are made by people outside the Geany team) only save at shutdown.

**Comment by codebrainz** [comment] 2018-04-17 00:30
Duplicate of #1416 

I don't know what signals your OS is sending to Geany, but if it's not sending `SIGTERM` Geany won't even try to save the session. We could probably add other signals to be handled if it makes sense (mentioned in the comments on #1255).

**Comment by elextr** [comment] 2018-04-17 02:32
The problem is that many DEs won't wait, even if they send SIGTERM they don't allow any time for the save to happen before they SIGKILL the process.

**Comment by codebrainz** [comment] 2018-04-17 03:41
Which desktop environments don't have a session manager?

**Comment by elextr** [comment] 2018-04-17 03:41
As far as Geany is concerned, all of them :)

**Comment by codebrainz** [comment] 2018-04-17 03:42
But realistically all of the major Linux DEs/WMs do.

**Comment by RostislavVel** [comment] 2018-04-17 07:27
The behavior is the same on all kubuntu 12, 14, 16 versions. Geany crashes or not - I don't know. To save the list of open files in the project I specifically restart geany, every time you open or close files. If this is not done, then after the computer is restarted - the project list is not correct, consistently Repeated since 2010 !

**Comment by elextr** [comment] 2018-04-17 07:31
@codebrainz maybe there are too many negatives in it but what I meant is that Geany does not subscribe to any of the session managers, so effectively as far as Geany is concerned no DEs have session management.

**Comment by RostislavVel** [comment] 2018-04-17 07:31
Why not add the function to save list of projects each time you open or close files. Can it be done optional?

**Comment by elextr** [comment] 2018-04-17 07:32
@RostislavVel sure, just "somebody" has to do it.

**Comment by RostislavVel** [comment] 2018-04-17 07:35
@elextr I did not understand your answer?

**Comment by elextr** [comment] 2018-04-17 07:39
Saving the session (in project or user files) whenever files are opened or closed is possible, just that somebody has to contribute the code to do it, preferably with an option, since not everyone will want to hit the project/user file on every file open/close.

**Comment by RostislavVel** [comment] 2018-04-17 07:46
I'm a user, not a developer Geany. I wrote to support asking to resolve it sometime in the near future! I have Geany installed from a package and have no desire to build it from source.

**Comment by elextr** [comment] 2018-04-17 07:54
@RostislavVel thats fine, but Geany is a volunteer project, it is not run by a company, it has no paid developers, so things only happen when somebody contributes the code.

So what I am saying is, yes its possible and even reasonable (IMO) to save the session on file open/close, but somebody has to contribute it, and they should ensure it has an option since not everybody will want to use the facility.

**Comment by RostislavVel** [comment] 2018-04-17 08:02
Who can tell the place in code where I can add, and how do these changes contribute to the overall project?

**Comment by RostislavVel** [comment] 2018-04-17 08:03
That would be in the future to get the official version of the package with the same functionality.

**Comment by cheapy** [comment] 2021-07-31 17:57
While the program is still running is there a file somewhere that contains a list of the files open?  If so, could I later somehow manually inject that list into the startup?

If I could even just copy a particular folder or file, that would be good enough.  I occasionally lose my list of what I had open and when I run geany again it opens a different list of files..

**Comment by cheapy** [comment] 2021-07-31 22:53
Ok, I wrote a small script to generate document list every 5 minutes and keep the last 49 of them
[save_geany_files.zip](https://github.com/geany/geany/files/6911919/save_geany_files.zip)

**Comment by elextr** [comment] 2021-07-31 23:42
@cheapy the PR #2114 listed above saves the session whenever it changes, so with 1.37 or newer you shouldn't need to do anything.

**Comment by elextr** [comment] 2021-07-31 23:43
This probably should have been closed when #2114 was merged.

**Closed by elextr** 2021-07-31 23:43 UTC
Labels: duplicate, enhancement

**Comment by cheapy** [comment] 2021-08-01 19:41
I will have to wait till I switch to bullseye, it looks.  I wasn't able to get past the dependency issues to install a 1.37.1 on my buster based system.  I was able to build it from Git, but it gave me an error about missing Glade setup, so since bullseye is close, the easy answer is just to wait for it.

I'm sorry for not figuring out that the capability was added, and appreciate the effort of those who made it happen.
