### ISSUE TITLE
Geany fails to open a file (silently) with trailing zero chars

### ISSUE THREAD

**Issue by ghorwin** [geany/geany#2654] opened 2020-11-10 18:53 UTC
See attached data logger file - Geany just does nothing when trying to open this file. Debug log shows:

```
19:52:04: Geany INFO		: Trying to convert 140106 bytes of data from ISO-8859-1 into UTF-8.
19:52:04: Geany INFO		: Couldn't convert from ISO-8859-1 to UTF-8.
19:52:04: Geany INFO		: Trying to convert 140106 bytes of data from ISO-8859-2 into UTF-8.
19:52:04: Geany INFO		: Couldn't convert from ISO-8859-2 to UTF-8.
....
19:52:04: Geany INFO		: Trying to convert 140106 bytes of data from WINDOWS-1258 into UTF-8.
19:52:04: Geany INFO		: Couldn't convert from WINDOWS-1258 to UTF-8.
19:52:04: Geany INFO		: Trying to convert 140106 bytes of data from CP932 into UTF-8.
19:52:04: Geany INFO		: Couldn't convert from CP932 to UTF-8.
```
then nothing else.

Problematic file is attached below.

[WsIBK_2020-05-11_00-00-00.csv.zip](https://github.com/geany/geany/files/5519553/WsIBK_2020-05-11_00-00-00.csv.zip)

**Comment by codebrainz** [comment] 2020-11-10 19:03
Sounds like a duplicate of #618, #1508, #1708, #2081, etc.

Related: #1709

**Comment by ghorwin** [comment] 2020-11-10 19:09
Yup, duplicate

**Closed** 2020-11-10 19:09 UTC
Labels: duplicate
