### ISSUE TITLE
Geany segfaults after clicking in a new documents text area.

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [geany/geany#3857] opened 2024-04-24 21:00 UTC
If I open Geany and press Ctrl+N start typing a file and save it then click in the text area of the file with my mouse it segfaults... If I spam the mouse in the text area after pressing Ctrl+N also segfaults. I am running gentoo fully up to date compiled from source Geany version 2.0.

```
l33tlinuxh4x0r@Ryzen ~ $ geany -v
(geany:86563): GLib-GIO-DEBUG: 16:38:29.129: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(geany:86563): GLib-GIO-DEBUG: 16:38:29.131: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
Geany-INFO: 16:38:29.148: Geany 2.0, unknown
Geany-INFO: 16:38:29.148: GTK 3.24.41, GLib 2.78.4
Geany-INFO: 16:38:29.148: OS: Gentoo Linux
Geany-INFO: 16:38:29.148: System data dir: /usr/share/geany
Geany-INFO: 16:38:29.148: User config dir: /home/l33tlinuxh4x0r/.config/geany
Geany-INFO: 16:38:29.207: Loaded GTK+ CSS theme '/usr/share/geany/geany.css'
Geany-INFO: 16:38:29.209: System plugin path: /usr/lib64/geany
Geany-INFO: 16:38:29.212: Added filetype Groovy (65).
Geany-INFO: 16:38:29.212: Added filetype Nim (66).
Geany-INFO: 16:38:29.212: Added filetype Meson (67).
Geany-INFO: 16:38:29.212: Added filetype Kotlin (68).
Geany-INFO: 16:38:29.212: Added filetype Scala (69).
Geany-INFO: 16:38:29.212: Added filetype Arduino (70).
Geany-INFO: 16:38:29.212: Added filetype CUDA (71).
Geany-INFO: 16:38:29.212: Added filetype JSON (72).
Geany-INFO: 16:38:29.212: Added filetype TypeScript (73).
Geany-INFO: 16:38:29.212: Added filetype Graphviz (74).
Geany-INFO: 16:38:29.212: Added filetype Clojure (75).
Geany-INFO: 16:38:29.212: Added filetype Genie (76).
Geany-INFO: 16:38:29.212: Added filetype Cython (77).
Geany-INFO: 16:38:29.212: Added filetype Swift (78).
Geany-INFO: 16:38:29.218: Loaded libvte from libvte-2.91.so
Geany-INFO: 16:38:29.219: Loaded:   /usr/lib64/geany/overview.so (Overview)
Geany-INFO: 16:38:29.226: /home/l33tlinuxh4x0r/work.py : Python (UTF-8)
Geany-INFO: 16:38:29.234: Loaded /usr/share/geany/tags/std.py.tags (Python), 15267 symbol(s).
Geany-INFO: 16:38:29.252: /home/l33tlinuxh4x0r/work2.py : Python (UTF-8)
Geany-INFO: 16:38:29.255: /home/l33tlinuxh4x0r/work3.py : Python (UTF-8)
Geany-INFO: 16:38:29.257: /home/l33tlinuxh4x0r/work4.py : Python (UTF-8)
Geany-INFO: 16:38:29.259: /home/l33tlinuxh4x0r/work5.py : Python (UTF-8)
Geany-INFO: 16:38:29.261: /home/l33tlinuxh4x0r/work6.py : Python (UTF-8)
Geany-INFO: 16:38:29.264: /home/l33tlinuxh4x0r/work7.py : Python (UTF-8)
Geany-INFO: 16:38:29.267: /home/l33tlinuxh4x0r/work8.py : Python (UTF-8)
(geany:86563): GLib-DEBUG: 16:38:29.372: g_unix_open_pipe() called with FD_CLOEXEC; please migrate to using O_CLOEXEC instead
Geany-INFO: 16:38:33.653: unknown : None (UTF-8)
(geany:86563): GLib-GIO-DEBUG: 16:38:38.122: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(geany:86563): GLib-GIO-DEBUG: 16:38:38.146: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(geany:86563): dconf-DEBUG: 16:38:38.146: watch_fast: "/org/gtk/settings/file-chooser/" (establishing: 0, active: 0)
(geany:86563): dconf-DEBUG: 16:38:38.146: watch_established: "/org/gtk/settings/file-chooser/" (establishing: 1)
Geany-INFO: 16:38:41.194: /home/l33tlinuxh4x0r/broken.py : Python (UTF-8)
Geany-INFO: 16:38:41.195: /home/l33tlinuxh4x0r/broken.py : Python (UTF-8)
(geany:86563): dconf-DEBUG: 16:38:41.196: change_fast
Segmentation fault (core dumped)
```

gdb says the exact same thing every time I reproduce this bug.

```
0x00007ffff78d014e in free () from /usr/lib64/libc.so.6
```

Does anyone know why this is happening and or have a fix?

Edit:
In case this helps I could not reproduce the bug on windows. Seems to be Linux exclusive.

**Comment by elextr** [comment] 2024-04-27 01:40
Duplicate of #2736

**Closed by elextr** 2024-04-27 01:40 UTC
