### ISSUE TITLE
Geany run python script with non-english path (Geany 1.27)

### ISSUE THREAD

**Issue by YuriPetrov** [geany/geany#1278] opened 2016-10-26 10:56 UTC
I'm using Geany for writing small Python scripts. Unfortunately, when I try to run a script located in a non-english folder or that has a non-english name, Geany gives errors such as 

`Could not find terminal cmd.exe /Q /C %c or CreateProcess failed. The directory name is invalid.`

With an english path script runs ok. Scripts with non-english names work ok when are lauched from the cmd directly.

How it can be fixed?

**Comment by codebrainz** [comment] 2016-10-26 14:28
Sounds like a duplicate of #1076

**Comment by YuriPetrov** [comment] 2016-10-26 14:53
I've just tried 1.28 version on Windows 10. Same result.

can't run "cmd.exe /Q /C C:\Users\yuri\AppData\Local\Temp\geany_run_script_Z0U9PY.bat": Invalid folder name. Check terminal in settings

Terminal settings are default: `cmd.exe /Q /C %c`.

**Comment by yetanotherrepo** [comment] 2016-10-26 15:13
+1 i have same problem

**Comment by yetanotherrepo** [comment] 2016-10-26 15:17
@YuriPetrov я переместил файл с проектом в корень диска C и все заработало

**Comment by yetanotherrepo** [comment] 2016-10-26 15:26
@YuriPetrov проблема была в папке на русском языке в которой находился проект

**Comment by YuriPetrov** [comment] 2016-10-26 15:34
@yetanotherrepo понятно, что проблему можно решить таким образом. Речь о том, что это ненормальное поведение и его надо пофиксить (таких проблем нет, например в Atom или Sublime).

I think Geany take script folder as the current directory, and it leads to some issues. It should be fixed somehow in the Geany itself.

**Comment by eht16** [comment] 2016-10-26 19:33
Could you test the version mentioned in https://github.com/geany/geany/issues/1259#issuecomment-255882320? It's possible that the issue is fixed there.
And please keep the language in English, we don't read and speak Russian, thanks.

**Comment by YuriPetrov** [comment] 2016-10-27 22:06
@eht16 

I've tried 1.29 night build, same resuts. Screenshots attached.

![1](https://cloud.githubusercontent.com/assets/1536964/19787284/a6b13958-9caa-11e6-8869-f1609a313bd5.png)
![2](https://cloud.githubusercontent.com/assets/1536964/19787285/a6b4ea9e-9caa-11e6-907a-37651bad99b8.png)
![3](https://cloud.githubusercontent.com/assets/1536964/19787286/a6b6b41e-9caa-11e6-911f-c84c30be5392.png)

**Comment by codebrainz** [comment] 2016-10-27 23:02
> I've tried 1.29 night build, same resuts. Screenshots attached.

Did you try the one with the fix that @eht16 linked to?

http://download.geany.org/snapshots/old/geany-1.28nightly20160703_pr1095_setup.exe

**Comment by YuriPetrov** [comment] 2016-10-28 08:26
@codebrainz yes, output is the same.

**Comment by YuriPetrov** [comment] 2016-11-02 14:17
Does anybody have an idea to fix it?

**Comment by elextr** [comment] 2016-11-03 00:20
What codepage are you using?

Can you try with a UTF-8 locale?

**Comment by YuriPetrov** [comment] 2016-11-03 00:28
How can I check it?

**Comment by elextr** [comment] 2016-11-03 03:21
@eht16 IIUC (and as you know that may be debated where windows is concerned :) your patch above only converts the working directory, but its the path to the run_script thats now the problem.

**Comment by eht16** [comment] 2016-11-03 22:07
Nope, I think the command is converted as well.
Currently I'm a bit limited on time but will try to work on this on Sunday.

@YuriPetrov could you send me a ZIP archive with some test files/directories for testing?

**Comment by elextr** [comment] 2016-11-04 01:43
@eht16, see comment on #1095 the path to the run script does appear to be missed.

@YuriPetrov can you please translate the messages shown in the message window on your last image above, in particular the part after the : that is cut off.

**Comment by YuriPetrov** [comment] 2016-11-04 21:41
@eht16 , [Пример.zip](https://github.com/geany/geany/files/572701/default.zip)

@elextr ,

- "Не могу запустить команду сборки" ~ "Can't launch build command"
- "Неверно задано имя папки. Проверьте параметры терминала в настройках" ~ "The directory name is invalid. Check terminal parameters in settings"

**Comment by eht16** [comment] 2016-11-07 22:31
> @eht16, see comment on #1095 the path to the run script does appear to be missed.
@elextr I think https://github.com/geany/geany/pull/1095/files#diff-accf4ed6a17ca835afc078465aaa568aR623 (line 623) converts the path to the run script.

@YuriPetrov thanks for the file. After extracting the contents, I can execute successfully both Python scripts. So either my tests are wrong in some way or there is something else involved.
I have no idea.

**Comment by elextr** [comment] 2016-11-07 23:03
@eht16, ahh, I read that as utils_locale that does nothing on Windows, ok.

**Comment by YuriPetrov** [comment] 2016-11-07 23:12
@eht16 

I've noticed the following: 

- when a source file with non-english filename is in english-name folder: `geany_run_script_....bat` created ok, but on Windows it has UTF-8 W/BOM encoding and it conflicts with CP866 (default console codepage for Cyrillic Windows); if I add `chcp 65001` at the beginning of `geany_run_script_....bat`, it'll run ok; Maybe your's console codepage doesn't have conflicts with UTF-8 W/BOM;
- when a source file with non-english filename is in non-english folder, `geany_run_script_....bat` is not created at all and Geany asks to check Terminal settings.

**Comment by eht16** [comment] 2016-11-13 17:19
This should be fixed now in Geany 1.29 (released today).
We merged #1095 which fixes locale issues when spawning external commands.

**Closed by eht16** 2016-11-13 17:19 UTC
