### ISSUE TITLE
Underscores disappear at certain editor zoom factor

### ISSUE THREAD

**Issue by JohnCC330** [geany/geany#3038] opened 2021-12-01 15:26 UTC
I suspect this might be a problem with the editor module, but I think the issue should be raised here.

I'm using geany:
on Slackware64-current Linux,
geany 1.38 (built on 2021-11-23 with GTK 3.24.29, GLib 2.68.2)
I configged the editor fron as 'Bitstream Vera Sans Mono Roman' at 11 points.
It also happend with DejaVu Sans Mono Book' at 11 points.

At this scale, underscores are not renderered. 

When I scale the font up or down, using ctrl-- or ctl-+, the underscore reappears.
Of course I could probably change the font, but I have had some problems with
other mono-spaced fonts which have unicode-characters defined correctly (apart
from taste issues)

Note that rendering fails in Geany. The underscores are rendererd correctly in
a font selector program, including the 'Pick a Font' dialog in Geany preferences.

I have the impression that this might have appeared on upgrading to 1.38. I can't
remember if I ever noticed this before.

John

**Comment by elextr** [comment] 2021-12-01 23:59
Fixed in master

Duplicate of #2466 which has been re-pinned until next release.

**Closed by elextr** 2021-12-01 23:59 UTC
