### ISSUE TITLE
geany filetree scrollbars in gtk3

### ISSUE THREAD

**Issue by gkapad** [geany/geany#2436] opened 2020-02-12 22:06 UTC
hello i have install geany from the official latest debian buster repositories,

Geany Version: geany 1.33 (built on 2018-04-16 with GTK 3.22.29, GLib 2.56.1)

my problem is related with gtk3 i think,
and is that when i have a filetree with names somehow long, and i wish to make that tree smaller in width, Geany turncates the names, from the left (start) of the them, and not show any horizontal scrollbar at the bottom of the tree, 
On the other hand on the same case-scenario, spacefm-gtk3 deal with this with an expected behaviour. I have an screen shot to see what i mean ....

Has somebody knows about it, and how i can fixe it ?
thanks
![geany-scrollbars-gtk3](https://user-images.githubusercontent.com/17152917/74381679-95deff80-4df4-11ea-8087-2b40df3a30ae.jpg)

**Comment by gkapad** [comment] 2020-02-12 22:47
because somehow old version i build geany to 1.36
same behaviour ....
![geany-1 36-scrollbars-gtk3](https://user-images.githubusercontent.com/17152917/74384586-40a5ec80-4dfa-11ea-867b-db0b7ed4e727.jpg)

**Comment by elextr** [comment] 2020-02-12 22:51
The truncation on the left as the pane gets smaller happens on other GTK apps too, most likely a GTK thing, definitely not something Geany does.

**Comment by codebrainz** [comment] 2020-02-13 20:18
I think this is because it cannot shrink anymore due to the controls above the tree view in the Files tab. This could maybe be fixed by setting the combo box in the top of the files tab to not have a fixed minimum size.

**Comment by elextr** [comment] 2020-02-13 20:51
> I think this is because it cannot shrink anymore due to the controls above the tree view in the Files tab.

Happens on all tabs, not just file tab.  Also happens in gedit.

**Comment by codebrainz** [comment] 2020-02-13 22:08
> Happens on all tabs, not just file tab.

Because they're all packed into the same notebook.

> Also happens in gedit.

Because it's a bug in GTK+ that sets the minimum size of GtkEntry to 150 pixels, so unless they work around the issue, any GTK+ applications would show this behaviour.

**Comment by gkapad** [comment] 2020-02-14 00:19
> I think this is because it cannot shrink anymore due to the controls above the tree view in the Files tab.

Yes me too, when i toggle on/off the 'File' plugin, this issue becomes more/less.

Thanks for all your comment, at least it becomes clear, that we cant do something right now :)
( ... maybe if i dont have to install much to build with gtk2 ... ? ) Anyway,

since i'm not developer of geany, i'm not sure if i must close this or leave it for more comments,
maybe a moderator here knows better ... ,

thank you all

**Comment by b4n** [comment] 2020-02-14 08:23
Yeah apparently looking at your screenshots GTK2 does a "better" job with underallocation (when a control is given less space than its minimal requested size).  There's not much we can do about that, save being careful which widgets we use in the sidebar -- but plugins can go there, which I believe is the case in your example.

BTW, this is likely to be affected by a lot of theme details, including you using a monospaced font everywhere, which likely takes more space than other fonts.  Not saying it's a problem, just that might be one of the many contributing factors -- yet the root cause being the sidebar gets less width than it asked for, and doesn't behave so well in this case.

**Closed by b4n** 2020-02-14 08:23 UTC
Labels: gtk

**Comment by codebrainz** [comment] 2020-02-14 08:29
If there is a not too hacky way to set the combos/entries in filebrowser to not need so much space, it might be worth doing. I tinkered a bit with setting `width-chars` like in the linked bug report, on the combo entries in filebrowser, to low values, but it didn't seem to work.

**Comment by b4n** [comment] 2020-02-14 12:11
Yeah if we can mitigate this it'd be nice, but there will always be a minimal size for GTK widgets (the size under which they consider they can't draw themselves in a useful manner).  I think GTK3 changed the handling of underallocation from "the widgets handles whatever it can" to "cannot happen", and thus in a GtkPaned it just result in truncating the visible part.  Or something like this.
