### ISSUE TITLE
Text in Message Window unreadable in dark mode

### ISSUE THREAD

**Issue by HTofi** [geany/geany#2293] opened 2019-09-07 15:40 UTC
Hi, 

The message window has a problem with dark mode. The text color remains dark blue and dark red, which is hardly readable on a dark background: 
![image](https://user-images.githubusercontent.com/55027206/64476953-aaf49a00-d195-11e9-8567-410a2acf8b34.png)
Geany version : geany 1.35 (built on 2019-07-01 with GTK 3.24.8, GLib 2.60.2)
I am running Manjaro KDE, and have tested with breeze-dark, adwaita-dark and Materia themes. The result is the same in all cases.

**Comment by codebrainz** [comment] 2019-09-07 18:00
This is configurable since #1382, [see the manual](https://www.geany.org/manual/current/index.html#customizing-geany-s-appearance-using-gtk-3-css).

Closing as duplicate of at least #1376 and #1737.

**Closed by codebrainz** 2019-09-07 18:00 UTC
