### ISSUE TITLE
Current line number with different highlight

### ISSUE THREAD

**Issue by pqks** [geany/geany#2150] opened 2019-05-09 05:30 UTC
When you active line numbers these are highlighted, but the current line number has the same properties and is no possible difference of the all numbers. Is it possible modify the colorschemes for active this behavior? or if not exist that option I open a request for add something like this:

 
![numb](https://user-images.githubusercontent.com/39012860/57429412-a1602300-71f1-11e9-89d2-787834bb1593.png)

**Comment by elextr** [comment] 2019-05-09 06:23
The background of the entire line containing the cursor is highlighted.

**Comment by pqks** [comment] 2019-05-09 15:09
I've edit the title and description of the issue.

**Comment by elextr** [comment] 2019-05-09 23:03
Why do you need the numbers highlighted when the entire text line is highlighted?  The right example image only highlights the number not the line so its needed, but what benefit accrues from highlighting the numbers when the whole line is highlighted?

**Comment by codebrainz** [comment] 2019-05-10 00:00
@pqks I do not believe this is possible at the moment. It appears to in fact be supported by the underlying text editing widget Scintilla, so it could be added to Geany, but it would require someone interested in implementing it.

@elextr I guess the idea is that you can then turn off highlighting the whole current line, which could be annoying/distracting, and still see an indication of the current line. QtCreator does this with the default theme and it does look a little nicer, IMO.

Anyway, closing as a duplicate of #844.

**Closed by codebrainz** 2019-05-10 00:00 UTC
Labels: enhancement, question
