### ISSUE TITLE
Mouse position off by a few lines if 'prefer tabs for opening docs' is set

### ISSUE THREAD

**Issue by jorisgeer** [geany/geany#2463] opened 2020-03-25 11:41 UTC
If the MacOs dock preference setting 'prefer tabs when opening documents is set, mouse navigation is off by a few lines. Only when dragging out to detach into a new window, the mouse position is correct.

**Comment by codebrainz** [comment] 2020-03-25 15:06
This sounds like a dupe of #1428 (and others). Maybe try the latest version instead of [unspecified version you are using].

**Comment by joriswu** [comment] 2020-04-04 10:25
This is 1.36, the latest release.

**Comment by codebrainz** [comment] 2020-04-04 16:59
Can you paste the information on the Info tab in the about dialog? It should say the date it was built as well as the version of GTK+ and GLib libraries.

**Comment by elextr** [comment] 2020-04-04 23:56
> This is Geany 1.36, the latest release. And macOS Mojave 10.14.6

Just to confirm you downloaded `geany-1.36_osx-2.dmg` (note the -2)

**Comment by techee** [comment] 2021-11-19 23:46
I believe this was fixed by adding
```
NSWindow.allowsAutomaticWindowTabbing = NO;
```
to the launcher here
https://github.com/geany/geany-osx/blob/e1fb74b386915fc31e3ef11686a18f51694f8d63/Launcher/geany/geany/main.m#L260

This line was added quite a while back so the issue should be fixed in the last several releases.

**Closed by techee** 2021-11-19 23:46 UTC
Labels: macos
