### ISSUE TITLE
Open in New Window broken in 1.25

### ISSUE THREAD

**Issue by layingback** [geany/geany#590] opened 2015-07-27 13:19 UTC
Right click on file editing Tab's title brings up navigation menu plus 'Open in New Window' (just above the Close options).

Has worked on all earlier versions, including 1.24.1, but on new (1.25) version, nothing happens.  No new copy of Geany opens, no visual indication of failure that I can see.

[ Workaround requires loading new copy of Geany, and then manually locating file to open. ]

Environment was Ubuntu / Ubuntu Mate 14.04 AMD64.

**Comment by elextr** [comment] 2015-07-27 23:11
The "new window" is really a new instance of geany, so it needs to find `geany` in your path.  If  `geany` is not installed in a directory in path, or path is not set right (such as starting it from a desktop menu which does not run a shell, so it does not set path) then it will not be found.

**Comment by codebrainz** [comment] 2015-07-28 00:02
I can confirm on the same Ubuntu version, the debug messages shows this when I try:

```
Unable to open new window: Failed to execute child process "" (No such file or directory)
```

I also just tried running from the command line using Geany from my `$PATH` and it does the same thing. Maybe it's related to the changes @techee made regarding encoding? FWIW my locale is `en_CA.UTF-8`.

**Comment by elextr** [comment] 2015-07-28 00:04
I don't even get that far, if I start Geany from a non-standard location I get `Unable to find 'geany'`.

**Comment by codebrainz** [comment] 2015-07-28 00:37
I think I found it, right [here](https://github.com/geany/geany/commit/232d4dacded6d98a827414d62fa9879f618fb4f1#diff-74710e3ecbe94109f39de34133e1c8caR2165) it takes a pointer to an automatic variable that goes out of scope immediately afterwards (same thing in the OSX code path).

**Comment by codebrainz** [comment] 2015-07-28 01:06
I made [patches to fix in two different ways](https://gist.github.com/codebrainz/9dd84b5a7c08e710085c). I probably like the "static" one better, but either seems ok. I'll apply it soon if nobody fixes it first or complains about the patch.

**Comment by elextr** [comment] 2015-07-28 01:21
Oops, commented on the gist:

Well, I would just move the declarations of osx_argv and unix_argv outside the if, but that isn't absolutely the maximum efficiency so I expect the premature optimisers will reject that :)

**Comment by techee** [comment] 2015-07-28 20:19
> I think I found it, right here it takes a pointer to an automatic variable that goes out of scope immediately afterwards (same thing in the OSX code path).

Ah, yes, my fault, sorry. I remember I tried to write it in as little amount of lines of code as possible and this crap is the result.

@codebrainz Haven't checked in detail but both patches look good in principle, I also probably prefer the static one.

**Comment by elextr** [comment] 2015-07-28 22:02
@codebrainz just a question on the patches, since the args are going into a fixed position in the array why do you use argc++, why not just fixed indixes?

**Comment by codebrainz** [comment] 2015-07-29 00:08
@elextr just to avoid hard-coding each index, and that the index of the last NULL which is common to both paths in a different index in each case. This way if you add an item to either code path, you just need to make sure the array is big enough and stick the assignment any old place without changing the others. For such a trivial case either way would be fine though, I just think this is a little nicer.

**Comment by b4n** [comment] 2015-07-29 18:09
@codebrainz good catch, oopsie.  Either one would be fine, or @elextr's too.  As @techee I have a slight preference for the static versions, but any would be fine.

**Comment by kugel-** [comment] 2015-08-03 07:17
Not sure if static is the right word, but yea, the the non-dynamic variant should be preferred :)

**Comment by codebrainz** [comment] 2015-08-03 23:56
@kugel- yeah, "automatic" or "stack allocated" are probably more apt terms, I just meant static as the opposite of dynamic, somewhat confusingly not the "static" storage duration/keyword :)

**Closed** 2015-08-04 00:06 UTC
