### ISSUE TITLE
C++ highlighting new type by ,,using'' syntax

### ISSUE THREAD

**Issue by WaldekA** [geany/geany#1944] opened 2018-09-04 07:40 UTC
When I   typedef int abc;  abc is highlighted as a new type, but    using abc = int;   doesn't.

Moreover, it would be niece to have third kind of color for keywords.  

One more thing, is it possible to declare keywords highlighted as numbers (ex. true, false, nullptr in the same color as 42, 0xDEADBEEF and so on) ?

**Comment by elextr** [comment] 2018-09-04 07:54
> When I typedef int abc; abc is highlighted as a new type, but using abc = int; doesn't.

duplicate of #545 (one of)

The parsers come from the [Universal ctags](https://github.com/universal-ctags/ctags) project (I'm getting sick of saying that).  That project is developing a new C++ parser which may be better, watch this space.

> Moreover, it would be niece to have third kind of color for keywords.

Highlighting lexers determine the number of sets of defined names they accept.  The lexers are part of the [Scintilla](https://www.scintilla.org/) project and the change would need to happen there first.

> is it possible to declare keywords highlighted as numbers (ex. true, false, nullptr in the same color as 42, 0xDEADBEEF and so on) 

Each set of keywords has its own style and thats separate from numbers, but there is nothing stopping you editing your colour scheme to make the two styles look the same.

**Comment by CKD4XXH** [comment] 2018-09-12 14:54
I am eagerly awaiting that universal-ctags-like tagmanager!
The `using aa = ........`-like aliases should be recognized. The "Go to symbol definition" should work (currently does not), i.e. should go to this alias definition. Allegedly the universal-ctags recognizes it.

**Closed** 2021-12-19 00:04 UTC
