### ISSUE TITLE
I want gtk2 statusbar

### ISSUE THREAD

**Issue by Komosa** [geany/geany#1600] opened 2017-09-04 10:17 UTC
Hi,
after update to 1.31 on centos7.3 I got also gtk3 statusbar.
Only visible difference is that it uses about 2.5 more vertical space.

It would be nice to be able select gtk version in preferences/cmdline.

**Comment by elextr** [comment] 2017-09-04 12:42
The selection of Geany being GTK2 or GTK3 is made when it is compiled as it has to be linked with the GTK2 or GTK3 libraries, it is not possible to select at runtime.

Can you post the versions of GTK and Glib that Geany reports in the first few lines of `Menu->help->debug messages`?

**Comment by codebrainz** [comment] 2017-09-04 17:26
I assume you're using the horrible "Adwaita" GTK+ theme, have you tried a different one?

**Comment by elextr** [comment] 2017-09-04 23:15
Yeah, it could be a broken theme (in either GTK2 or GTK3).  Thankfully my distro (Mint Cinnamon) makes the effort to make themes that look the same on both.

**Comment by codebrainz** [comment] 2020-05-24 17:09
Duplicate of #1419.

**Closed by codebrainz** 2020-05-24 17:09 UTC
Labels: duplicate, gtk, gtk-theme, invalid
