### ISSUE TITLE
saving files in freebasic

### ISSUE THREAD

**Issue by Plutonium5793** [geany/geany#2632] opened 2020-10-21 14:18 UTC
I use geany as an IDE for freebasic under fedora(32) linux. this is a minor complaint that is driving me nuts.  I don't believe it has anything to do with freebasic.  When i go to save a file, the filename is highlighted, but if I just start to type in the new name, a search box opens,and the text goes into the search box while the filename remains highlighted.  It seems to me that if the filename is highlighted (filename.bas) --the underlined is highlighted that the focus should be on that, and not an invisible search box which only appears when you start typing.   To correct one has to move the mouse to the filename and rehighlight the name.   
![highlight](https://user-images.githubusercontent.com/4324823/96732709-e0e2e680-1375-11eb-90ac-e79a095e82a3.png)
I have attached a picture of the thing.  I called up this menu and typed the letter 'a'.  Note the filename is highlighted, but the a went into a search box.   Thanks for any help,
John

**Comment by elextr** [comment] 2020-10-21 21:43
This is a "feature" of the GTK toolkit that provides the file dialog.  The highlighting of the filename does not indicate that the name box has focus, whilst its theme dependent usually the box will be outlined if it has focus.

Instead the namelist has focus, and as you found typing there creates a filter.

**Comment by codebrainz** [comment] 2020-10-21 23:57
You can use the <kbd>Ctrl</kbd>+<kbd>L</kbd> shortcut to switch to direct Location mode.

Duplicate of #2267

**Closed** 2020-10-22 00:31 UTC
Labels: duplicate, gtk, invalid
