### ISSUE TITLE
unneeded saving question

### ISSUE THREAD

**Issue by paolobenve** [geany/geany#3452] opened 2023-04-10 00:57 UTC
I'm often using geany in order to perform simple o not simple operation on texts. I open geany, I paste a text, I edit it, and then I cut it in order to paste into another app.

After doing all this stuff, if I close geany, it asks me if I want to save the content. But:

- I opened geany with a brand new void file
- I'm closing geany/the document without any content

I think that the document/geany can be safely closed without asking anything.

**Comment by elextr** [comment] 2023-04-10 01:54
Duplicate of #1710

**Closed by elextr** 2023-04-10 01:54 UTC
