### ISSUE TITLE
Spell checking almost invisible on the last line

### ISSUE THREAD

**Issue by dandv** [geany/geany#1116] opened 2016-07-06 10:21 UTC
While editing files longer than one page, Geany manages the scroll position such that the currently edited line is always the bottom-most line. One unfortunate side effect of this is that the spell checking underlining will be hidden beneath the status bar (depending on the height of the window):

![image](https://cloud.githubusercontent.com/assets/33569/16614995/a4b66f00-4328-11e6-973f-41891bfb91d6.png)

In the screenshot above, you can barely see that "Filller" was highlighted as misspelled.

One way other editors (e.g. GitHub right here) handle this, is by leaving some space underneath the last line in the file. As a workaround, you can repeatedly scroll down in Geany, but that gets annoying while editing. 

You might need to adjust the height of the Geany window to reproduce the problem.

**Comment by elextr** [comment] 2016-07-06 10:59
The Scintilla editing component that Geany uses always starts with a line boundary at the top of the screen and shows lines down from there, which can leave a fractional line at the bottom that the cursor won't enter, or if you are lucky(?) and have the window an exact multiple of the line height the cursor can go right to the bottom.

Github switches the fractional line to the top of the screen if the cursor enters the last line and vice versa.  This change would have to be made in Scintilla as Geany has no control over that.  

Scintilla is a separate project and you can request it at their feature request [tracker](https://sourceforge.net/p/scintilla/feature-requests/).

**Comment by b4n** [comment] 2016-07-06 12:59
Looking at your screenshot it looks like you have Ubuntu's overlay scrollbars.  It's very possible they overflow a few pixels on the editing are hiding the bottom of the line.

I indeed cannot reproduce this on my system, where when I manage to put the bottom line the closest to the bottom of the editing area, I get this:
![bottom-line-squiggle](https://cloud.githubusercontent.com/assets/793526/16616890/8ac2e8b4-4380-11e6-9721-cd400250ead4.png)
As you can see, the squiggle underline doesn't oveflow the line boundaries, so is completely visible here.  I wonder: does it overflow on your system, or is about 1 px of the whole line missing?

Also, one reason I find the red squiggle hard to see on your capture isn't that one pixel of it is missing but that it has a color too similar to what I believe is the bottom scrollbar.  It's kind of unfortunate to have such non-background colors around an area containing unknown content.  Sure, Scintilla could have a padding, but that would waste screen estate for nothing.
A workaround could be changing the color of that underline (not currently configurable unfortunately) or of that scrollbar.

However, we could indeed set [the Y caret policy](http://www.scintilla.org/ScintillaDoc.html#SCI_SETYCARETPOLICY) with an offset so the last line is never on the bottom, something like `SCI_SETYCARETPOLICY(CARET_SLOP | CARET_STRICT | CARET_EVEN, 1)`.
I guess that'd be reasonable, but may require a setting.  Also, note that if scrolling past the last line is disabled, this won't help with the very last line, as there are none to display below it.

**Comment by eht16** [comment] 2016-07-06 21:05
@dandv you could also try the option "Stop scrolling at last line" in Preferences->Editor->Display. When disabled, this option let you scroll down the last line and so there is enough space to the overlay scrollbars.

**Comment by b4n** [comment] 2016-07-29 14:20
See also #1152 and #1154

**Comment by b4n** [comment] 2016-08-21 11:59
Closing this, because IMO it's mostly the Ubuntu's theme fault, plus now #1154 is merged so there should be a decent workaround.

**Closed by b4n** 2016-08-21 11:59 UTC
Labels: enhancement, scintilla

**Comment by b4n** [comment] 2016-11-01 16:29
Also now #1185 allows to configure the indicator color, so there's one more workaround.
