### ISSUE TITLE
GTK+ file chooser dialog shows "Unknown" Modified times

### ISSUE THREAD

**Issue by dunkfan** [geany/geany#2453] opened 2020-03-17 14:34 UTC
I've a feeling that this is due to some Windows 10 update
It is not possible to read the modification times in the File open window.
Every column entry for each file just says "Unknown"
This used to work fine in each Geany version, reinstalling older versions does not help.
I have an old portable app version 0.18. There it works.

**Comment by codebrainz** [comment] 2020-03-17 15:28
Just to be clear since the title says "file browser" and the description says "File open window", are you talking about the File Browser plugin, or just the normal Open File Dialog that opens when you use File->Open menu item, as if to open a new file?

For the latter, here it's working OK with 1.36 on Win 10 Pro (OS build 18363.720).

**Comment by dunkfan** [comment] 2020-03-17 15:54
Sorry I really meant the file open window

 

So that explains it, I need an update.

Version 1809 17763.805. 

Win 10 Enterprise supplied by IT, no updates in ages…

 

I really miss not being able to sort.

The windows file open dialog just doesn’t cut it in comparison.

 

Many thanks, 

 

Mark

**Comment by codebrainz** [comment] 2020-03-17 16:14
@dunkfan are you by any chance viewing a network or otherwise unusual path? Here I'm just testing with local hard drive (actually a virtual/VM hard drive).

**Comment by dunkfan** [comment] 2020-03-17 16:23
No everything is local. The 0.18 portable version still works.

**Comment by codebrainz** [comment] 2020-03-17 16:30
I think I know what it is, it seems to be related to the language/locale, perhaps it's not matching your system locale, so GTK+ can't figure out how to format the date and just puts Unknown instead. Can you paste the first few lines of `Help->Debug Messages`?

I can reproduce if I set the `LANG` environment variable to `C`, but not when I use a proper locale like `en_CA.utf8`, `en.utf8` or `de.utf8` or the default. My Windows is set to `English (United States)` language/locale.

**Comment by dunkfan** [comment] 2020-03-17 16:34
16:30:30: Geany INFO		: Geany 1.36, C
16:30:30: Geany INFO		: GTK 2.24.32, GLib 2.60.6
16:30:30: Geany INFO		: System data dir: C:\Program Files (x86)\Geany\data
16:30:30: Geany INFO		: User config dir: C:\Users\mg\AppData\Roaming\geany
16:30:30: Geany INFO		: System plugin path: C:\Program Files (x86)\Geany\lib\geany
16:30:30: Geany INFO		: Added filetype Arduino (61).
16:30:30: Geany INFO		: Added filetype Clojure (62).
16:30:30: Geany INFO		: Added filetype CUDA (63).
16:30:30: Geany INFO		: Added filetype Cython (64).
16:30:30: Geany INFO		: Added filetype Genie (65).
16:30:30: Geany INFO		: Added filetype Graphviz (66).
16:30:30: Geany INFO		: Added filetype Groovy (67).
16:30:30: Geany INFO		: Added filetype JSON (68).
16:30:30: Geany INFO		: Added filetype Kotlin (69).
16:30:30: Geany INFO		: Added filetype Nim (70).
16:30:30: Geany INFO		: Added filetype Scala (71).
16:30:30: Geany INFO		: Added filetype Swift (72).
16:30:30: Geany INFO		: Added filetype TypeScript (73).
16:30:30: GLib-GIO DEBUG	: _g_io_module_get_default: Found default implementation winhttp (GWinHttpVfs) for ‘gio-vfs’
16:30:30: Geany INFO		: Loaded:   C:\Program Files (x86)\Geany\lib\geany\filebrowser.dll (File Browser)
16:30:30: Geany INFO		: Loaded:   C:\Program Files (x86)\Geany\lib\geany\splitwindow.dll (Split Window)
16:30:30: Geany INFO		: unknown : None (None)
16:30:40: Geany INFO		: C:\Users\mg\Documents\IconSRC\head_41\gen\src\prg\scripts\tix\iconnmr\bruklib\Ez_Lib.tcl : Tcl (UTF-8)

**Comment by codebrainz** [comment] 2020-03-17 16:39
Yeah, you're using `C` (hardcoded/builtin) locale, I can reproduce it with that. Try to open a command prompt, change directory to `C:\Program Files (x86)\Geany\bin` and run `set LANG=en` (or whatever language you use/want) and press enter, and then type `geany` and press enter.

Is it possible when you installed Geany that you didn't install the localization files? I believe they are selected for installation by default.

**Comment by codebrainz** [comment] 2020-03-17 16:40
Also you can compare that same first line of `Help->Debug Messages` with the old portable version that is working, I expect you'll find that it's not using the `C` locale.

**Comment by dunkfan** [comment] 2020-03-17 16:44
Cant check the old version right now, but yes the set LANG=en fixes it
Deselected nothing when installing, but always installing with Geany removing the last version itself.
Tried a complete fresh install too, but this fix will do the trick for me!
THANK YOU

**Comment by codebrainz** [comment] 2020-03-17 16:54
To make it permanent, you can edit the Geany shortcut Properties, and change the `Target:` to the following:

```batch
C:\Windows\System32\cmd.exe /c "SET LANG=en&& START /D ^"C:\Program Files (x86)\Geany\bin^" geany.exe"
```

You can change `en` in above with other language code if you like, of course.

**Comment by codebrainz** [comment] 2020-03-17 16:56
Closing since solution found and the issue is not Geany's fault, at most it's a GTK+ issue.

**Closed by codebrainz** 2020-03-17 16:56 UTC
Labels: gtk, i18n, windows
