### ISSUE TITLE
the file on the disk os more recent than the current buffer

### ISSUE THREAD

**Issue by sevenskull** [geany/geany#649] opened 2015-09-09 17:55 UTC
I am accessing a file in another computer through samba in a mounted folder, when i save the file, sometimes, it shows the message "the file .... on the disk os more recent than the current buffer", and i am the only one acessing it and writing to it.
I setted the timeout to 5 seconds, because 30 is too much for checking modifications if another user is editing, but now there is this annoying message, show up, even when there are no modifications. It's something about 50% chance showing it.
I know i can disable it, sometimes i do, when i am sure the only one editing it, but in some cases i have to turn it on, to avoid overwriting others changes.

I am using Geany 1.25.

**Comment by elextr** [comment] 2015-09-09 22:38
duplicate of #605

**Closed by elextr** 2015-09-09 22:38 UTC
