### ISSUE TITLE
Vertical editing paste only pastes one line

### ISSUE THREAD

**Issue by AdamDanischewski** [geany/geany#841] opened 2015-12-28 21:30 UTC
I really like the vertical editing capability of Geany but I noticed that the paste feature only hits one line, I think the logic should presume when multiple lines are vertically selected that a paste issued should be applied to all lines in the vertical selection (instead of only the first one). 

To duplicate create a new test document, enter a few lines 
one 
two 
three
four

Then write a word lets say "line " copy it to the clipboard and then vertically select the beginning column of the four lines above by (holding SHIFT + ALT and clicking the beginning of line 1 then clicking the beginning of line four (you should see the cursor blinking across the entire selected lines). 

If you type in manually from here it will be applied to all selected lines, but hitting Paste/Ctrl-V you get the following: 
line one 
two 
three
four

As you can see the paste is applied to only the first line in the selection.

**Comment by elextr** [comment] 2015-12-28 21:57
Duplicate of #625

**Closed by elextr** 2015-12-28 21:57 UTC
