### ISSUE TITLE
Print white text on white background when  "invert syntax highlighting colors" is ticked

### ISSUE THREAD

**Issue by 3togo** [geany/geany#1791] opened 2018-03-01 09:55 UTC
If "invert syntax highlighting colors" is ticked, (Pref->Editor->Display), the print out will print white text on white backgroud. 
![screenshot from 2018-03-01 17-50-18](https://user-images.githubusercontent.com/731338/36838206-872c616a-1d79-11e8-8c85-d6e6ac2670b4.png)
![screenshot from 2018-03-01 17-49-48](https://user-images.githubusercontent.com/731338/36838210-8b018004-1d79-11e8-8c81-73b6349666aa.png)

**Comment by elextr** [comment] 2018-03-01 09:58
Duplicate of #1551

**Closed by elextr** 2018-03-01 09:58 UTC

**Comment by 3togo** [comment] 2018-03-06 02:06
Any chance to let user define a hotkey for "Invert syntax hightlighting color" or temporarily disable "Invert syntax hightlighting color" while printing?
