### ISSUE TITLE
Execute button wont work properly

### ISSUE THREAD

**Issue by mrstanlez** [geany/geany#1369] opened 2017-01-17 15:53 UTC
I have xterm and also xfce4-terminal

**Comment by frlan** [comment] 2017-01-17 15:59
Can you please add more details like filetype, error message, .... Something more we could use to reproduce ;)

**Comment by mrstanlez** [comment] 2017-01-17 16:07
Yes,
after install, click on button < Build >, compiler wrote:
make: *** No targets specified and no makefile found.  Stop.

and Execute button: "./%e" wont work, with xfce4-terminal.

This is my favorited editor. Please fix it.

2017-01-17 16:59 GMT+01:00 Frank Lanitz <notifications@github.com>:

**Comment by elextr** [comment] 2017-01-17 23:27
What language is the program you are trying to build and execute?

**Comment by mrstanlez** [comment] 2017-01-18 16:25
The code:
#include <stdio.h>
#include <string.h>

int main()
{
    FILE *fp;
    char ret[25];
    int index;

    fp = fopen("test.txt","w");
    strcpy(ret,"test 1");

    for(index = 1; index<=10; index++)
     fprintf(fp,"%s # of row %d\n",ret, index);

    fclose(fp);
    return 0;
}

and the message says, that can not run process of child. Directory or file
doesnt exist.

2017-01-18 0:27 GMT+01:00 elextr <notifications@github.com>:

> What language is the program you are trying to build and execute?
>

**Comment by elextr** [comment] 2017-01-18 23:21
Did you build the executable before you tried to run it?

**Comment by mrstanlez** [comment] 2017-01-19 12:44
I 'm programmer 23 years. C, C++, Java, Python.

Dňa 19. 1. 2017 12:21 dopoludnia používateľ "elextr" <
notifications@github.com> napísal:

**Comment by b4n** [comment] 2017-01-19 13:05
Works for me just fine if I

1. open a fresh Geany (1.29)
2. replace "xterm" to "xfce4-terminal" in the Preferences/Tools (giving me `xfce4-terminal -e "/bin/sh %c"`)
3. paste the sample C program into the buffer
4. save it as */tmp/1369.c*
5. click on the "Build" icon (<kbd>F9</kbd>)
6. click on the Execute icon (<kbd>F5</kbd>)

> after install, click on button < Build >, compiler wrote:
> make: *** No targets specified and no makefile found.  Stop.

This is odd, *Build* shouldn't be running `make` by default

> and Execute button: "./%e" wont work, with xfce4-terminal.

Does the file actually exist?  Should be the name of your source file minus the extension, next to the source file.

**Comment by elextr** [comment] 2017-01-19 13:05
Please provide information that is relevant to the problem to help solve it.

Since you pasted the whole program we will assume C language.  What actions did you use to build the executable?  Does an executable with the same name as the source exist in the same directory?  The message you pasted above would suggest not "Directory or file doesnt exist.".

You mentioned clicking on the "Build" button, it is assumed you mean the toolbar button.  The message you received is from `make` which is the command it will run by default.  The message says you have no makefile, so that action did not build any executable.  If you have no makefile you need to select a different action for the toolbar button, such as the one to use the build menu "build" command, which by default builds an executable for the current document.

**Comment by AldanisVigo** [comment] 2017-07-30 16:04
Thanks b4n, worked for me.

**Comment by DS-Minetest** [comment] 2017-08-17 15:39
I've also got a problem, I don't know if it's related to this.
I use Geany 1.29 and LXTerminal 0.3.0 on Lubuntu 17.04.
A simple code to test it:
```C++
#include <iostream>

int main()
{
	std::cout << "bla";
}
```
Pressing F9 to build, then F5 to execute results in:
![screenshot](https://user-images.githubusercontent.com/7613443/29420619-ca091e20-8372-11e7-8b6d-899de710929b.png)
I'm not sure if it's geany's fault.

**Comment by b4n** [comment] 2017-08-20 00:28
@DS-Minetest works for me with current Geany version under Debian.

What is your *Preferences → Tools → Terminal* setting?

**Comment by HybridDog** [comment] 2017-08-20 09:15
That's the wrong issue: #1515

**Comment by elextr** [comment] 2017-08-20 09:24
@HybridDog if you mean this appears to be a duplicate of #1515 then you appear to be right, @DS-Minetest try the solution shown there.

**Comment by elextr** [comment] 2017-08-21 00:10
@DS-Minetest you probably meant to post here, not on #1515, you said:

"I changed the execute command in the settings from "./%e" to ./%e but somehow it doesn't fix the problem, do I have to remove the quotes somewhere else?"

Not sure what else to suggest, except that it may be something specific to lxterminal, but I don't know of any regular contributors who use it to be able to test.  

Which directory did yo save the test file in?

**Comment by HybridDog** [comment] 2017-08-21 07:14
The quotes need to be removed at the terminal command setting.
`x-terminal-emulator -e /bin/sh %c`

**Comment by DS-Minetest** [comment] 2017-08-21 11:56
>you probably meant to post here

I thought,
>This is the wrong issue.

and wanted to post it at the right one.

Ah, I found the terminal command setting (in modify/settings/tools (hopefully I translated it correctly)) thanks!

**Comment by codebrainz** [comment] 2019-04-02 23:58
Closing after 2+ years of waiting for info and people not being able to reproduce.

**Closed by codebrainz** 2019-04-02 23:58 UTC
Labels: waiting for information
