### ISSUE TITLE
The Underline (ASCII 95) is not visible

### ISSUE THREAD

**Issue by Mininock-afk** [geany/geany#2287] opened 2019-09-06 11:02 UTC
geany -V: geany 1.35 (kompiliert am 2019-07-01 mit GTK 3.24.8, GLib 2.60.2)
pkg-config --modversion gtk+-3.0: 3.24.10
pkg-config --modversion gtk+-2.0: 2.24.32
uname -r: 5.2.11-arch1-1-ARCH

I try to explain it: In geany the underline is not visible its shown as a space. If you open the same
text in an other editor the underline is present.
With this bug its impossible to use geany as an editor, especially not as a developement tool.

e.g.:
original: BASH_CMDS: a bash_variable
geany: BASH CMDS: a bash variable
hex-editor: 42 41 53 48 5F 43 4D 44 53 3A 20 61 20 62 61 73 68 5F 76 61 72 69 61 62 6C 65 0A

Kind regards, Walter

**Comment by elextr** [comment] 2019-09-06 11:20
Works for me.

Its likely that your font is not providing correct height info and the underscore is being overwritten by the next line.

You can adjust interline spacing with the `line_height` setting in your colour scheme (if its set there) or in `filetypes.common`.

**Comment by codebrainz** [comment] 2019-09-06 14:33
Sounds like a duplicate of #1387?

**Comment by eht16** [comment] 2019-09-07 10:29
It happens on my system as well:
ArchLinux
Xfce 4.14
Geany 1.36 (git >= c88c27e2), en_US.utf8
GTK 2.24.32, GLib 2.60.6
Font: DejaVu Sans Mono Book
Size: 8

As mentioned in #1387, changing font size makes the underscore visible (though there no usable font size where it appears).

The same happens with Scite (Version 4.2.0 compiled for GTK 3.24.10).

So I think this might be an issue either with the DejaVu Sans font or with Scintilla.

**Comment by elextr** [comment] 2019-09-07 10:40
Do other fonts work?

**Comment by eht16** [comment] 2019-09-07 10:43
Yes, some other fonts work.

**Comment by codebrainz** [comment] 2019-09-07 17:49
I can't reproduce here with either a GTK+ 2 or GTK+ 3 build with "DejaVu Sans Mono Book", although the underscore is well below the other letters, and I've definitely hit this issue before at some point.

Seems to be [fairly common](https://www.google.com/search?q=dejavu%20font%20underscore), maybe it was fixed in `fontconfig` or `fonts-dejavu` or something (`fontconfig` v2.12.6 and `fonts-dejavu` v2.37-1 here).

**Comment by elextr** [comment] 2019-09-07 21:30
Definitely is the font, not Geany, and workaround described above.

**Closed by elextr** 2019-09-07 21:30 UTC

**Comment by GFdevelop** [comment] 2019-10-11 22:43
Is not the font, for me not work the size of the font and I am using Monospace Regular, this issue is present from geany 1.36...
https://github.com/geany/geany/issues/2353#issue-506073544

**Comment by elextr** [comment] 2019-10-11 22:47
@GFdevelop did you try the workaround noted [above](https://github.com/geany/geany/issues/2287#issuecomment-528815882)?

**Comment by GFdevelop** [comment] 2019-10-11 22:52
@elextr yes, I tried some values:
```
line_height=1;1;
line_height=10;10;
line_height=0;10;
line_height=10;0;
line_height=100;100;
line_height=100;-10;
```
but nothing work...I'm using Monospace Regular from geany v1.2* and only now there is this....

**Comment by elextr** [comment] 2019-10-11 23:00
@GFdevelop also note that Monospace is usually an alias for another font, its not an actual font, so you have to find what its an alias for to find the culprit.

**Comment by bencaradocdavies** [comment] 2020-04-08 02:15
(Copied from https://github.com/geany/geany/issues/2466)

I just got the `line_height` workaround to work with excellent results. The `line_height` setting can be found in "Tools" > "Configuration Files" > "filetypes.common". To change this setting from its default `line_height=0;0;` there are two things to note:

* `#~` lines are commented and have no effect.
* The file format is an [INI file](https://en.wikipedia.org/wiki/INI_file) so uncommenting the `line_height` line is insufficient because the `[styling]` section is also required; either uncomment this line or add a new `[styling]` section at the end.

The only uncommented lines in my filetypes.common are now:

```
[styling]
line_height=0;2;
```

With this setting and DejaVu Sans Mono Book size 12, underscores are visible. Using `line_height=0;1;` also works, but `line_height=0;2;` gives me, for the first time ever, exact agreement (as far as I can tell) with the line height in xfce4-terminal.

**Comment by yothinin** [comment] 2020-05-28 09:07
> (Copied from #2466)
> 
> I just got the `line_height` workaround to work with excellent results. The `line_height` setting can be found in "Tools" > "Configuration Files" > "filetypes.common". To change this setting from its default `line_height=0;0;` there are two things to note:
> 
>     * `#~` lines are commented and have no effect.
> 
>     * The file format is an [INI file](https://en.wikipedia.org/wiki/INI_file) so uncommenting the `line_height` line is insufficient because the `[styling]` section is also required; either uncomment this line or add a new `[styling]` section at the end.
> 
> 
> The only uncommented lines in my filetypes.common are now:
> 
> ```
> [styling]
> line_height=0;2;
> ```
> 
> With this setting and DejaVu Sans Mono Book size 12, underscores are visible. Using `line_height=0;1;` also works, but `line_height=0;2;` gives me, for the first time ever, exact agreement (as far as I can tell) with the line height in xfce4-terminal.

Thank you, it's work!!!
