### ISSUE TITLE
Multiline editing ? (feature request)

### ISSUE THREAD

**Issue by codinghedgehog-python** [geany/geany#2551] opened 2020-07-18 20:22 UTC
The only thing that I really miss in Geany is multiline editing. Can it be implemented anytime soon ? Geany became
my editor to-go and it would be awesome being able to edit multiple lines at the same time.

**Comment by ntrel** [comment] 2020-07-19 10:11
https://www.geany.org/manual/current/index.html#column-mode-editing-rectangular-selections

**Comment by codinghedgehog-python** [comment] 2020-07-20 08:01
I checked that out. Yeah it does work but it's not very useful if the lines you need to edit aren't right on top of each other.
Say, you want to edit every 3rd line. In that case `Search --> Replace` is the only way to do it as of now I guess.

**Comment by elextr** [comment] 2020-07-20 08:20
The version of Scintilla used by Geany (3.5.x) does not support multiple selection, but the next (major 4.x+) version does.  But that needs an upgrade of the minimum compiler version to build Geany.  So until the compiler version requirement is lifted and when whatever changes are made to support a new major version of Scintilla the capability won't be available.

Also as Scintilla is soon to release a new major version it has been decided to wait and skip directly to that.

**Comment by codebrainz** [comment] 2020-07-20 14:51
Duplicate of #1141, #1656, etc.

**Closed by codebrainz** 2020-07-20 14:51 UTC
