### ISSUE TITLE
C:\Program Files (x86)\Geany\Geany.lnk broken, need no-detach mode

### ISSUE THREAD

**Issue by gigadude** [geany/geany#786] opened 2015-12-01 02:23 UTC
The "Start in:" field in the Geanly.lnk should be empty, it's currently set to the install dir and this prevents command-line invocations from opening relative-pathed file arguments correctly.

Also it would be useful for scripting/debug to have a mode where geany stays attached to the launch cmd console (`start "" /B /WAIT "C:\Program Files (x86)\Geany\bin\Geany.exe"` is a possible work-around)

**Comment by codebrainz** [comment] 2015-12-01 02:35
> Also it would be useful for scripting/debug to have a mode where geany stays attached to the launch cmd console

At least for debugging, it when the `-v` verbose option is passed it allocates a new console on which to print debug messages, not useful for scripting though.

**Comment by eht16** [comment] 2016-08-28 17:46
The first part is a duplicate of #1183 and is not a bug, see #1183 for details.

The second part is a new feature, would you mind opening a separate issue for this? Thanks.

**Closed by eht16** 2016-08-28 17:46 UTC
Labels: windows
