### ISSUE TITLE
Compiling problem 

### ISSUE THREAD

**Issue by rafitc** [geany/geany#766] opened 2015-11-21 02:09 UTC
when compiling compilation not occur then in status print this message>>......process failed(the system cannot find the file specified)
why??????????

Windows 8.1 64bit
Geany 1.26

**Comment by codebrainz** [comment] 2015-11-21 02:12
On 2015-11-20 6:09 PM, rafitc wrote:
> when compiling......process failed(the system cannot find the file specified)
> why??????????
>
> Windows 8.1 64bit
> Geany 1.26
>

Most likely the directory your compiler executable is in is not in your 
%PATH% environment variable. You can put it in there, or you can edit 
the build commands (Build->Set Build Commands) and hard-code the 
absolute path to the executable for your compiler (you never mentioned 
what language/compiler you're talking about, so I'm being generic).

Cheers,
Matthew Brush

**Comment by elextr** [comment] 2015-11-21 02:13
On 21 November 2015 at 12:12, Matthew Brush <notifications@github.com>
wrote:

> On 2015-11-20 6:09 PM, rafitc wrote:
> > when compiling......process failed(the system cannot find the file
> specified)
> > why??????????
> >
> > Windows 8.1 64bit
> > Geany 1.26
> >
>
> Most likely the directory your compiler executable is in is not in your
> %PATH% environment variable. You can put it in there, or you can edit
> the build commands (Build->Set Build Commands) and hard-code the
> absolute path to the executable for your compiler (you never mentioned
> what language/compiler you're talking about, so I'm being generic).
>
> Cheers,
> Matthew Brush
>
>
>
​Note also Geany does not include a compiler, you need to install that
separately.

Cheers
Lex​

**Comment by indu97** [comment] 2017-05-30 04:46
On 2015-11-20 6:09 PM, rafitc wrote:

    when compiling......process failed(the system cannot find the file specified)
    why??????????

    Windows 8.1 64bit
    Geany 1.26

Most likely the directory your compiler executable is in is not in your
%PATH% environment variable. You can put it in there, or you can edit
the build commands (Build->Set Build Commands) and hard-code the
absolute path to the executable for your compiler (you never mentioned
what language/compiler you're talking about, so I'm being generic).

Hi, I'm new to geany , and i'm not able to fix the env var. I have the same issue, it says file not found. Can you explain me what you meant by "hard-code the absolute path to the executable for your computer " . I am using C++ and am trying to access raspicam library. This is the file it says 'Not found'. 

Thanks :)

**Comment by elextr** [comment] 2017-05-30 05:59
@indu97 please do not hijack old threads.

Note that the compiler is not part of Geany, so you have to make it work first.

Does the compiler work on the command line?

If not fix that first.

Then use the same command in the build commands in Geany (Menu->Build->Set Build Commands)

**Comment by codebrainz** [comment] 2019-04-03 00:48
Closing since no information is forthcoming in almost 4 years and it cannot be reproduced.

**Closed by codebrainz** 2019-04-03 00:48 UTC
Labels: can't reproduce, waiting for information

**Comment by jrtokyo1992** [comment] 2019-04-23 11:45
> On 2015-11-20 6:09 PM, rafitc wrote:
> 
> > when compiling......process failed(the system cannot find the file specified)
> > why??????????
> > Windows 8.1 64bit
> > Geany 1.26
> 
> Most likely the directory your compiler executable is in is not in your
> %PATH% environment variable. You can put it in there, or you can edit
> the build commands (Build->Set Build Commands) and hard-code the
> absolute path to the executable for your compiler (you never mentioned
> what language/compiler you're talking about, so I'm being generic).

Could you explain more clearly on how to check the current directory and on how to change the path? I have the same problem. Any advice will be appreciated.

**Comment by codebrainz** [comment] 2019-04-23 19:48
This site has good instructions for setting up the `PATH` variable:
https://www.java.com/en/download/help/path.xml

Alternatively just change the [build command](https://www.geany.org/manual/current/index.html#build-menu) so that the command has the full path to the compiler/interpreter executable (ex. `C:\Program Files\YourLanguage\whatever.exe` instead of just `whatever.exe`).
