### ISSUE TITLE
How to hide menu bar without root privileges

### ISSUE THREAD

**Issue by fjvico** [geany/geany#1559] opened 2017-07-26 07:25 UTC
Having root privileges, it's a matter of rewritting `/usr/share/geany/geany.glade` 
`    <object class="GtkHBox" id="hbox_menubar">`
`           <property name="visible">False</property>`
but, is there a way (out of recompiling geany locally) to hide this bar from a non-root user?

**Comment by codebrainz** [comment] 2017-07-26 08:04
There is a plugin to do this linked in the comments on the issue this is a duplicate of: https://github.com/geany/geany/issues/633

**Comment by fjvico** [comment] 2017-07-26 08:18
Totally, @codebrainz, the solution I've been looking for. Thx!!

**Comment by LarsGit223** [comment] 2018-03-17 12:16
IMHO this can be closed.

**Closed** 2018-03-17 14:52 UTC
