### ISSUE TITLE
Geany edit window has a vertical green line across the code at column 

### ISSUE THREAD

**Issue by hlech65730** [geany/geany#2396] opened 2019-11-13 07:33 UTC
Hello @all,
in my Geany ( V 1.35 , Win10, GTK 2.0 ) edit window a vertical green line over the code at column 46 is shown. I don´t know what this line is for and how i can delete it ?
Thanks for an answer ! 
Regards, Hlech65730

**Comment by codebrainz** [comment] 2019-11-13 08:52
Sounds like a duplicate of #1779

**Closed** 2020-08-03 06:39 UTC
Labels: question
