### ISSUE TITLE
`sidebar.c` symbols truncated

### ISSUE THREAD

**Issue by elextr** [geany/geany#2916] opened 2021-10-07 07:38 UTC
Only a few of the symbols for the file `sidebar.c` show up in the symbols pane.  This is due to the lines [here](https://github.com/geany/geany/blob/5b307bc05dbb055a06dc83c1d749ffab46e259e4/src/sidebar.c#L203) within a comment inside a macro not being backslashed confusing ctags.  

Because cpp removes comments before preprocessing its not a problem for the compiler, cpp never sees the comment and the macro is whole, but ctags gets confused and gives up.

Should we just add the backslashes as a workaround.  And is it worth reporting since we don't use the ctags "new C/C++" parser?

**Comment by techee** [comment] 2021-12-06 15:50
This is basically a duplicate of #2349 and will be fixed by the new cxx parser.

**Closed** 2021-12-19 00:04 UTC
