### ISSUE TITLE
Geany 1.34.1 on MAC OS Catalina

### ISSUE THREAD

**Issue by ochampal** [geany/geany#2397] opened 2019-11-13 10:07 UTC
Following the Mac OS Catalina update, Geany can't no more acces my "document" file : "Operation not permitted"

**Comment by elextr** [comment] 2019-11-13 11:31
Looks duplicate of #2344

**Comment by techee** [comment] 2021-11-10 16:13
This was fixed quite some time ago. Closing.

**Closed by techee** 2021-11-10 16:13 UTC
