### ISSUE TITLE
[home] or [end] key not working on vertical split screen

### ISSUE THREAD

**Issue by RedCarpet** [geany/geany#1901] opened 2018-07-22 14:23 UTC
On a vertical split screen the [home] or [end] key does not go to the start or end of the line of text. 
[shift] + [home] and [shift] + [end] **DOES** work but plain [home] or [end] key does not.

On the left hand side vertical split screen the [home] or [end] key works fine and goes to the start or end of text. Yet if you select the focus of the right screen (with mouse click) then the [home] or [end] keys do not work on their own, the cursor remains stationary.
_Hope this helps
pj_

geany 1.33 (built on 2018-04-17 with GTK 3.10.8, GLib 2.40.2)
[geanytext.txt](https://github.com/geany/geany/files/2217075/geanytext.txt)

Release Linux Mint 17.3 Rosa 64-bit
Kernel Linux 3.19.0-32-generic x86_64
MATE 1.12.0

**Comment by GladOSkar** [comment] 2018-07-22 15:51
Duplicate of #604 and others

**Comment by elextr** [comment] 2018-07-22 22:38
closed as duplicate

**Closed by elextr** 2018-07-22 22:38 UTC
Labels: duplicate
