### ISSUE TITLE
Many tabs in "message window" not available on win OS

### ISSUE THREAD

**Issue by yashpalgoyal1304** [geany/geany#3145] opened 2022-04-02 12:36 UTC
### Summary
Terminal button not available in message window in geany on Windows OS

### Details
* I am only seeing 4 tabs/buttons in the message window : 
    * Status, Compiler, Messages, Scribble
* But i saw in a video online showing geany in linux that it had 5 tabs:
    * Status, Compiler, Messages, Scribble, Terminal
* Same goes for the tabs in settings
    
So, i think that on windows, the inbuilt terminal is not available

### Screenshots

<details>

![image](https://user-images.githubusercontent.com/19423063/161385816-265e7248-9b4b-4fd0-93e3-d79c1d48e7cd.png)

![image](https://user-images.githubusercontent.com/19423063/161385836-37f43a12-e0f0-47c5-9901-2476e2f72148.png)

![image](https://user-images.githubusercontent.com/19423063/161388725-dca1bbce-86d6-4b1a-b920-0a843c83c6a4.png)

</details>

### Environment:
* Geany: 1.38 "Sulamar"
* GTK+: dont know `geany -V` didnt work
* OS: WIndows 10
* Filetype: not applicable i think, tried with .tex and .c

(details asked at: https://www.geany.org/support/bugs/ )

|   | normal ones | MSYS2 |
| -- | -- | -- |
| terminal | wezterm, conhost | mintty |
| shell | cmd, PowerShell, git-bash | bash |

<details>
<summary>
Old description
</summary>

* how to use terminal in geany? 
while the build button is super nice to have, there still are occassions when i want to manually enter the commands (both for build and non-build tasks). I was dealing with .tex files and didn't see any way to launch any terminal widget

</details>

**Comment by yashpalgoyal1304** [comment] 2022-04-02 14:47
watching online videos, and so far i have seen following number of people:

2

**Comment by yashpalgoyal1304** [comment] 2022-04-02 15:43
Update:

i saw a screenshot online, and it shows even more tabs like : 
* Tasks
* Markdown preview
* Web preview

i am not shown any of those, like i tried with markdown file, and i was not shown markdown preview button. so :(

![image](https://user-images.githubusercontent.com/19423063/161390606-b9fe4e13-3e11-4592-a72c-ca2990a036c5.png)

**Comment by elextr** [comment] 2022-04-02 23:25
> Terminal button not available in message window in geany on Windows OS

Duplicate of at least #675, to summarise "The terminal widget Geany uses on Linux is not available on Windows and nobody has implemented any alternative solution".

The other tabs are from plugins, they show if you enable the relevant plugin, see `Tools->Plugin Manager`.

PS Thank you for trying to provide version and system information, for simplicity `Help->Debug Messages` provides it all in the top few lines.

**Closed by elextr** 2022-04-02 23:25 UTC
Labels: existing capability, duplicate

**Comment by eht16** [comment] 2022-04-03 12:08
A few more details:
- the "Terminal" tab, as @elextr said, is not available on Windows
- the "Tasks" tab is part of the "Addons" plugin, installable via the Geany-Plugins, available on https://www.geany.org/download/releases/
- the tabs "Markdown preview" and "Web preview" are part of the "Markdown" und "Web Helper" plugins which are not available on Windows, see the release announcement at https://www.geany.org/news/geany-plugins-138-are-out/ for details.
