### ISSUE TITLE
Double title bar

### ISSUE THREAD

**Issue by nimdanor** [geany/geany#1729] opened 2017-12-24 10:58 UTC
![capturegeanyprob](https://user-images.githubusercontent.com/10084549/34325941-7c8b5354-e8a1-11e7-84a0-840018023fb6.jpeg)

I have this on my mac for several days.
I uninstalled geany, tried 1.31 , searched throught  the preference,
it's impossible to work with this because mouse if off by one title bar height.

**Comment by elextr** [comment] 2018-01-29 02:40
@techee ping

**Comment by techee** [comment] 2018-01-29 14:06
In my opinion it's not a title bar but rather a tab created by macOS. I believe we already had something like that reported elsewhere (not sure if it was mailing list or bug report, can't find it now) where macOS adds an extra tab when

System Preferences->Dock->Prefer tabs when opening documents

is set to "Always". Geany is not a native macOS application and unfortunately doesn't have a control over this extra tab.

**Comment by nimdanor** [comment] 2018-01-29 16:59
I tried every position of :  preference->dock-> prefer tabs always/never/manually.
did have any effect allways the double bar.

You can see in the image that those bar are different , size and style of font.

**Comment by techee** [comment] 2018-01-29 21:31
@codebrainz Do you remember the extra tab bar issue? I believe you found some way to hide it - I just can't find the bug report anywhere in the mailing list or the bug tracker.

@nimdanor If it's a Geany issue, it could be some strange settings store in the config file. You could try renaming ~/.config/geany/geany.conf to something else (while Geany is not running) and start Geany which will then create a default config file.

**Comment by codebrainz** [comment] 2018-01-30 02:21
@techee that doesn't ring a bell at all.

**Comment by codebrainz** [comment] 2018-01-30 02:29
@techee you could try to hard-code it off like [Chromium did](https://chromium.googlesource.com/chromium/src/+/5788338a8a54e230ef868e66c4ab309bb76dfd65%5E%21/#F1)

**Comment by nimdanor** [comment] 2018-01-30 11:22
@techee have try to dump the geany config didn't work for me.
(i have checked just now to be sure didn't change any thing).

**Comment by techee** [comment] 2018-01-30 22:22
I finally found the bug report which I thought was related:

https://github.com/geany/geany/issues/1428

There's a window with one tab with Geany editor and one with the Preferences window created by Mac OS. And in this bug report I think there's just the editor tab displayed by Mac OS for some reason. 

(And the Mac OS expert in the bug report wasn't @codebrainz but @elextr ;-)

@codebrainz The problem is that it involves Objective-C which we don't use in the code at the moment and from what I remember Colomban wasn't very keen of using it (which then complicates build settings and requires linking objective-c runtime).

@nimdanor Yeah, I suspected that, I think it's really a tab. Isn't it possible to close it? There might appear a close button when you move the mouse to the left of the second "title bar".

**Comment by codebrainz** [comment] 2018-01-31 01:11
> The problem is that it involves Objective-C which we don't use in the code at the moment...

I believe you can call Objective-C methods from C, using [the runtime](https://developer.apple.com/documentation/objectivec/objective_c_runtime).

> ...which then complicates build settings and requires linking objective-c runtime

Yeah, though I'm sure Geany is already indirectly linked to the Objective-C via GTK+. It's basically just adding a `-framework` flag conditionally for Macos to the build script or whatever.

**Comment by elextr** [comment] 2018-01-31 01:22
> The problem is that it involves Objective-C which we don't use in the code at the moment and from what I remember Colomban wasn't very keen of using it (which then complicates build settings and requires linking objective-c runtime).

Its not nice having lots of foreign language stuff in `#ifdef` everywhere, can it be in a separate file like Scintilla "platform" stuff?

> (which then complicates build settings and requires linking objective-c runtime).

meson FTW!!! `</troll b4n>` :)

**Comment by techee** [comment] 2018-01-31 13:26
In any case, before writing some platform-specific code we should understand the problem - I have no idea how to reproduce this particular issue and have never seen it myself.

**Comment by techee** [comment] 2018-02-01 14:18
If we want to add some platform-specific code, we could also add it to the gtk-mac-integration library. Under normal conditions such a fix could be applied upstream but with the gtk-osx maintainer's attitude:

https://bugzilla.gnome.org/show_bug.cgi?id=793015

I'm not going to do that and we'd have to use a patched version of gtk-mac-integration. We already have to patch it anyway by

https://github.com/geany/geany-osx/blob/master/patches/01-gtk_mac_integration_radio_fix.patch

because the gtk-osx project maintainer refuses to accept there's a problem in the library and rejects submitted patches:

https://bugzilla.gnome.org/show_bug.cgi?id=744596

(When I reported the problem, he closed the bug report saying the problem doesn't exist. When I re-opened the bug and added more details, he closed it again saying we're doing it wrong. Then I re-opened it again because what we are doing is completely legal code after which he rejected the patches. The guy is a joy to work with.)

So since we are patching the library anyway, we can add more patches there and do a similar thing like Chromium. Still it would be good to know first how to reproduce the problem and see if such a patch helps.

**Comment by JanAxelsson** [comment] 2018-08-20 12:28
Long-time user here!

This is still an issue!  It is not a tab, but seems to be an extra title bar.  This effectively makes Geany unusable, because the extra resizing of a window before doing anything becomes unbearable.  I can confirm this behaviour, looking exactly as the screen shot above on High Sierra and Geany 1.33.  

Please indicate if you have this problem.  Also make yourself heard if you do not have this problem which would indicate that there is something user-dependent that can crop up.

**Comment by JanAxelsson** [comment] 2018-08-20 12:37
Reading the sad links above; let me just say how much I appreciate your work on Geany.  Hope my message above did not come out too terse, or worse...  I would be glad to help you isolate the problem if I can.  I am subscribing to this issue so I will notice updates

**Comment by nimdanor** [comment] 2018-08-20 18:52
Lovely (not to terse at all)
I was a geany addict and was conseling it's use to me 500 new students each
year  until this stupid extra title bar  that renders the software useless
on my mac.
The problem now is this mac can't connect any more to internet so until i
repare the mother board in september i will not be able to change much on
it.
So if what you ask can be done witha little typing: throw away.
Cheers


Le lun. 20 août 2018 à 14:37, JanAxelsson <notifications@github.com> a
écrit :

**Comment by JanAxelsson** [comment] 2018-08-21 07:42
Some more info:

On a mac which never had Geany on it, it works as expected.  It did initially work as expected on my mac.

It seems as if at some time point, Geany goes nuts, and the extra title bar comes up.

Could it be that Geany is using some global settings, that are affected by another software?  
Is Geany for instance reading some global GTK settings?  If so, that could be fixed?

**Comment by JanAxelsson** [comment] 2018-08-21 21:21
A fresh user-account runs Geany fine. On the same mac as the bad account  

On the bad account, I have tried to look in $HOME/.config and removed everything related to geany and gtk, but it does not help.  Still opens geany with OSX's own title bar, and the GTK titlebar inside the window (as in figure above in this thread).

This means that there is something very account-specific which I can't isolate.  

I know this may not be Geany's fault, but it is still frustrating, and I would really appreciate if somebody gave me some hints.  If the problem is understood, I do trust that this could be used towards Geany becoming robust against such problems in the future

**Comment by JanAxelsson** [comment] 2018-08-25 09:59
Problem solved!

My theory is that HomeBrew gtk installations interferred.  After executing:
```
  brew remove gtk+
  brew remove gtk-engines
```
the double title bars went away.

Sorry if I have created any confusion

**Comment by nimdanor** [comment] 2018-08-26 09:54
1) with another account no problems
2) 
brew remove gtk+ ---> ok 
brew remove gtk-engines ---> No such Keg

restart geany ---> two title bars

**Comment by JanAxelsson** [comment] 2018-08-27 08:30
I also tried to remove things related to other package managers, such as Macports or Fink.  It turned out I had none of these installed.  I also logged in and out in this process, so I am not sure if that helped too.

One thing I noted is that macports had added things in the `.bash_profile ` setting of the `PATH`.  Maybe worth checking your path: `echo $PATH` in the terminal?

Hope any of this could help, otherwise I have run out of ideas to help you.  Good luck!

**Comment by techee** [comment] 2018-08-29 13:32
If anyone is interested, I wrote a summary of what might be the workarounds of this issue here:

https://github.com/geany/geany/issues/1371#issuecomment-416954072

**Comment by phillc54** [comment] 2018-08-30 02:34
View->Hide Tab Bar works for me, THANK YOU...

**Comment by nimdanor** [comment] 2018-09-10 07:26
@techee trying but my geany is in french and i can't find the menu and menu item you are referring  to.

**Comment by techee** [comment] 2018-09-10 08:34
@nimdanor It should be at the top of the very top of the View menu:

<img width="724" alt="screen shot 2018-09-10 at 10 29 18" src="https://user-images.githubusercontent.com/713965/45286029-faea4380-b4e4-11e8-8e25-e7b10acc7f07.png">

**Comment by b4n** [comment] 2018-09-10 15:54
@nimdanor With @techee's screenshot you should have got the right menu already, but FTR the "View" menu is "Affichage" in French.

**Comment by nimdanor** [comment] 2018-09-11 17:26
The 'affichage' menu starts with change font ... there is no tab related
item.
@techee you said something about removing GTK ?

**Comment by techee** [comment] 2018-09-11 21:19
Oh, wow, you are right, I've just checked the Czech locale and there isn't this item either. But you can disable Geany localization by creating a file called `ignore_locale` under `~/.config/geany`. This

```
touch ~/.config/geany/ignore_locale
```

executed in the terminal should create it for you. If you run Geany then, it will be in English and you should see the options.

**Comment by nimdanor** [comment] 2018-09-12 17:08
YES !!!!
Removed the ignore_locale to go back to french  and every thing ok.
Thanks to all.
But the bugs is not really found .... should stay open.

**Comment by techee** [comment] 2020-03-22 13:21
I believe this issue is fixed in the latest release based on GTK 3. Feel free to reopen this issue if you still experience the problem.

**Closed by techee** 2020-03-22 13:21 UTC
Labels: macos
