### ISSUE TITLE
Javascript syntax highlight

### ISSUE THREAD

**Issue by CupIvan** [geany/geany#2539] opened 2020-06-30 20:49 UTC
does not highlight multiline ES6 strings with symbol ` in *.php, instead of color like default quoted strings (',")
![screen_2020-06-30_23:47:55](https://user-images.githubusercontent.com/217988/86175527-2b70f680-bb2c-11ea-9de4-9435ff57ad57.png)

**Comment by codebrainz** [comment] 2020-07-01 18:25
Thanks for the report. I believe this is a duplicate of #1984, which needs to be implemented [upstream in Scintilla](https://sourceforge.net/p/scintilla/feature-requests/1112/) before it will work in Geany.

**Closed by codebrainz** 2020-07-01 18:25 UTC
