### ISSUE TITLE
Search for selected text when pressing [Ctrl]+[F]

### ISSUE THREAD

**Issue by etkaar** [geany/geany#2693] opened 2020-12-17 18:51 UTC
It would be nice if the selected text would be inserted into the "Search for:" input when pressing [Ctrl]+[F]. I know this behaviour from Notepad++ and it is very helpful.

**Comment by elextr** [comment] 2020-12-17 20:16
Duplicate of #758 (or at least one of the suggestions, its a big and confusing discussion) but nobody has made a PR.

Although its a duplicate perhaps better to leave this open due to the complexity (and age) of #758.

**Comment by etkaar** [comment] 2020-12-18 08:26
I noticed that the default behaviour of Geany is to put the selected text into the "Search for:" as long the search dialog is not opened.  If you open it using [Ctrl]+[F] or via the menu does not matter.

Since the feature is already implemented I think it should be a little bit easier to just add an option such like "Always search for selected text".

**Comment by elextr** [comment] 2020-12-18 08:43
> Since the feature is already implemented I think it should be a little bit easier to just add an option such like "Always search for selected text".

Well, thats the whole point of the loooong discussion on #758, changing the search string every time something is selected limits what editing actions can be used between searches (they have to _NOT_ select anything or you lose the search string), but if its an option on the search dialog it should be ok.

Since it already loads the selection on opening the dialog, if CTRL+F (or whatever is configured as the keybinding for search) while the dialog is is already open, loads a new search from selection without closing and re-opening, thats also an acceptable enhancement IMNSHO.

Pull requests are welcome (and don't forget to document in the manual).

**Comment by etkaar** [comment] 2020-12-20 22:00
I created a pull request now, see #2695. Is it okay if I do another PL for the manual later?

**Comment by etkaar** [comment] 2020-12-21 09:19
Closed because of pending Pull Request: #2697

**Comment by elextr** [comment] 2020-12-21 09:25
Don't close until the PR is merged, see [github docs](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for how to make it happen automatically when the merge happens.

**Closed** 2020-12-28 20:32 UTC
