### ISSUE TITLE
Missing lines in 4-pages-on-1 print

### ISSUE THREAD

**Issue by ghost** [geany/geany#1040] opened 2016-05-20 08:35 UTC
Geany 1.25, Ubuntu 15.10:
When printing 4 pages on a single page some text lines are missing. 
Printing 2,6 and 9 pages on one looks OK, the problem comes with 4 and 16. 
In the attached image, lines from 61 to 64 and 119 to 122 are missing. 
It is not an error with line numbers but code is actually missing too.

![screenshot from 2016-05-20 10-27-15](https://cloud.githubusercontent.com/assets/13032051/15421974/450470ec-1e76-11e6-8bca-b7020af6c2b0.png)

**Comment by LarsGit223** [comment] 2018-03-15 17:43
Duplicate of #325.

**Closed** 2018-03-15 21:57 UTC
Labels: duplicate
