### ISSUE TITLE
Notepad versus Geany (on Windows): Notepad wins

### ISSUE THREAD

**Issue by rubyFeedback** [geany/geany#2804] opened 2021-05-03 23:23 UTC
Hey folks,

Sorry to pick such an eye-catching title. ;)

I compiled an .exe today on windows, via msys2.

I never managed to do so before; I am a linux guy really.

Anyway, I wanted to find out whether it was 32bit or 64bit. How retarded windows is!!! You
can't easily find it out (ok you can, but you may need to install a SDK or something).

Anyway. One solution was to look at the content after the PE string. 

At first I tried to use geany there, but geany whined:

"The file "C:\aragorn.exe" does not look like a text file or the file encoding is not supported".

Notepad.exe on the other hand showed the file content. And I saw the PE identifier and
since I was on stackoverflow, I now knew that it was 64 bit.

So please, anyone with commit rights, could this be changed on geany? A notification is
ok, or perhaps a "do you want to open the file nonetheless"? Or, the simplest, to just
open it as-is, like notepad does.

As long as this is not possible, notepad wins. (Perhaps there are options to configure, but
I think this is where notepad.exe has better defaults and perhaps also notepad++.exe).

TL;TD: Geany should not refuse to open a file arbitrarily so. The user should decide
at his or her own discretion.

**Comment by elextr** [comment] 2021-05-03 23:35
Duplicate of #618 #1508 #1708 #2081 #2654

Geany will not load a binary file, thats why you got the message.  Geany is C, in C a zero byte indicates the end of a string, so most functionality will only see the contents up to the first zero byte, and binaries are littered with zero bytes.  So no it can't be "enabled" without major work.

Notepad++ is C++ where strings can contain zero bytes, so its "easy" for it to use binaries.

And nobody is in competition, so nobody "wins" just different projects have different capabilities.

**Closed by elextr** 2021-05-03 23:35 UTC
