### ISSUE TITLE
Copy/Paste in Fedora 37

### ISSUE THREAD

**Issue by jerryd** [geany/geany#3363] opened 2023-01-01 05:10 UTC
It appears that coppying from geany out to for example gnome-terminal does not work.  It is probably a Fedora 37 gnome desktop related issue. I though I better post here so you good folksare aware.

**Comment by jerryd** [comment] 2023-01-01 05:17
It is reported on the redhat bugzilla and is a wayland issue.  aka upstream.

**Comment by elextr** [comment] 2023-01-01 05:48
duplicate of #3345

**Closed by elextr** 2023-01-01 05:48 UTC
