### ISSUE TITLE
Colorscheme setting for printing

### ISSUE THREAD

**Issue by kadarmarton** [geany/geany#2754] opened 2021-02-21 11:35 UTC
I like a dark color scheme for editing, but
I want to print the text black on white.
I find myself switching to a B/W colorscheme just for printing
and then switching back to the usual dark editing scheme.

My suggestion is a configuration item that is a colorscheme name, and when set, it would be used for printing.

**Comment by elextr** [comment] 2021-02-21 22:35
Duplicate of #617 #894 #1791 #2023

And I'm sure some of them mention the colour scheme idea.

**Closed by elextr** 2021-02-21 22:35 UTC
