### ISSUE TITLE
Geany find edit box "hangs" on Fedora 24

### ISSUE THREAD

**Issue by brianread108** [geany/geany#1101] opened 2016-06-30 13:14 UTC
I've just upgraded from Fedora 23 to 24. Geany (version 1.27) now hangs in the find box (with a blue ring around it) after one or two successful finds. The rest of the app seems to work ok, but I am then unable to type into the find box.  Solution is to close down Geany and re-start.  Works then for a while. Seems to be rwalted to the "incremental" search aspect of the Find function - if I leave the typing and then return to it in a second or so it hangs, but if I type the whole string in straight away it seems to work. Perhaps a short timeout?

**Comment by codebrainz** [comment] 2016-06-30 14:50
I guess you are referring to the search entry on the toolbar as opposed to the one in the separate Search dialog? You could try and reproduce with the Search dialog entry, it has a lot of the same features (style hacks to show no matches, incremental searching, etc).

Can you paste terminal output when run with `geany -v` after it locks up? It will show the needed GTK+ info and possibly some "assertions" firing.

**Comment by brianread108** [comment] 2016-06-30 16:56
Yes I do mean the toolbar find (I use it ALL the time!).
However it also locks up on Search Dialog entry.

When I run geany -v  and it locks up I am not seeing any unexpected messages, here is the startup:

Geany-INFO: Geany 1.27, en_GB.utf8
Geany-INFO: GTK 2.24.30, GLib 2.48.1
Geany-INFO: System data dir: /usr/share/geany
Geany-INFO: User config dir: /home/brianr/.config/geany
Geany-INFO: System plugin path: /usr/lib64/geany
Geany-INFO: Added filetype Scala (61).
Geany-INFO: Added filetype Clojure (62).
Geany-INFO: Added filetype CUDA (63).
Geany-INFO: Added filetype Cython (64).
Geany-INFO: Added filetype Genie (65).
Geany-INFO: Added filetype Graphviz (66).
Geany-INFO: Added filetype JSON (67).
Geany-INFO: Loaded:   /usr/lib64/geany/geanyvc.so (GeanyVC)
... cut (load details for the active files)

**Comment by codebrainz** [comment] 2016-06-30 18:53
I only have two ideas to try and find the problem, one is to run geany with the `-p` option to disable plugins (or even with `-c /tmp/somewhere/fleeting` to use a whole fresh config with no plugins loaded), the other is to try and switch your GTK+ theme (say to one of the boring stock ones like Raleigh or Redmond or such).

**Comment by brianread108** [comment] 2016-07-01 06:16
geany -p makes no difference.

I've not idea how to switch the GTK+ theme - unless it is through Cinnamon? ( I forgot to say that I am using the Fedora Cinnamon spin)

**Comment by brianread108** [comment] 2016-07-05 06:08
It happens as soon as the search fails to find the pattern.

**Comment by elextr** [comment] 2016-07-05 06:41
When a search fails the entry box changes colour.  You might have to look at how thats done and if its in some way incompatible with a GTK version Fedora provides.

**Comment by b4n** [comment] 2016-07-05 11:48
I found yesterday that the search entry field fails if you have a rectangular selection.  Canceling the rectangular selection fixes it.
Is it your problem, or unrelated?

**Comment by brianread108** [comment] 2016-07-12 19:19
any news on this? - i use geany all the time under Fedora (24) and having to close and open the editor whenever I try a search that fails to fond anything is somewhat testing my patience! (I love geany though).

**Comment by codebrainz** [comment] 2016-07-12 19:41
@brianread108 did you try changing themes to see if that helps (according to Google; `Cinnamon Settings->Appearance` is where you change it)? Also does it only affect you when using a rectangular/block selection as @b4n mentioned?

**Comment by brianread108** [comment] 2016-07-12 20:52
Switched theme for windows and desktop (Was Nightfall/Crystal) no change - still fails.

No idea what you mean by the rectangular/block selection  - I am not selecting anything except typing in the search characters.

The search dialog (CTRL-F) fails in the same way.

**Comment by elextr** [comment] 2016-07-13 04:28
@brianread108 the problem is that none of the Geany devs use Fedora AFAIK, and (other than the situation noted by @b4n) it seems to work on the other distros we use.

What versions of GTK and Glib is it using (see a line near the top of the `help->debug messages` window) and what desktop are you using?

**Comment by f2404** [comment] 2016-07-13 09:03
I think I'm having the same issue on Arch Linux - the text I'm searching for sometimes becomes invisible in the search dialog. I can see that it's there if I select it (switch to the input field and press Ctrl+A); otherwise I'm only seeing blank field.

geany is 1.28 (built against gtk2); gtk2 is 2.24.30; gtk3 is 3.20.6; glib is 2.48.1.

**Comment by elextr** [comment] 2016-07-13 09:45
@f2404 not sure its the same, the OP is not that the search field is disappearing, just that it is not working.  Maybe you should open another issue, if we find its the same we can close both :)

**Comment by elextr** [comment] 2016-07-13 09:47
Other than the issue noted by @b4n search dialog works for me on Mint cinnamon 3.06 gtk2 build GTK 2.24.30, GLib 2.48.1 and gtk3 build GTK 3.18.9, GLib 2.48.1.

**Comment by f2404** [comment] 2016-07-13 09:54
@elextr Thanks, created another one.

**Comment by dmaphy** [comment] 2016-07-13 15:21
@brianread108 The update for Geany 1.28 is already available for Fedora 24 and went quite smooth as far as I could see. Probably it is an option for you to check if the issue is still present with 1.28?

**Comment by brianread108** [comment] 2016-07-14 13:56
I'm on 1.28 already - issue still extant.

This is the GTK version:

Geany-INFO: GTK 2.24.30, GLib 2.48.1

**Comment by brianread108** [comment] 2016-07-14 13:58
Also - the post above - the search string does dissapear, so these issues might be related  Switching the the edit box and CTRL-A shows it, but the search is hung at that point.

**Comment by b4n** [comment] 2016-07-14 15:17
@brianread108 can you please try #1137?  I somehow doubt it will really help if it's not merely that you don't see the content of the entry (#1135), but well, who knows.

**Comment by brianread108** [comment] 2016-07-14 17:00
@b4n Sorry but I've no idea how to apply those fixes - is there somewhere that will help me?

**Comment by b4n** [comment] 2016-07-14 17:03
Actually you can even do it manually quite easily, just replace */usr/share/geany/geany.gtkrc* with https://raw.githubusercontent.com/b4n/geany/13a9600ad7fad421497310d1572337ce88b5162f/data/geany.gtkrc and restart Geany.  Yes this suggests you to replace a system data file, but that's the easiest solution given you installed Geany via your favorite package manager.

**Comment by brianread108** [comment] 2016-07-14 17:41
Well, that fixed it! Many thanks.

**Comment by b4n** [comment] 2016-07-14 17:44
Great :)

But it suggests that the problem you've been having was only that you didn't see some text in the field when it didn't match, and so trying to add more character to the blank field worked (but still weren't visible), but appended to the already non-matching string.

**Comment by brianread108** [comment] 2016-07-15 16:39
I am pretty sure it "hung" - I could do CTRL-A to see the text, but delelting it did not get the functionality back.

**Comment by brianread108** [comment] 2016-07-15 16:40
How do I mark this as resolved?

**Comment by elextr** [comment] 2016-07-15 23:43
Just close it (done for you)

**Comment by elextr** [comment] 2016-07-16 00:38
Actually since there is a fix to be applied, should leave it open and the fix will autoclose it :)

**Closed** 2016-07-16 01:38 UTC
