### ISSUE TITLE
Hard to distinguish between warnings and errors on compilers results

### ISSUE THREAD

**Issue by medeotl** [geany/geany#1795] opened 2018-03-07 08:14 UTC
geany 1.32 (built on 2018-01-28 with GTK 3.22.26, GLib 2.54.3)
tested on fedora 27 with vala

When I compile, I have to carefully read the compile result to understand if compilation went perfect well, well with warnings or totally failed.
Reason: 
- errors and warnings have the same (red) colour  in result
- "compilation failed" and "compilation finished successfully" have the same (blue) colour in result
- sound of compilation failed| finished successfully is the same (bling!)

![screenshot from 2018-03-07 09-04-50](https://user-images.githubusercontent.com/1864684/37080870-e436461a-21e7-11e8-9c1f-4bf485d2b38f.png)
![screenshot from 2018-03-07 09-05-14](https://user-images.githubusercontent.com/1864684/37080871-e466ec20-21e7-11e8-9758-535b3c3e041b.png)

**Comment by elextr** [comment] 2018-03-07 08:29
Closed as duplicate of #447 which is being addressed by PR #1649

**Closed by elextr** 2018-03-07 08:29 UTC
