### ISSUE TITLE
Geany doesn't switch to newly opened document when restoring previously opened files

### ISSUE THREAD

**Issue by xiota** [geany/geany#3210] opened 2022-05-24 05:27 UTC
When "load files from the last session" is enabled, regardless of whether a project is loaded, the previously active document is reactivated when Geany is closed and restarted with a document at the command line or from a file manager.  The expected behavior is to activate the newly opened document for editing.  When Geany is open in the background, it switches to the new document, as expected.

This occurs with the default config and no plugins loaded.  Does not occur in an old build from 2021-12-30.  Does occur in builds dated after 2022-05-01.  I did not build Geany between those dates, so don't know when the new behavior was introduced.  I do not see it in the manual, nor do I see any option to revert to the old behavior.

To reproduce:

1. Open Geany.
2. Open several documents.
3. Close Geany.
4. Open Geany with a file from a file manager or command line.
5. Geany will open and activate the last active document.  Expected behavior is to activate the newly opened document for editing.

**Comment by elextr** [comment] 2022-05-24 05:54
Nor is the old behaviour actually specified, but makes sense.  @kugel- is this a side effect of the session split changes?

**Comment by kugel-** [comment] 2022-05-28 19:17
Caused by #3125 where I changed the "switch to last active document from session" to a `g_idle_add()` mechanism, and that's now run after command line files are opened.

**Comment by elextr** [comment] 2022-05-28 23:13
Guess it should just select to switch to last document from session or last CL file opened if there are any.

**Comment by ralf3u** [comment] 2022-06-08 11:32
I would like to give a feedback to the code mentioned above. This is what I did:
Because in `~/.local/` there was no folder `bin`, I created a folder `bin`. In that folder `bin`, I created a document with the name `geany`, with the code mentioned above as content. In `/usr/bin/` I looked for a document with the name `geany`, just to check if the path of `GEANY_EXEC="/usr/bin/geany"` is correct. Then I did in the terminal `sudo chmod +x ~/.local/bin/geany` to make the script executable. In the script `geany` that is located in `~/.local/bin/`, I changed `DELAY=0.5` from `0.5` to `0.6`, because the used computer is not so fast. Then I saved the document. The script works perfect for me.

**Comment by kugel-** [comment] 2022-06-08 21:02
I intend to restore the old behavior but it's not as simple as it seems, sorry, may take a while.

**Comment by xiota** [comment] 2022-06-08 23:15
@kugel-  I wasn't sure if it was intentional because no one had previously stated otherwise.    Since there's a workaround and it took 3-4 months for anyone to even notice the change, there doesn't seem to be much need to hurry.

**Comment by kugel-** [comment] 2022-06-09 09:29
Well most users don't use Geany from the master branch but the last release. So I think 3-4 months vs a few days doesn't mean much.

**Comment by ralf3u** [comment] 2022-08-24 20:15
It would be good if this issue will be fixed before Geany 1.39 will be released.

**Closed** 2023-07-18 06:03 UTC
Labels: regression
