### ISSUE TITLE
Mouse pointer reversed on left side

### ISSUE THREAD

**Issue by copywrong** [geany/geany#1412] opened 2017-02-26 15:48 UTC
In Geany 1.29, mouse pointer is reversed when hovering the left side of the window. This issue is independent of any theme in Xfce 4.12.1.
![mouse pointer](https://cloud.githubusercontent.com/assets/6815768/23341172/6d56458c-fc3a-11e6-869a-01f033e38c64.gif)
(.gif quality isn't the best, but you can see the mouse pointer changing)

**Comment by elextr** [comment] 2017-02-26 16:13
The reversed cursor is normal behaviour when it is over the editing margins.

The bar on the left is the folding margin, where folding symbols appear and can't be turned off.

**Comment by codebrainz** [comment] 2017-02-26 19:15
It could be changed, Geany just uses the default behaviour, see:

http://www.scintilla.org/ScintillaDoc.html#SCI_SETMARGINCURSORN

**Comment by kugel-** [comment] 2017-03-07 15:48
I suggest closing this since this is apparently the expected behavior.

**Comment by elextr** [comment] 2017-03-08 00:58
Agree.

**Closed by elextr** 2017-03-08 00:58 UTC
