### ISSUE TITLE
Need c++ source code autocomplete for custom class members/functions 

### ISSUE THREAD

**Issue by andysendo** [geany/geany#1824] opened 2018-04-11 10:11 UTC
Hi, i recently use geany for my c++ & java project, it's almost like a IDE for my requirments (edit, compile, debug).

for java source edit, custom class members/functions autocomplete is worked sometimes.
for c++ source edit, but custom class members/functions autocomplete not work at all. 

actually geany already have enough symbols information for an opened c++/java project, because the symbols view can show up members/functions for the opened file, ctrl+left-click member will jump/open declaration of the header file. why not do more work for autocomplete? 

(i tried geany-plugin-ctags, it's not what i need)
 
debian9 stable, geany 1.29.

Regards.

**Comment by elextr** [comment] 2018-04-11 12:09
I am not sure which particular autocomplete situation you are having problems with.

If the names are in the symbols pane of an _open file_ of the same language they should appear for autocompletion if you type the first few characters (how many is settable in preferences, default 4).

Is that the problem you are describing, or is it that many names do not show up in symbols.  The ctags system used to get the symbols can only handle named scopes, not lexical scopes, so it does not parse local definitions, so those names will not show in symbols.

**Comment by andysendo** [comment] 2018-04-11 15:50
let me make c++ project with 2 example files to  explain:
test.hpp:  define a class named Test with public method named test_func(parms...)
test.cpp:  impelement method  Test::test_func(parms...)

in test.cpp write the main fucntion as:
int main(int argc, char** argv)
{
    Test t1;   Test *t2
    t1.
    t2->
}

symbols view will show up the member test_func, ctrl+left-click will jump to the hpp definition, that's fine, and it means geany already collect enough symbols/tags.

i wish when i typing "t1." or "t2->" autocomplete will show up the member symbol "test_func(parms...)" no need to type "t1.test" or "t2->test", this feature is very common for c++ ide editors(qtcreator, kdevelop, codeblocks), right?

for java project, for example 2 class files: classA.java, classB.java
in classB.java import classA and write the main function with: 
    classA test;
    test.

when typing "test." autocomplete will show up "classA members", no need to type "test.xxxx".
but autocomplete show up "members" is just "sometimes" not worked for all class, i am still testing.

**Comment by b4n** [comment] 2018-04-11 17:39
@andysendo The problem you're encountering is that currently Geany's ctags

**Comment by elextr** [comment] 2018-04-11 22:09
@b4n s/local functions/local declarations/?

**Comment by elextr** [comment] 2018-04-11 22:17
@andysendo as @b4n and I said, its a known limitation of the ctags parsers.  Note that ctags is a separate [project](https://github.com/universal-ctags) not part of Geany.

Duplicate of #493

**Closed by elextr** 2018-04-11 22:17 UTC
Labels: ctags parser, filetype

**Comment by andysendo** [comment] 2018-04-12 02:35
it's not a bug report, i hope geany can do that in the feature release.
