### ISSUE TITLE
Windows true dark mode

### ISSUE THREAD

**Issue by AndiLeni** [geany/geany#2225] opened 2019-07-23 11:16 UTC
Hello,

I was looking forward to change the entire windows to dark, but the theme only changed the color of the editor.
Is it possible to set the whole programm to dark on windows?

Regards
Andi

**Comment by elextr** [comment] 2019-07-23 11:19
The rest of the widgets are controlled by the GTK theme, not sure how to set that on windows @eht16 ?

**Comment by codebrainz** [comment] 2019-07-23 14:32
Duplicate of #1935 and #1604.

**Comment by AndiLeni** [comment] 2019-07-23 14:49
Thanks for the answers, unfortunately I haven't used linux and therefore I am not familiar with gtk.
Could you give a short explanation of what has to be done? 
I could not find any steps to reproduce in those two issues.

Regards
Andi

**Comment by codebrainz** [comment] 2019-07-23 23:43
I don't have Windows handy to test, but the general idea is to download a Gtk2 theme you like (ex. from [here](https://www.gnome-look.org/browse/cat/136/order/latest/)). Inside, there should be folder called `gtk-2.0`, copy the files from there to the `etc/gtk-2.0` folder inside Geany's installation folder (probably backup any files in there in case you want to go back). You will likely have to restart Geany for the changes to take effect.

I can't seem to find any good documentation either, but you can reach out on the [GTK+ mailing list](https://www.gtk.org/mailing-lists.php) or [IRC](https://wiki.gnome.org/Community/GettingInTouch/IRC) for support.

The main thing to take into account if you're using the official Geany release, is that it's GTK+2 (version 2), not GTK+3 (version 3); a lot of stuff changed between those versions, most notably the entire theming mechanism.

**Comment by AndiLeni** [comment] 2019-07-24 08:37
Downloading a theme and putting it in the gtk-2.0 folder works in some parts.
Actually it looks like this:

![grafik](https://user-images.githubusercontent.com/13385771/61778456-127da280-adff-11e9-8228-2a929a6d46b8.png)

**Comment by AndiLeni** [comment] 2019-07-24 09:02
Update:
The stylish-gtk-theme works pretty fine.
https://www.gnome-look.org/p/1013743/

![grafik](https://user-images.githubusercontent.com/13385771/61780164-4dcda080-ae02-11e9-8f21-ec49a4b8fd3b.png)

**Comment by codebrainz** [comment] 2019-07-24 14:29
Good stuff, glad you got it to work.

**Closed by codebrainz** 2019-07-24 14:29 UTC
Labels: duplicate, existing capability, gtk-theme, question

**Comment by cyberhardt** [comment] 2023-05-29 17:46
> Update: The stylish-gtk-theme works pretty fine. https://www.gnome-look.org/p/1013743/
> 
> [1920×1280 png99 kB![grafik](https://user-images.githubusercontent.com/13385771/61780164-4dcda080-ae02-11e9-8f21-ec49a4b8fd3b.png)](https://user-images.githubusercontent.com/13385771/61780164-4dcda080-ae02-11e9-8f21-ec49a4b8fd3b.png)

hi, my bad for resurrecting this, but how did you manage to use it and not have your checkboxes red like this? 

![image](https://github.com/geany/geany/assets/107224222/eeb62cb6-87e6-4104-bbc0-c316e09b3bea)

**Comment by arthurfprecht** [comment] 2023-10-28 15:20
> > Update: The stylish-gtk-theme works pretty fine. https://www.gnome-look.org/p/1013743/
> > [1920×1280 png99 kB![grafik](https://user-images.githubusercontent.com/13385771/61780164-4dcda080-ae02-11e9-8f21-ec49a4b8fd3b.png)](https://user-images.githubusercontent.com/13385771/61780164-4dcda080-ae02-11e9-8f21-ec49a4b8fd3b.png)
> 
> hi, my bad for resurrecting this, but how did you manage to use it and not have your checkboxes red like this?
> 
> ![image](https://user-images.githubusercontent.com/107224222/241783933-eeb62cb6-87e6-4104-bbc0-c316e09b3bea.png)

Hi! I think I managed to make it work, to get the checkboxes working, you need to copy the "assets" folder (inside gtk3 folder of your theme of choice) and paste it to the same folder where "geany.css" is. At least for me this worked (to change the theme I just copied the contents of "gtk.css" to "geany.css" that you can open from Tools->Configuration Files on Geany):

![image](https://github.com/geany/geany/assets/44984671/809e6e8c-24c3-48a6-82cb-be77cf6fcde9)


The checkboxes look like this:
![image](https://github.com/geany/geany/assets/44984671/0eba08bd-a2f8-42a7-ab25-e96ff1c77ca6)
