### ISSUE TITLE
Setting SciTEGlobal properties

### ISSUE THREAD

**Issue by DevynCJohnson** [geany/geany#2068] opened 2019-01-28 16:24 UTC
Correct me if I am wrong, but I do not see a way to change the width of the folding margin. It also appears that `fold.on.open` does not work in Geany. Could a feature be added so that users have access to setting the properties that would normally be seen in a `SciTEGlobal.properties` file? For instance, I am needing to change `fold.margin.width=24` and `fold.on.open=1`.

**Comment by elextr** [comment] 2019-01-28 21:49
Scite properties files are part of Scite and not Scintilla, the part Geany uses.  However there are settings that are part of Scintilla that are currently fixed values and could be given settings, probably in filetypes.common.

**Comment by andy5995** [comment] 2019-02-05 03:54
@elextr Yeah, I think I could do this. But which hard-coded settings do you want converted?

**Comment by elextr** [comment] 2019-02-05 04:52
@andy5995 Ahh, well, yeah, finding them is the issue!!

The problem is that its not all in the one place I'm afraid, for example some are set in [editor.c::create_new_sci()](https://github.com/geany/geany/blob/bf5c9eddd8a500577719af7fc7f1c1ffb8044a49/src/editor.c#L4900) but the margin widths as mentioned in the OP are hard coded [here](https://github.com/geany/geany/blob/bf5c9eddd8a500577719af7fc7f1c1ffb8044a49/src/sciwrappers.c#L149) and I bet there are other places in that file where values are hard coded that could be variable.

And of course there are places where Geany doesn't set a value at all, relying on the Scintilla default, you would have to find those from the Scintilla docs.  Using find-in-files on all of Geany should help.

Probably best to create an issue and list those that you find, and if you think they make sense to be variable. That way others can provide any advise they are aware of, such as "No that will conflict with XXX".

But then do them one at a time by pull request so they are simple and (hopefully) fast to merge.  Large pull requests tend to sit because reviewers and committers are short of time.

**Comment by andy5995** [comment] 2019-05-03 03:31
I've tried to start on this in #2140. Would anyone be able to give me clues on how to start working on it? I started the draft pull request (2140) to hopefully make it a bit easier to guide me a little with line comments...

**Comment by andy5995** [comment] 2019-05-16 18:40
I'll back out of this now and leave it open for someone who knows how to do it xD

**Comment by andy5995** [comment] 2019-07-10 15:52
With help from @codebrainz and @elextr I was able to get a [working PR](#2140) to change the width of the folding margin, in the queue for review.

**Comment by DevynCJohnson** [comment] 2019-07-13 03:59
@andy5995 , @codebrainz , and @elextr  Thanks for your time.

**Comment by elextr** [comment] 2020-06-23 05:14
Fixed by #2140

**Closed by elextr** 2020-06-23 05:14 UTC
Labels: enhancement
