### ISSUE TITLE
Support for Julia Language

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#2279] opened 2019-08-28 21:54 UTC
Julia has reached 1.0 version for a while and its syntax is stable now. The current editors for Julia are either too complicated (vim and emacs) or too big (atom and vscode), it would be great if Geany can provide some basic support for Julia Language.

**Comment by elextr** [comment] 2019-08-28 22:30
There are three parts to adding a filetype:

1. making a custom filetype file defining a language optionally using an existing Scintilla lexer for highlighting (not sure if any will work, or just get confused by Julia syntax) and an existing uctags parser for symbol recognition (though I doubt any will actually recognise Juila types `Array{Quantity{Int64,D,U} where U where D,1}` or do the level of inferencing Julia does)

2. add a Lexer to Scintilla and add it to Geany and move the filetype to internal.

3. add a symbol parser to uctags and integrate it into Geany

Pull requests are welcome (AFAIK no existing contributors use Julia, so somebody needs to contribute it).

**Comment by elextr** [comment] 2019-08-28 22:43
Duplicate of https://github.com/geany/geany/issues/434 which has started the process

**Closed by elextr** 2019-08-28 22:43 UTC
