### ISSUE TITLE
Can't see underscores in Linux Mint 20

### ISSUE THREAD

**Issue by crazyBaboon** [geany/geany#2722] opened 2021-01-08 14:53 UTC
Using Linux Mint 20 (cinnamon edition), the underscores disappear. 

I can only see them when i zoom in or if i change the default font.

Thanks!

**Comment by abdulbadii** [comment] 2021-01-08 16:05
It's a **Pinned Issue**, https://github.com/geany/geany/issues/2502

**Comment by crazyBaboon** [comment] 2021-01-08 16:55
@abdulbadii , thanks but that issue is closed, but the problem is out there!

**Comment by elextr** [comment] 2021-01-08 22:30
@crazyBaboon did you try the solution given in the pinned issue?

**Comment by elextr** [comment] 2021-01-10 07:40
Duplicate of #2502

**Closed** 2021-01-10 07:50 UTC
Labels: waiting for information, workaround available
