### ISSUE TITLE
Incorrect selection length calculation with cyrillic text

### ISSUE THREAD

**Issue by wrgcpp** [geany/geany#2202] opened 2019-06-20 06:25 UTC
When text contains cyrillic symbols and user selects some text, the selection length displayed in bottom status bar is incorrect. By fact, it is twice as much as it actually is. It looks like a size of selected string in bytes (UTF-8), but not a length. This problem is similar to #1958 . Geany version is 1.35.
![geany1](https://user-images.githubusercontent.com/6756060/59825630-fb561b80-934d-11e9-89e7-5336a593bddb.PNG)
![geany2](https://user-images.githubusercontent.com/6756060/59825638-fee9a280-934d-11e9-80d9-89e8a383f1f9.PNG)

[geany_sample.txt](https://github.com/geany/geany/files/3309042/geany_sample.txt)

**Comment by elextr** [comment] 2019-06-20 06:32
Duplicate of #745

**Closed by elextr** 2019-06-20 06:32 UTC

**Comment by jesus2099** [comment] 2021-01-20 12:30
@wrgcpp, when your ticket is closed as duplicate, please upvote the original ticket to show the demand: 

1. Go to #745
2. Click the smiley button (top right) and
3. Click 👍

**Comment by elextr** [comment] 2021-01-20 12:35
@jesus2099 no point, github makes an entry in the original noting the duplicate.
