### ISSUE TITLE
Html tag name delete last letter crash

### ISSUE THREAD

**Issue by bvirtual** [geany/geany#1847] opened 2018-04-29 23:27 UTC
On Ubuntu 16.04 release 1.27 (not tested on latest 1.33 by me) when editing an HTML file, and deleting the last letter of a HTML tag, Geany crashes.  The window disappears.  Your edits are not saved.  Recent file list is not saved.  How to duplicate is below
```
<p>
paragraph text here
</p>
```
Position the mouse cursor after the p in the tag <p>, and press backspace.

That easy.

I imagine it has to do with syntax highlighting, and it fails to find a 'tag' value for the HTML Start Tag, that "used to exist".  I did not turn off syntax highlighting to find out.

I did search GitHub for a similar issue report, but the keywords I used (two sets) found none.

**Comment by elextr** [comment] 2018-04-30 00:42
If you have the `pair tag highlighter ` pluginb enabled, try with it disabled.  Was fixed in 1.28 IIRC.

**Comment by codebrainz** [comment] 2018-04-30 06:37
Duplicate of #989, #1016, #1056, #1262, geany/geany-plugins#432, geany/geany-plugins#442, geany/geany-plugins#446, [130](https://sourceforge.net/p/geany-plugins/bugs/130/), etc.

**Closed by codebrainz** 2018-04-30 06:37 UTC
