### ISSUE TITLE
Geany Scope shows blank window

### ISSUE THREAD

**Issue by ohaessler** [geany/geany#1048] opened 2016-05-31 09:46 UTC
If you load geany scope, load a simple "Hello world" software written in C compiled with -g, and you start the execution with geany scope you obtain a blank window without text or buttons and geany freeze.. so geany scope is unusable...
geany scope 1.27 in Fedora 24 with italian language

reported in https://bugzilla.redhat.com/show_bug.cgi?id=1341107

**Comment by elextr** [comment] 2016-05-31 09:52
This repository is for Geany itself.

Scope is a plugin that is part of the geany-plugins project which has a separate repository and issues [here](https://github.com/geany/geany-plugins/issues).

Please report plugin issues to the geany-plugins project.

**Comment by LarsGit223** [comment] 2018-03-12 21:16
Duplicate of #1461 - it should be closed.

**Closed** 2018-03-12 21:19 UTC
Labels: invalid
