### ISSUE TITLE
Mac OS dark mode complier color in the Message Window

### ISSUE THREAD

**Issue by zz273** [geany/geany#2647] opened 2020-11-07 20:41 UTC
Hi all,

I just downloaded Geany 1.37. The full dark mode is beautiful. But when I compile the code, the color in the Complier Window is not clear. (attached) 

<img width="326" alt="Screen Shot 2020-11-07 at 15 38 38" src="https://user-images.githubusercontent.com/60077140/98450956-5b01c200-210f-11eb-8e9f-4e017c3ee89d.png">

I also try to block the dark mode specific to Geany using: `defaults write org.geany.geany NSRequiresAquaSystemAppearance -bool yes`. But the color of the compile window is still dark when I restart Geany.

Could anyone help me with that? I appreciate any advice.

Thanks in advance!

**Comment by codebrainz** [comment] 2020-11-07 21:01
Sounds related to the recent https://github.com/geany/geany/issues/2644 and similar previous issues.

**Comment by zz273** [comment] 2020-11-07 21:03
Hi @codebrainz, thank you for your reply. But I was wondering maybe I can block the dark mode specific to Geany? Do you think it is possible?

**Comment by codebrainz** [comment] 2020-11-07 21:05
I have no idea about Macos, I was just linking your issue to the others about the bad colours when dark mode/themes are used, sorry.

**Comment by zz273** [comment] 2020-11-07 21:09
No problem. Thanks for your reply!

**Comment by codebrainz** [comment] 2020-12-23 10:27
Duplicate of #1376, #1737, #2293, #2644, etc.

**Closed by codebrainz** 2020-12-23 10:27 UTC
