### ISSUE TITLE
Non-integer font sizes only work in preview, not in actual editor

### ISSUE THREAD

**Issue by leitold** [geany/geany#772] opened 2015-11-24 14:48 UTC
This seems to be an issue related to a new version of GTK or GLib, as did work fine for me until a system upgrade. The problem is, after clicking View->Change Font, that non-integer font sizes do not work in the main editor any more. Example: The default editor font is Monospace, Regular, size 12. Now I would like to change the size to 12.5, as this is somewhat larger while still not looking "bold" as a size of 13 would. In the small preview line in the bottom of the font selector, the change from 12 to 12.5 is clearly visible. However, this change is not translated to the main editor window any more, only changes of integer size are.

Geany details: geany 1.26 (built on 2015-11-24 with GTK 2.24.23, GLib 2.40.2)
OS: Xubuntu 14.04 with XFCE 4.10 (Ubuntu 14.04.3 LTS)

**Comment by codebrainz** [comment] 2015-11-24 15:32
Duplicate of #703

**Closed by codebrainz** 2015-11-24 15:32 UTC
