### ISSUE TITLE
No search results changes font color of search key

### ISSUE THREAD

**Issue by kommaklar** [geany/geany#1267] opened 2016-10-18 15:24 UTC
Using the find or replace dialog the font color of the text entered into the 'search for' field changes to white when nothing is found. The text is still there but only readable when selected.

However, the original color for the font returns when running a new search that does yield results.

Geany 1.28, de_DE.UTF-8, GTK 2.24.31, GLib 2.50.1

**Comment by codebrainz** [comment] 2016-10-18 21:52
Duplicate of #1135 and fixed in #1137.

**Closed by codebrainz** 2016-10-18 21:52 UTC
