### ISSUE TITLE
Geany did not notify to save  when logging off from OS that is set with save session for future logins.

### ISSUE THREAD

**Issue by PthDE** [geany/geany#3975] opened 2024-10-04 20:24 UTC
geany 2.0 (built on Oct 23 2023 with GTK 3.24.38, GLib 2.78.0)

OS ManjaroLinux 24.1.0 Xahea
OS Kernel 6.6.52-1-MANJARO (linux66)

File type *.ino (Arduino IDE 2 code file)

After some extensive editing, user logged-off to return to log-in screen, with OS set to save session for future logins.

Immediately logged back in, saved session was returned to, Geany opened correctly, bringing the cursor to the same position immediately prior to where editing began.

The file had not been saved by the logging out process and all changes to the file are lost.

**Comment by elextr** [comment] 2024-10-04 23:32
Short form:  when your system does logout it simply stops Geany, effectively crashing it, so nothing is saved.

Long form: Geany is a portable application, it runs on Windows, Macos, and all Linux desktops, and each Linux desktop has different session management methods.  Geany does not have the available effort to interface with all those session management methods, so claims __by the session management__ (not by Geany) that sessions are saved are false since session managements do not interface with Geany and do not allow time to save anything.

Duplicate of https://github.com/geany/geany/issues/3946

**Closed by elextr** 2024-10-04 23:32 UTC
