### ISSUE TITLE
Under Windows geany couldn't open file which was found by grep utility (Cygwin) with non ascii filename.

### ISSUE THREAD

**Issue by NTMan** [geany/geany#783] opened 2015-11-30 05:41 UTC
Under Windows geany couldn't open file which was found by grep utility (Cygwin) with non ascii filename.

![under windows geany couldn t open file which was found by grep utility cygwin with non ascii filename](https://cloud.githubusercontent.com/assets/200750/11464269/bf157aca-974e-11e5-9268-597d8f83895c.png)

show error message: "Invalid byte sequence in conversion input"

**Comment by eht16** [comment] 2015-11-30 08:41
I'm not sure whether it makes a difference but could you try the grep tool which is bundled with UnxUtils? This one has been tested and works well with Geany (though this is no guarantee it will solve the problem).

http://unxutils.sourceforge.net/UnxUpdates.zip

More probably, we need to convert the result from the grep command before using it.

**Comment by NTMan** [comment] 2015-11-30 09:18
http://unxutils.sourceforge.net/UnxUpdates.zip
same here

You can reproduce my problem with folder "борода" from attached archive.
[111.7z](https://files.zenhub.io/565c141adf514c140280843a)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by techee** [comment] 2015-12-12 18:25
I fixed some utf8/locale problems in the patch here:

https://github.com/geany/geany/pull/547

which might fix this issue too.

**Comment by eht16** [comment] 2015-12-13 16:20
Unfortunately, #547 doesn't help here.
I'll debug this problem in detail in the next days.

**Comment by techee** [comment] 2015-12-13 17:03
> Unfortunately, #547 doesn't help here.
> I'll debug this problem in detail in the next days.

Pity, then it has to be something Windows-specific.

**Comment by eht16** [comment] 2015-12-15 16:34
Got a few more details:
at first, this is a problem in grep.exe (at least this one distributed with Geany, maybe other/better binaries are out there):

if I run the grep command on the cmd.exe, I also get the `grep: ./??????: Invalid argument` result. But in your screenshot you got those squares.
![win32_grep_unicode](https://cloud.githubusercontent.com/assets/617017/11814977/ed323d42-a349-11e5-9ada-d11d0ead4202.png)

For futher testing, I created a directory with a German umlaut (`lalelö`).
Result in cmd.exe:
![win32_grep_mixed_cmd](https://cloud.githubusercontent.com/assets/617017/11814994/022d542a-a34a-11e5-9b6e-ebcf2d4b72b1.png)

Result in Geany:
![win32_grep_mixed_geany](https://cloud.githubusercontent.com/assets/617017/11814996/074105e2-a34a-11e5-8bc6-e7ce3568c3a7.png)

cmd.exe displays the folder name `lalelö` correctly but is not able to display correctly the UTF-8 encoded search result.

In Geany, the result is vice-versa: the folder name is displayed incorrectly but the UTF-8 parts are displayed properly.

So, related to #784, we probably need to convert the output from external commands back from UTF-16 to UTF-8. Though I doubt whether this can ever work properly if in the same output there is also UTF-8 encoded text. At least I have no idea how this could work.

For curiosity, I just tested grep.exe from the MSYS2 environment:
![win32_msys2_grep_mixed_geany](https://cloud.githubusercontent.com/assets/617017/11816518/041f3e2c-a351-11e5-8aa3-c34405843ea6.png)

So yeah, MSYS2 grep.exe seems to work nicely with Geany.
@NTMan it would be cool if you could test the grep.exe in the archive at http://repo.msys2.org/msys/x86_64/grep-2.22-1-x86_64.pkg.tar.xz. This is exactly the same as I used for the last test (verified with md5sum). I'm not sure whether this binary is supposed to work without a MSYS2 environment and I cannot test this.

**Comment by NTMan** [comment] 2015-12-16 08:01
2015-12-15 21:34 GMT+05:00 Enrico Tröger <notifications@github.com>:

> Got a few more details:
> at first, this is a problem in grep.exe (at least this one distributed
> with Geany, maybe other/better binaries are out there):
>
> if I run the grep command on the cmd.exe, I also get the grep: ./??????:
> Invalid argument result. But in your screenshot you got those squares.
> [image: win32_grep_unicode]
> <https://cloud.githubusercontent.com/assets/617017/11814977/ed323d42-a349-11e5-9ada-d11d0ead4202.png>
>
> For futher testing, I created a directory with a German umlaut (lalelö).
> Result in cmd.exe:
> [image: win32_grep_mixed_cmd]
> <https://cloud.githubusercontent.com/assets/617017/11814994/022d542a-a34a-11e5-9b6e-ebcf2d4b72b1.png>
>
> Result in Geany:
> [image: win32_grep_mixed_geany]
> <https://cloud.githubusercontent.com/assets/617017/11814996/074105e2-a34a-11e5-8bc6-e7ce3568c3a7.png>
>
> cmd.exe displays the folder name lalelö correctly but is not able to
> display correctly the UTF-8 encoded search result.
>
> In Geany, the result is vice-versa: the folder name is displayed
> incorrectly but the UTF-8 parts are displayed properly.
>
> So, related to #784 <https://github.com/geany/geany/issues/784>, we
> probably need to convert the output from external commands back from UTF-16
> to UTF-8. Though I doubt whether this can ever work properly if in the same
> output there is also UTF-8 encoded text. At least I have no idea how this
> could work.
>
> For curiosity, I just tested grep.exe from the MSYS2 environment:
> [image: win32_msys2_grep_mixed_geany]
> <https://cloud.githubusercontent.com/assets/617017/11816518/041f3e2c-a351-11e5-8aa3-c34405843ea6.png>
>
> So yeah, MSYS2 grep.exe seems to work nicely with Geany.
> @NTMan <https://github.com/NTMan> it would be cool if you could test the
> grep.exe in the archive at
> http://repo.msys2.org/msys/x86_64/grep-2.22-1-x86_64.pkg.tar.xz. This is
> exactly the same as I used for the last test (verified with md5sum). I'm
> not sure whether this binary is supposed to work without a MSYS2
> environment and I cannot test this.
>
>
>
​grep from cygwin​




​​grep from msys​


​

both return file path ok for my system.

**Comment by NTMan** [comment] 2015-12-16 09:17
​grep from cygwin​
![grep_msys](https://cloud.githubusercontent.com/assets/200750/11836932/9c3d95f6-a3ff-11e5-97e5-c76bc92960bf.png)

​​grep from msys​
![grep_cygwin](https://cloud.githubusercontent.com/assets/200750/11836931/9c3af6a2-a3ff-11e5-921d-a9f71bd76931.png)

**Comment by NTMan** [comment] 2015-12-16 10:12
Hmmm found very interesting thing 
https://www.youtube.com/watch?v=H6sG80DMj8k
Result depends on the encoding used for the search. using encoding win1251 for search give normal result, but search into UTF-8 files became impossible.

**Comment by NTMan** [comment] 2015-12-17 09:29
If the problem seems related to convert GREP output from search encoding into internal encoding. On Linux machines this is not works (search result not depend from Encoding parameter) always search in utf-8 encoding, and console works in utf-8 encoding too. So all is well for the user until it begins to look for in a different encoding. On Windows the situation is different, the console work in encoding 1251. If we look for encoding 1251 all good, if you look for in a different encoding all bad.

![screenshot from 2015-12-17 13-57-32](https://cloud.githubusercontent.com/assets/200750/11866055/555a7be2-a4ca-11e5-83fa-d4c7480727eb.png)

Also update my archive, add file ttt.txt with encoding win1251
[111.7z](https://files.zenhub.io/5672805f0a670d7d20f0f21b)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by NTMan** [comment] 2015-12-18 04:38
https://youtu.be/s89z2bZkgjk

**Comment by stdex** [comment] 2015-12-25 21:25
+1
Ubuntu 14.04
Geany 1.27
Search in files not working for windows-1251

**Comment by eht16** [comment] 2016-01-02 21:01
For the Linux part, even `grep` on the command line doesn't find text in a Windows-1251 encoded text file on my system. And this is when I pass a plain ASCII search term to `grep`.
It seems `grep` treat these files as binary files and in Geany we explicitly ignore binary files (via command line parameter -I). If you add "-a" to the extra options field in the FiF dialog, `grep` will treat binary files as text files and the search seems to work, at least in my case.

**Comment by NTMan** [comment] 2016-01-19 04:53
I am not sure. But seems workaround not work for me (

![geany_search_in_files](https://cloud.githubusercontent.com/assets/200750/12410013/554d924c-be92-11e5-9c45-b5d4afeea36e.png)

**Comment by elextr** [comment] 2016-01-19 08:07
The message window is UTF-8, it has to be.  When geany reads the filename it passes what it finds it to `document_open_file()` [here](https://github.com/geany/geany/blob/master/src/msgwindow.c#L1128) without first converting it to locale.

**Comment by eht16** [comment] 2016-01-20 23:03
@NTMan the workaround with `grep -a` mentioned above works only on Linux. This was not related to the Windows issue which seems different.
In comment https://github.com/geany/geany/issues/783#issuecomment-165042911 you seem to have tested the MSYS grep only on the command line but not in Geany, based on your screenshots.
Could you configure your Geany to use the MSYS grep (Preferences->Tools) and then try FiF in Geany again as in the first post of this issue?
For me it is less relevant how grep works in cmd.exe, what Geany does is relevant and for me the MSYS grep worked well. Otherwise we need further testing/debugging of the test case.

**Comment by NTMan** [comment] 2016-01-24 19:58
> Could you configure your Geany to use the MSYS grep (Preferences->Tools) and then try FiF in Geany again as in the first post of this issue?

I am change PATH variable and restart Geany for it. As I said above correct path displayed only if I force search in 1251 encoding. But this workaround impossible if I want find UTF8 text in files.

![screenshot from 2016-01-25 00-52-47](https://cloud.githubusercontent.com/assets/200750/12538574/c90b3250-c2fe-11e5-920e-98ca9557f123.png)

**Comment by NTMan** [comment] 2016-01-24 20:16
If on Linux I use workaround (search in encoding 1251 with parameter -a) then I am get broken path in search results.

![screenshot from 2016-01-25 01-14-13](https://cloud.githubusercontent.com/assets/200750/12538676/4f9767ce-c301-11e5-8135-4c7e6a59fda7.png)

**Comment by eht16** [comment] 2016-02-02 22:15
Hmm, I'm a bit out of ideas especially I cannot reproduce your issues then :(.

**Comment by NTMan** [comment] 2016-02-08 18:53
> I cannot reproduce your issues
Please, download updated archive 111.7z
And try experiment with 1251 encoding.

**Comment by eht16** [comment] 2016-11-13 17:24
This should be fixed now in Geany 1.29 (released today).
We merged #1301 and the Windows installer has a `grep` version from the MSYS2 project bundled which seems to work fine with non-ASCII files and paths.

**Closed by eht16** 2016-11-13 17:24 UTC
Labels: workaround available
