### ISSUE TITLE
file/open "Could not read the contents of Desktop 

### ISSUE THREAD

**Issue by cnoblejr** [geany/geany#2415] opened 2020-01-03 01:51 UTC
file/open "Could not read the contents of Desktop Error opening directory 'Users/carlnoble/Desktop': Operation not permitted. MacOS 10.15.2   Geany 1.33 and 1.36.
Cannot navigate left menu with mouse or arrow keys once carlnoble is clicked.

Chmod 777 Directory didn't change anything.  All other operations from other applications are fine.

Planned to use Geany for my middle school students starting next 2 weeks, but cannot with this.

C

**Comment by elextr** [comment] 2020-01-03 02:07
duplicate of #2344 ?

**Comment by techee** [comment] 2020-03-22 13:24
I believe this issue is fixed in the latest release based on GTK 3. Feel free to reopen this issue if you still experience the problem.

**Closed by techee** 2020-03-22 13:24 UTC
