### ISSUE TITLE
Set preferred UI language

### ISSUE THREAD

**Issue by JanAxelsson** [geany/geany#2619] opened 2020-10-11 11:29 UTC
Some translations have faults, and it would be a nice feature to be able to set the UI language.  Specifically, it would be nice to allow for the system-way to set languages (for MacOS, see)

There are methods reported to set env variable LANG, prior to launch from command line, but that method breaks stuff such as opening from the system, right-click and select Geany, and many more.  

The suggestion is to :
1) allow for a preference within Geany
2) alternatively, use the build-in system way (for macos :  https://beebom.com/how-customize-language-settings-specific-apps-macos-catalina/ , but I am sure the other systems have their own ways) -- this may not be as easy to find for people as 1), though

I would prefer method 1)

**Comment by elextr** [comment] 2020-10-11 22:11
Duplicate of #1757.

And specifically see the [comment](https://github.com/geany/geany/issues/1757#issuecomment-362868750) explaining why in-program settings won't work.

Method two might work if it sets the LANG environment variable before running the program.

**Closed by elextr** 2020-10-11 22:11 UTC
