### ISSUE TITLE
Please tell me how to set a short cut key for 

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#2821] opened 2021-06-07 14:01 UTC
Please tell me how to set a short cut key for the highlighted menu item?  Thanks! 

![image](https://user-images.githubusercontent.com/7548378/121030052-09064500-c7a1-11eb-870d-661e9f72ee7d.png)

**Comment by elextr** [comment] 2021-06-08 00:13
As you currently have it laid out its not see the [manual](https://www.geany.org/manual/current/index.html#build-menu-keyboard-shortcuts)

But if you used one of the execute commands for execute you would have one spare compile command for upload that can get a keybinding.

**Comment by ntrel** [comment] 2023-02-10 17:38
Duplicate of #705.

**Closed** 2023-02-10 17:39 UTC
