### ISSUE TITLE
Bash - Shell Script Colorizer is Broken 

### ISSUE THREAD

**Issue by AdamDanischewski** [geany/geany#1549] opened 2017-07-19 23:36 UTC
I've got a Bash script and it is using arrays (something the other shells don't have, maybe that's why this isn't more thoroughly tested?). It cannot handle nested parenthesis, I'm not sure if this problem is actually Scintilla. 

Here is how to reproduce, enter the following into a file t.bsh: 
```
#!/bin/bash 
declare -a MYARRAY

MYARRAY+=("intentional aor unintentional features")
MYARRAY+=("(intentional aor unintentional) features")
MYARRAY+=("((intentional) aor (unintentional)) errors")
MYARRAY+=("((intentionally) aor (unintentionally)) broken")

echo "this should not look this way" 
```
Then open it in Geany and have a look at the coloring. It breaks on the nested parenthesis in the third array element.

**Comment by elextr** [comment] 2017-07-19 23:52
Confirmed with 1.31, problem does not appear with Scite 3.6.0 (whats in my distro), can anybody test with Scite 3.7.4 which has the same Scintilla as Geany 1.31?

**Comment by LarsGit223** [comment] 2017-07-20 16:13
I downloaded and built SciTe 3.7.4, the file looks like this after opening:
![testbashinscite374](https://user-images.githubusercontent.com/9009011/28427586-f2cc43da-6d76-11e7-9c25-3b7dd44db165.png)

SciTe shows the following version numbers in the about dialog:
Version 3.7.4 compiled for GTK+ 2.24.30 Jul 20 2017 18:04:40

**Comment by AdamDanischewski** [comment] 2017-07-20 16:34
It looks like someone broke Scintilla, I've launched a bug ticket on Scintilla: 
https://sourceforge.net/p/scintilla/bugs/1963/

**Comment by LarsGit223** [comment] 2017-07-20 17:11
Update: it looks good in SciTe 3.7.5:
![testbashinscite375](https://user-images.githubusercontent.com/9009011/28430006-229f62d8-6d7f-11e7-98ad-4875bc7f9d79.png)

So it seems like it has been fixed already .

**Comment by LarsGit223** [comment] 2017-07-20 17:14
I assume it was fixed with this ticket: https://sourceforge.net/p/scintilla/bugs/1944/

**Comment by AdamDanischewski** [comment] 2017-07-20 17:19
Thanks, I hope so. I'll let them close it themselves if it has, I don't have the environment to test.

**Comment by LarsGit223** [comment] 2017-07-21 08:49
I cloned, compiled, installed and tested with b4n's branch scintilla/update-375. With that version this problem is solved. So I can confirm that PR #1503 would fix this.

**Comment by elextr** [comment] 2017-07-21 08:51
@LarsGit223 thanks for testing #1503, it should be included in the next Geany release, so hopefully this will be fixed then.

**Comment by LarsGit223** [comment] 2017-07-21 08:54
:thumbsup: Great!

**Comment by AdamDanischewski** [comment] 2017-07-21 19:08
Thanks, when the next release is out it should be easy to quickly test and then we can close this. In the meantime if anyone is frustrated about this a workaround is to temporarily comment out the problematic array element assignments - that will put the highlighting back to normal and you can develop the remainder of the code then uncomment the array assignments when you are ready to start executing.

**Comment by LarsGit223** [comment] 2017-11-20 18:56
I downloaded and built release 1.32 and re-tested this. Looks good, I think this can be closed.

**Closed** 2017-11-20 19:00 UTC
Labels: bug, confirmed, scintilla

**Comment by AdamDanischewski** [comment] 2017-11-20 21:24
Note: This issue is fixed, yet the colorization is still wrong for HERE-DOC's. It is broken in Scintilla there is an open bug yet it's a low priority, it should probably get "auto-fixed" via Scintilla at some point.

**Comment by LarsGit223** [comment] 2017-11-20 21:46
I suggest that you open a new issue for that with a specific example code which reproduces the problem.
