### ISSUE TITLE
Crash on ctrl-c large amounts of text

### ISSUE THREAD

**Issue by mothlight** [geany/geany#2752] opened 2021-02-19 02:53 UTC
Doing a copy of a large amount of text always crashes geany. 

This is an example of a file that crashes:
wget "https://neo.sci.gsfc.nasa.gov/servlet/RenderData?si=1784251&cs=rgb&format=CSV&width=360&height=180"

To reproduce: Open file, ctrl-a, ctrl-c
and geany crashes and disappears.

$ uname -a
Linux mu00038561 4.4.0-197-generic #229-Ubuntu SMP Wed Nov 25 11:05:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ dpkg -l geany
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  geany          1.27-1       amd64        fast and lightweight IDE

$ gdb -ex run --args geany -v "RenderData?si=1784251&cs=rgb&format=CSV&width=360&height=180" 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from geany...(no debugging symbols found)...done.
Starting program: /usr/bin/geany -v RenderData\?si=1784251\&cs=rgb\&format=CSV\&width=360\&height=180
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Geany-INFO: Geany 1.27, en_AU.UTF-8
Geany-INFO: GTK 2.24.30, GLib 2.48.2
Geany-INFO: System data dir: /usr/share/geany
Geany-INFO: User config dir: /home/kerryn/.config/geany
[New Thread 0x7fffee0c6700 (LWP 12732)]
[New Thread 0x7fffed8c5700 (LWP 12733)]
[New Thread 0x7fffed0c4700 (LWP 12734)]
Geany-INFO: System plugin path: /usr/lib/x86_64-linux-gnu/geany
Geany-INFO: Added filetype Cython (61).
Geany-INFO: Added filetype Scala (62).
Geany-INFO: Added filetype Genie (63).
Geany-INFO: Added filetype Graphviz (64).
Geany-INFO: Added filetype JSON (65).
Geany-INFO: Added filetype CUDA (66).
Geany-INFO: Added filetype Clojure (67).
Geany-INFO: /home/kerryn/git/2019-04-CRC-IRP4/SalisburyFInal/Analysis/test/PrecinctUTCIData3.csv : None (UTF-8)
Geany-INFO: /media/kerryn/87d9469d-56aa-4a1f-a62d-5f03d7599bbf/Data/NDVI2/2020/RenderData?si=1784251&cs=rgb&format=CSV&width=360&height=180 : None (UTF-8)
The program 'geany' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 6801 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[Thread 0x7fffed8c5700 (LWP 12733) exited]
[Thread 0x7fffee0c6700 (LWP 12732) exited]
[Thread 0x7ffff7f6c980 (LWP 12728) exited]
[Inferior 1 (process 12728) exited with code 01]
(gdb)

**Comment by elextr** [comment] 2021-02-19 03:40
The message:

```
The program 'geany' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
(Details: serial 6801 error_code 3 request_code 18 minor_code 0)
```

tells you what the problem is, the GTK library and the X server got confused about something.  

How big is the file? How much free memory do you have? Is some internal limit of the X11 clipboard being exceeded?

Version 1.27 of Geany is nearly 5 years old, perhaps try a new version (1.37.1 now) and see if the problem persists.

**Comment by mothlight** [comment] 2021-03-02 22:31
I compiled 1.37.1 from Github and am not able to reproduce the problem in 1.37.1.

I filed a bug with Ubuntu to see if they can update the version in 16.04:
https://bugs.launchpad.net/ubuntu/+source/geany/+bug/1917086

**Comment by elextr** [comment] 2021-03-02 22:40
Ubuntu backporting to LTS with a life left of two months (as I write this) isn't anything we can change, but given that lifetime you would probably be better to upgrade to 18.04 LTS pretty soon anyway.

Closing as fixed

**Closed by elextr** 2021-03-02 22:40 UTC
Labels: waiting for information
