### ISSUE TITLE
cannot compile with shared object

### ISSUE THREAD

**Issue by mbmxush** [geany/geany#837] opened 2015-12-21 10:46 UTC
Hi all,
I created a share object (.so) - libds.so.
I am trying, successfully to debug it through gdb:
gcc -g test.c -lds

However, when i am trying to debug through geany, i get an error immediately: 
program existed with error 127

just to mention - everything else is working just fine (compiling with static library, makefiles etc).

**Comment by elextr** [comment] 2015-12-21 10:54
How are you running the debugger "through geany" ?

**Comment by mbmxush** [comment] 2015-12-21 12:47
Hi elextr,
Thanks for your response.
I am just trying to take advantage of geany's gui. I am uploading the target executable, marking several breakpoints and running the debugger.  
Please note that all of the build is done outside (through terminal operations), because i am changing it to rapidly to update geany's build setup each time.

**Comment by b4n** [comment] 2015-12-21 14:29
> I am trying, successfully to debug it through gdb:
> gcc -g test.c -lds

This is not a GDB command, but a GCC one, building a file named test.c, adding debugging info and linking `libds`.

Running under GDB would look like
```console 
$ gdb a.out
...
(gdb) run
...
```

BTW, note that Geany doesn't have any builtin debugger, but three plugins: *debugger*, *scope* and *geanygdb*, so it's unlikely to be a Geany issue.
And code 127 usually means "program not found", so maybe you just don't have GDB installed?

**Comment by mbmxush** [comment] 2015-12-21 14:43
I probably stepped ahead too much.
What I meant is - I am compiling and linking via terminal.
I can run the executable via gdb or via geany debugger plugin.
The only time I get the error is when compilation was done with a shared object.

**Comment by elextr** [comment] 2015-12-21 19:35
How are you starting Geany?  If its not in the same environment as the terminal you successfully use gdb under then the loader search path for the shared object might not be the same.  This often happens when starting Geany from system menus since they are not a terminal environment.

**Comment by mbmxush** [comment] 2015-12-21 20:13
I am starting it through the terminal: 
geany prog.c
the very same terminal where i later compile and use gdb.

**Comment by codebrainz** [comment] 2015-12-21 20:36
> [...] geany debugger plugin

Which debugger plugin? Is the one called "Debugger"? You might try the "Scope" plugin as it has had more maintenance recently.

**Comment by mbmxush** [comment] 2015-12-21 20:59
Hi codebrainz.
Yes, i was referring to the Debugger plugin. I'll try scope but this seems a little bit weird, why should geany behave differently when compiling with a shared object? i mean, standard c libraries, such as stdio, are working just fine...

**Comment by elextr** [comment] 2015-12-21 21:07
@mbmxush nowhere have you said what system you are running on and what version of geany you are using

**Comment by mbmxush** [comment] 2015-12-21 21:16
Sorry, i am new to bug reporting :)
I am using ubuntu 14.04 LTS 64 bit.
Geany version is 1.25.

**Comment by codebrainz** [comment] 2015-12-21 21:22
@mbmxush it could be as @elextr eluded to, that your library search paths are different. You could try to run Geany like this: `LD_LIBRARY_PATH=/path/to/your/shared/lib/dir geany prog.c`

**Comment by kugel-** [comment] 2015-12-22 18:11
This doesn't look like a Geany bug so I suggest closing.

**Comment by mbmxush** [comment] 2015-12-22 19:04
My LD_LIBRARY_PATH is set correctly, as I manage to compile and link with shared object successfully. Something is going amiss whilst trying to debug such a file from geany Debugger...

**Comment by kugel-** [comment] 2015-12-22 19:15
The debugger you mention is an external plugin, perhaps there is a bug.

You could check in the integrated terminal if LD_LIBRARY_PATH is set.

**Comment by mbmxush** [comment] 2015-12-22 19:16
Alright, i'll try to do that.

**Comment by elextr** [comment] 2015-12-22 21:16
Or compile your program with RUNPATH set.

**Comment by kugel-** [comment] 2016-03-06 09:46
Not a bug (?)

**Comment by elextr** [comment] 2016-03-06 10:18
Would appear to be plugin related, not Geany anyway.

**Comment by codebrainz** [comment] 2019-04-03 00:47
Closing since if this is a bug, it seems not to be a Geany bug as noted by @kugel- and @elextr.

**Closed by codebrainz** 2019-04-03 00:47 UTC
Labels: plugin
