### ISSUE TITLE
End the program(program crashes) when I try to auto-complete the code.

### ISSUE THREAD

**Issue by Spiker01** [geany/geany#1927] opened 2018-08-21 13:47 UTC
Hello everybody.
My technical specifications:

```
uname -a
Linux SpSystem 4.10.0-38-generic # 42 ~ 16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU / Linux

Geany => Help => About.
Geany 1.27 (collected Apr 17 2016 or later).

geany -V
geany 1.27 ((collected Apr 17 2016 or later) GTK 2.24.30, GLib 2.48.0)
```

I installed plugins for Geany from the official Linux / GNU Mint repositories, everything is fine. I did this, because I needed to double the tags, for example in HTML. I did this with the plugin. Everything worked.

After a while I decided that I want to include the autocompletion of words. I enabled simple autocompletion through the settings, the first tick in the settings: Edit / Settings. In the settings window, select "Editor", "Autocompletion" tab, "Auto-complete code snippets" parameter).

In the future work suddenly, for the first time the editor closed. I propose it to an emergency. I ran it again. Everything worked, but when editing the file, if you get to the point where, in theory, the list with options for autocompletion may fall out, the program automatically ends without outputting any error, the window just closes (disappears).

I decided to disable autocompletion and the problem disappeared. Now I write the required code with my hands, without the possibility of an automatic add-on. The program is relatively stable. Paired tags are highlighted.

I do not know very well the terms from programming in English. I hope I clearly explained.

I decided to notify Geany developers about this issue so I am writing here. In some of the newest code editing programs (such as Atom), auto-completion usually works without lags and (or) critical errors. Geany should not fall behind, in my opinion. I hope the problem will be solved in the future.

I can provide almost any files in my system for additional information on this issue. I can conduct various tests at your request (Acceptable for me) when I have free time.

Thank you for watching.

**Comment by codebrainz** [comment] 2018-08-21 14:58
Is this a duplicate of #989, #1016, #1056, #1262, geany/geany-plugins#432, geany/geany-plugins#442, geany/geany-plugins#446, [130](https://sourceforge.net/p/geany-plugins/bugs/130/), #1847, etc?

**Comment by elextr** [comment] 2018-08-21 19:49
@codebrainz Yeah probably.

**Comment by elextr** [comment] 2018-08-21 19:53
@Spiker01 also 1.27 is a pretty old version, please try the latest version to see if its fixed.

**Comment by Spiker01** [comment] 2018-08-21 22:16
@elextr Thanks for the advice. I tried to download the latest version (1.33) from the official site. Configured, assembled(make), installed. After installation, the version 1.27 is also launched from the menu and the command geany -V also issues version 1.27. I attach the file with the output of the console "make install" : l https://gist.github.com/Spiker01/3e7aa50fffdc73e8cb2df8c2a01d02ef#file-makeintstallgeany133-txt-L86 Am I doing something wrong, is there a mistake?

If You may, tell me the best ways to install.

**Comment by elextr** [comment] 2018-08-22 02:13
Unfortunately the official builds are distro neutral, so they won't replace your desktop menu or other definitions set by the official version for that distro.

Try running geany from $prefix/bin (where $prefix is the prefix you used when building, or default /usr/local IIRC).

**Comment by elextr** [comment] 2018-08-22 03:45
Depending on your PATH of course.

**Comment by Spiker01** [comment] 2018-08-22 09:42
@elextr @codebrainz My paths to the established geany 1.27 :

```
user01@SpSystem ~ $ whereis geany
geany: /usr/bin/geany /usr/local/bin/geany /usr/local/lib/geany /usr/include/geany /usr/share/geany /usr/share/man/man1/geany.1.gz
```

I not understand completely: Do I need to use the make command with the keys or do I need to move the already installed files with my hands? I do not often collect files from source. I will be grateful if You write "ready" GNU/Linux commands.

**Comment by elextr** [comment] 2018-08-22 20:42
You need to run the right geany, `/usr/local/bin/geany`.

**Comment by Spiker01** [comment] 2018-09-05 23:01
Thank you all. I solved the problem. Has connected Geany repositories for developers.
https://launchpad.net/~geany-dev/+archive/ubuntu/ppa
```
sudo add-apt-repository ppa: geany-dev / ppa
sudo apt-get update
```
Installed (updated) package Geany: 
`sudo apt-get install geany`
Everything is working.I enabled code autocompletion. Now program no crashes.

**Closed** 2018-09-05 23:11 UTC
Labels: resolved
