### ISSUE TITLE
Copy word at cursor position, when no selection is made

### ISSUE THREAD

**Issue by tjeck46** [geany/geany#3148] opened 2022-04-04 18:30 UTC
When you press Ctrl-F (find) then the word at the cursor position is automatically selected. It would be great if the same logic was true when you press Ctrl-C, to copy the word at the cursor position, without having to mark the word first. Thanks! :-)

**Comment by elextr** [comment] 2022-04-04 23:24
Duplicate of #197 #558 #565 and others.

Rejected.

The explanation that says it best is [this](https://github.com/geany/geany/pull/197#issuecomment-31388209).

**Closed by elextr** 2022-04-04 23:24 UTC
