### ISSUE TITLE
Shutting down before closing Geany does not save which files are open  

### ISSUE THREAD

**Issue by lrh3370** [geany/geany#2839] opened 2021-07-08 02:15 UTC
Repro
1. Blank Geany state (No files opened)
2. Close Geany
3. Open Geany and open a file
4. Shutdown or restart your computer
5. The state of which files are opened is not saved

**Comment by elextr** [comment] 2021-07-08 03:44
Duplicate of #1416 and #1826 and probably others.

**Closed by elextr** 2021-07-08 03:44 UTC
