### ISSUE TITLE
Switching between tabs with mouse wheel

### ISSUE THREAD

**Issue by thinslice** [geany/geany#1967] opened 2018-10-02 19:48 UTC
I miss this feature a lot from the builds of Geany that are compiled to Gtk3.
I know, it was removed with the Gtk2 -> Gtk3 switch, as the toolkit itself removed it.

I would like it to be there again, with an optional setting to turn it on/off (to reap whatever benefits it has to not have it).

Is it possible to implement it?

**Comment by codebrainz** [comment] 2018-10-02 22:50
Duplicate of #872 and #1848 (enhancement request to re-implement the feature) and related/duplicate of #1778 and #1815 (about losing the feature).

**Closed** 2019-03-25 23:50 UTC
Labels: duplicate, enhancement, gtk
