### ISSUE TITLE
Does not preserve file's ACL

### ISSUE THREAD

**Issue by Safari77** [geany/geany#2252] opened 2019-08-09 08:33 UTC
```
$ getfacl  wrlr.txt
# file: wrlr.txt
# owner: safari
# group: safari
user::rw-
group::rw-
group:rpm:r--
mask::rw-
other::r--
```
```$ geany wrlr.txt```
```
$ getfacl  wrlr.txt
# file: wrlr.txt
# owner: safari
# group: safari
user::rw-
group::rw-
other::r--
```

keywords: ```getxattr``` ```setxattr```

**Comment by elextr** [comment] 2019-08-09 08:35
Duplicate of #2251

**Closed by elextr** 2019-08-09 08:35 UTC
