### ISSUE TITLE
Content of new not yet saved files is lost on crash

### ISSUE THREAD

**Issue by j1warren** [geany/geany#2931] opened 2021-10-11 17:01 UTC
If one creates a new file, but doesn't save it (giving it a name and a path), then it's content is lost on crash.

Would be nice if Geany would periodically save content of these new "untitled" tabs in case of crash/power loss.
At least in some ~/.config/geany file, so the user can restore it later.

**Comment by elextr** [comment] 2021-10-11 22:03
Duplicate of #905 and #2717

**Closed as completed by elextr** 2021-10-11 22:03 UTC
