### ISSUE TITLE
Implement multiple text selection mode

### ISSUE THREAD

**Issue by drws** [geany/geany#1605] opened 2017-09-15 12:13 UTC
Besides ordinary text selection by using mouse cursor Geany also implements the awesome block select functionality when holding ctrl+alt which is very useful at times. However, there is one more selection mode I'd find useful which is called somewhere along the lines of "multi select". It would be an option to select multiple parts of text at once, accessible while holding down only the ctrl button for example (which currently does nothing). For a more clear explanation I'm also appending this mock-up image:

![image](https://user-images.githubusercontent.com/1191893/30481515-71a15018-9a1f-11e7-98ea-fc826275af65.png)

**Comment by elextr** [comment] 2017-09-15 13:06
The underlying editing widget supports multiple selections, so"all" it needs is somebody to change all the editing code in Geany to understand multiple selections.  Pull requests are welcome.

Duplicate of #1141, #850

**Closed by elextr** 2017-09-15 13:06 UTC
Labels: duplicate
