### ISSUE TITLE
Underscore is not always visible

### ISSUE THREAD

**Issue by GFdevelop** [geany/geany#2353] opened 2019-10-11 21:54 UTC
```
OS: Arch Linux x86_64
Resolution: 1366x768 @ 60.05Hz
DE: Budgie
WM: Mutter(Budgie)
```
```
Geany 1.36, it_IT.UTF-8
GTK 3.24.12, GLib 2.62.1
Font: Monospace Regular, 10
```

From geany 1.36 I can't see the underscore:

![geany-underscore](https://user-images.githubusercontent.com/17930457/66687056-b0a43a80-ec81-11e9-9166-d7f02df7a43d.gif)

**Comment by elextr** [comment] 2019-10-11 22:37
Duplicate of #2287, see that for workaround of faulty fonts.

Note: the times its visible in your example is when the colour scheme selects bold which the font clearly has right.

**Closed** 2019-10-11 22:37 UTC

**Comment by bencaradocdavies** [comment] 2020-04-08 02:15
(Copied from https://github.com/geany/geany/issues/2466)

I just got the `line_height` workaround to work with excellent results. The `line_height` setting can be found in "Tools" > "Configuration Files" > "filetypes.common". To change this setting from its default `line_height=0;0;` there are two things to note:

* `#~` lines are commented and have no effect.
* The file format is an [INI file](https://en.wikipedia.org/wiki/INI_file) so uncommenting the `line_height` line is insufficient because the `[styling]` section is also required; either uncomment this line or add a new `[styling]` section at the end.

The only uncommented lines in my filetypes.common are now:

```
[styling]
line_height=0;2;
```

With this setting and DejaVu Sans Mono Book size 12, underscores are visible. Using `line_height=0;1;` also works, but `line_height=0;2;` gives me, for the first time ever, exact agreement (as far as I can tell) with the line height in xfce4-terminal.
